### ISSUE TITLE
Should DataFrames reexport StatsBase?

### ISSUE THREAD

**Issue by cstjean** [JuliaStats/DataFrames.jl#1003]
Both StatsBase.jl and ScikitLearn.jl export a different `fit!` function, and it's causing ambiguity errors. This is fine and legitimate, but is there a reason why `DataFrames.jl` should export all of `StatsBase.jl`? DataFrames are used in a lot of non-statistical applications.

**Comment by quinnj** [comment]
Should be easy up-for-grabs issue.

**Comment by quinnj** [comment]
Oh, I just realize that StatsBase _isn't_ actually re-exported anymore, only CategoricalArrays & Nulls.jl.
