### ISSUE TITLE
Error insert data float

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaStats/DataFrames.jl#1010]
Given a example:
numbers = csv"""
  a    ,   b
"""
a = 10.0; b = 5.0

push!(numbers, [1.0, 5.0] )
+---+---+---+
|      | a | b |
+---+---+---+
| 1   | 1 | 5 |
+---+---+---+
ok

push!(numbers, [1.0, 5.5] )
LoadError: ArgumentError: Error adding 5.5 to column :b. Possible type mis-match.
while loading In[197], in expression starting on line 1

How to solve?

**Comment by ararslan** [comment]
I'm not entirely sure why, but it appears that when you initialize a dataframe like that, it assumes the columns are all integers.

```julia
julia> numbers = csv"""
       a, b
       """
0×2 DataFrames.DataFrame

julia> numbers.columns
2-element Array{Any,1}:
 Int64[]
 Int64[]
```

The first `push!` works because 1.0 and 5.0 can both be cast to integers, but 5.5 causes the push to fail because trying to convert 5.5 results in an `InexactError`. That error gets caught and the error you're getting is thrown instead.

**Comment by jmarcellopereira** [comment]
ok, I got it. but ... how to solve?

**Comment by ararslan** [comment]
The only thing I can think of offhand would be to avoid initializing the dataframe with 0 rows. For example, you could do

```julia
numbers = DataFrame(a = [1.0], b = [5.0])
push!(numbers, [1.0, 5.5])
```

**Comment by jmarcellopereira** [comment]
hum ... also follows this idea but would like to use the first, because I found very interesting.

**Comment by ararslan** [comment]
Yeah, like I said I don't know why initializing an empty dataframe as in your original approach would make everything integers. So I'm kind of stumped as to how to proceed with that approach. Hopefully someone here who more intimately understands this package will chime in. :)

**Comment by jmarcellopereira** [comment]
I understand. well ... I, out of curiosity, I use this code, in which an empty dataframe starts and the data is entered by the push !.

**Comment by jmarcellopereira** [comment]
thanks ararslan ;)

**Comment by nalimilan** [comment]
Basically, we can't do much without information on column types. Creating a `Vector{Any}` would be convenient, but it would be a performance trap for users. I think we should do like `readtable` and raise an error. Use `DataFrame(a=Float64[], b=Float64[])` instead to add floats later.

**Comment by jmarcellopereira** [comment]
Hi nalimilan.
Now, in julia 5.0 it works perfectly.

**Comment by ararslan** [comment]
Glad to hear things are working for you now. Since your issue appears to be resolved, I'll go ahead and close the issue.
