### ISSUE TITLE
Can writetable write to a stream?

### ISSUE THREAD

**Issue by ahalwright** [JuliaStats/DataFrames.jl#1011]
It would be very useful if the writetable function could write to an IO stream as well as a file.

**Comment by johnmyleswhite** [comment]
This would be a good first PR to make. You should be able to copy the approach in `writemime` to generalize `printtable`: https://github.com/JuliaStats/DataFrames.jl/blob/b774e5ad6c02c9ec6ad7e3c04be143e5299e899a/src/abstractdataframe/io.jl

**Comment by quinnj** [comment]
Just FYI, `CSV.write(io, dataframe)` is already supported in the `CSV.jl` package. The package has continued to evolve here and there, but has been pretty steady lately. I'm working on getting more docs/examples out there so it's more obvious everything that is supported, but you can pass any generic `IO` type to `CSV.write` to write out a DataFrame.

**Comment by quinnj** [comment]
`readtable` `writetable` are now deprecated in favor of CSV.jl or TextParse.jl
