### ISSUE TITLE
Sort ignores numeric column names

### ISSUE THREAD

**Issue by mwsohn** [JuliaStats/DataFrames.jl#1020]
For example,

sort!(df,cols=[:2,:3])

does not sort the data by columns :2 and :3. Instead, 2nd and 3rd columns are used for sorting.

**Comment by joshday** [comment]
The issue is that you aren't using symbols.  
```
julia> typeof([:2, :3])
Array{Int64, 1}
```

Symbols aren't meant to begin with a number.  See: http://stackoverflow.com/questions/34858166/julia-dataframe-columns-starting-with-number

**Comment by nalimilan** [comment]
I didn't know that `:1` was parsed into `1`. I'd prefer if it returned an explicit error. Could you file an issue in Julia itself?
