### ISSUE TITLE
convert column of type '::DataArrays.NAtype' to '::Float64'

### ISSUE THREAD

**Issue by krauti** [JuliaStats/DataFrames.jl#1026]
Hi all,
I'm constructing a DataFrame, and try to add couple of columns. One is containing only NA values, so the way I do it is:
`df[:newCol] = NA`
However I need it to be of the type `Float64`, and currently I do not find a good option to convert the type of the DataFrame column. My best approach would be 
`df[:newCol] = map(Float64,df[:newCol])`
but there is no method defined for this action.

I think this has worked in the past (I found this in an old *.jl file), but it just won't work in the current version of DataFrames.

**Comment by ararslan** [comment]
So if I understand the issue correctly, you want `NA` to be a `Float64`?

**Comment by kleinschmidt** [comment]
I think you're better off constructing a `DataArray{Float64}` [directly](https://github.com/JuliaStats/DataArrays.jl/blob/master/src/dataarray.jl#L109)

```julia
df[:newCol] = DataArray(Float64, (nrow(df), ))
```

**Comment by krauti** [comment]
@ararslan 
I usually append a lot of dataframes to a "master" dataframe.
The columns in questions usually hold a Float64 value, and if I read from file, it assigns the type  `Float64`, even if there are NA values in there.
However, some files don't have that field, and I append a column to the DataFrame , with the value `NA`.
This gets another type assigned, making 
`append!(df_master,df_in)`
impossible. Thus the conversion of the column.
@kleinschmidt 
thanks for this solution, I will try it. I had a temporary solution, that is not really efficient:
```
df =  @byrow! df begin
        @newcol newColumn::Array{Float64}
        :newColumn = NA
```
---
In general, I would welcome to batch convert the eltypes a bunch of columns, defined by a Vector. Something like:
`convert_eltypes(df::DataFrame,columns::Vector,eltypes::Vector)`

**Comment by kleinschmidt** [comment]
That might be useful; pull requests are welcome or you can open another issue for that. I think it's a separate issue from the original one here, which is about initializing a column to all NA with the correct type. The correct way to do that is to construct a `DataArray` directly, like above.
