### ISSUE TITLE
Model matrix is broken the same variable is present on both sides of `~`.

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/DataFrames.jl#1032]
This was not tested here but in the `statsquiz.jl` in `StatsBase`.
```
julia> ModelMatrix(ModelFrame(x~x, nasty))
ERROR: BoundsError: attempt to access 0-element Array{Array{Float64,2},1} at index [1]
 in expandcols(::Array{Array{Float64,2},1}) at /Users/andreasnoack/.julia/v0.6/DataFrames/src/statsmodels/formula.jl:377
 in DataFrames.ModelMatrix{T<:Union{Float32,Float64}}(::DataFrames.ModelFrame) at /Users/andreasnoack/.julia/v0.6/DataFrames/src/statsmodels/formula.jl:472
```
It broke during 90f700e1c988c3e228cf56bee43f02538d8be542

**Comment by ararslan** [comment]
Hah, I was just about to file an issue for this. Thanks for correctly bisecting, sorry for misidentifying the offending commit before.

**Comment by ararslan** [comment]
cc @dmbates

**Comment by kleinschmidt** [comment]
I know I submitted a PR to fix this, but now I'm wondering if it's behavior that we want to allow. Or, rather, how opinionated the formula DSL should be about what is a well-formed formula. Is there _any_ situation where the response variable would also appear on the RHS?

**Comment by dmbates** [comment]
@kleinschmidt I agree that it would be unusual to have the same variable on the right and left-hand sides if the purpose is to create a model matrix.

I think the general approach of model terms and evaluation terms and the role of the response should be revisited.  Unfortunately I say this just as I am starting vacation and will be without internet access for about 10 days.  Anyway, the current way of storing information on the response is copied from the R formulation and is not a very Julian approach.  It seems to make more sense to store a symbol or expression for the response and evaluate it with respect to the model frame when needed.  It doesn't really need to be mixed with the model terms for the model matrix.
