### ISSUE TITLE
ModelMatrix fails for mixed effects models without an intercept

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/DataFrames.jl#1035]
Currently if you construct a mixed effects model with no other terms or an intercept, `reduce` throws an error. For example,
```julia
df = DataFrame(x = [1,2,3], y = [4,5,6])
mf = ModelFrame(y ~ 0 + (1 | x), df)
ModelMatrix(mf)
```
currently produces
```julia
ERROR: ArgumentError: reducing over an empty collection is not allowed
 in _mapreduce(::Base.#identity, ::Base.#hcat, ::Base.LinearFast, ::Array{Array{Float64,2},1}) at ./reduce.jl:148
 in DataFrames.ModelMatrix{T<:Union{Float32,Float64}}(::DataFrames.ModelFrame) at /Users/ararslan/.julia/DataFrames/src/statsmodels/formula.jl:482
```
This happens because when you get the set of terms as `droprandomeffects(dropresponse!(mf))` and there's no intercept, the current logic still lets the case get through to the end, but without adding anything to a vector of blocks, which gets `reduce`d at the end.

Before @dmbates' overhaul of model matrices, the above code produced `DataFrames.ModelMatrix{Float64}(,Int64[])`.

I'm not sure what we actually want to do in this situation since there isn't really a model matrix to construct, but if it should be an error then we should make it an explicit one.

Side note: It appears a test in FixedEffectModels relies on something like this working. See [here](https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/test/reg.jl#L38)

**Comment by dmbates** [comment]
@ararslan Such a mixed-effects model would be very unusual and probably nonsensical so I am not concerned that it would fail.  Mixed-effects models have two model matrices, X and Z, where X is the model matrix for the fixed-effects terms and Z comes from the random-effects terms.  The model formula you have given would result in X having 0 columns.   Exactly what that would mean is not clear.  The random effects coefficients are assumed to have a mean of zero and any non-zero mean is absorbed into the fixed effects.   A model without an X is making some very strong assumptions about the form of the response.

If you want to have the model matrix code capable of producing a model matrix with 0 columns for the sake of completeness then I think that checking for no intercept and a terms.terms object of length 0 will do the trick.

I am on vacation for the next 10 days with limited Internet access.  If you feel it is urgent to pursue this then do so but I feel it is a non-issue.

**Comment by ararslan** [comment]
Right, I get that such a model doesn't actually make sense, but I still think we should have some kind of behavior consciously defined in this case. If it's something that's come up in a test in another package then that suggests to me that our choice of behavior here affects another package's behavior downstream, so I feel the need to tread somewhat carefully.

The decision here could be as simple as choosing one of these two options:

1. Return `DataFrames.ModelMatrix{Float64}(,Int64[])` as before
2. Throw an explicit error, like `ERROR: Could not construct model matrix. Resulting matrix has 0 columns.`

I'd be fine with either, but with a slight preference for the latter.

**Comment by nalimilan** [comment]
I agree raising an error is clearer, as long as we don't have a correct use case for this formula.

**Comment by ararslan** [comment]
Is there a correct use case where a model matrix can't be constructed?
