### ISSUE TITLE
Test fails on windows

### ISSUE THREAD

**Issue by abhijithch** [JuliaStats/DataFrames.jl#1037]
Package tests fails for statsmodel.jl when it is trying to run `bash stdin.sh`.

**Comment by ararslan** [comment]
It doesn't seem to be failing on AppVeyor, the Windows CI we're using. I'm not very familiar with Windows specifics, but are you running Julia from cmd or another place without Bash? In the Julia REPL, does `;` (enter shell mode) then `bash --version` work?

**Comment by amellnik** [comment]
It's passing for me with DataFrames master and 0.5.0-rc3.

**Comment by nalimilan** [comment]
@abhijithch Can you post the full output?
