### ISSUE TITLE
Unstack fails when DataFrame column begins with NA

### ISSUE THREAD

**Issue by chipkent** [JuliaStats/DataFrames.jl#1039]
unstack appears to fail when the DataFrame value column begins with a NA.  The reproducer below demonstrates the problem.  Example output follows.

https://gist.github.com/chipkent/83081d8aa2cfee1cbef074ed6a0cb37b

GOOD permutation...start
10×3 DataFrames.DataFrame
│ Row │ S   │ D    │ V    │
├─────┼─────┼──────┼──────┤
│ 1   │ "B" │ "d1" │ 6.0  │
│ 2   │ "B" │ "d3" │ NA   │
│ 3   │ "B" │ "d5" │ 10.0 │
│ 4   │ "A" │ "d4" │ 4.0  │
│ 5   │ "A" │ "d1" │ 1.0  │
│ 6   │ "A" │ "d2" │ NA   │
│ 7   │ "A" │ "d5" │ 5.0  │
│ 8   │ "B" │ "d2" │ 7.0  │
│ 9   │ "A" │ "d3" │ 3.0  │
│ 10  │ "B" │ "d4" │ 9.0  │
GOOD permutation worked
BAD permutation...start
10×3 DataFrames.DataFrame
│ Row │ S   │ D    │ V    │
├─────┼─────┼──────┼──────┤
│ 1   │ "B" │ "d3" │ NA   │
│ 2   │ "B" │ "d1" │ 6.0  │
│ 3   │ "B" │ "d5" │ 10.0 │
│ 4   │ "A" │ "d4" │ 4.0  │
│ 5   │ "A" │ "d1" │ 1.0  │
│ 6   │ "A" │ "d2" │ NA   │
│ 7   │ "A" │ "d5" │ 5.0  │
│ 8   │ "B" │ "d2" │ 7.0  │
│ 9   │ "A" │ "d3" │ 3.0  │
│ 10  │ "B" │ "d4" │ 9.0  │
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{DataArrays.NAtype}, ::Float64)
This may have arisen from a call to the constructor DataArrays.NAtype(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, !Matched::T)
  DataArrays.NAtype()
 in setindex! at /cc/home/chip/.julia/v0.4/DataArrays/src/indexing.jl:208
 in unstack at /cc/home/chip/.julia/v0.4/DataFrames/src/abstractdataframe/reshape.jl:187
 in unstack at /cc/home/chip/.julia/v0.4/DataFrames/src/abstractdataframe/reshape.jl:192

julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by amellnik** [comment]
This also occurs on DataFrames master and 0.5.0-rc3.  The problem is that unstack forms an empty DataFrame with DataArrays for columns that take their type from the first element in the key column.  Excellent bug report.  #1041 passes tests for me and fixes the example shown in this gist.
