### ISSUE TITLE
readtable() and files containing trailing tabs or colons ...

### ISSUE THREAD

**Issue by aa-em** [JuliaStats/DataFrames.jl#1044]
Hello:

while using the DataFrames.jl for importing some "non-standard" csv or tsv files I ran into an issue.
In the case when the file ends with some empty "cells" the readtable command fails. For better explanation a small example.

```
Cell1 \t Cell2 \t Cell3 \t Cell4 \newline
1 \t 2 \t 3 \t 4 \newline
1 \t 2 \t 3 \t 4 \newline
\t \t
```

The readtable command will fail with the following error:

`ERROR: LoadError: Saw 3 rows, 3 columns and 11 fields
- Line 1 has 6 columns`

Is this the intended behavior of the code? Isn't there any failure handling?

**Comment by ViralBShah** [comment]
Can you try using `CSV.jl`?

**Comment by aa-em** [comment]
This fails anyway:

```
df = CSV.read("xxx.txt")
ERROR: MethodError: `convert` has no method matching convert(::Type{DataStreams.Data.Schema}, ::Array{UTF8String,1}, ::Array{Any,1}, ::Int64)
This may have arisen from a call to the constructor DataStreams.Data.Schema(...),
since type constructors fall back to convert methods.WARNING: Error showing method candidates, aborted

 in call at essentials.jl:57
 in Source at /Users/xxx/.julia/v0.4/CSV/src/Source.jl:179
 in Source at /Users/xxx/.julia/v0.4/CSV/src/Source.jl:34
 in read at /Users/xxx/.julia/v0.4/CSV/src/Source.jl:291
 in read at /Users/xxx/.julia/v0.4/CSV/src/Source.jl:269
```

But this is not the place to discuss this here, right?!

**Comment by nalimilan** [comment]
I don't think the goal is to support files with varying number of cells per line. The CSV "standard" is already very complex without that. Though, to be sure I understand: in your file, not only the last line contains only empty cells, it contains only three cells, right?

**Comment by quinnj** [comment]
You should be able to do the following with CSV.jl
```julia
Pkg.checkout("CSV") # currently needs master on 0.4
df = CSV.read("xxx.txt"; footerskip=1)
```
this tells the parser to skip the last row of the file.

CSV.jl relevant because eventually, `DataFrames.read_table` will probably just call out to `CSV.jl` for delimited-file parsing. CSV.jl currently supports reading delimited files into a variety of "sinks", beyond just a DataFrame.

**Comment by tcovert** [comment]
Does there exist a way of using this CSV.read() trick that generates an old-school DataFrame, not one with NullableArray columns?

**Comment by quinnj** [comment]
No, and it probably won't be supported officially due to DataFrames themselves moving to NulllableArrays by default (see #1008). It's not very hard to write a non-copying conversion to a DataArray though.

**Comment by amellnik** [comment]
@aa-em: see for example my comment here: https://github.com/JuliaStats/DataFrames.jl/issues/933

**Comment by quinnj** [comment]
Tracking this issue here: https://github.com/JuliaData/CSV.jl/issues/99
