### ISSUE TITLE
julia dataframe changing one cell changes entire row

### ISSUE THREAD

**Issue by xximranxx** [JuliaStats/DataFrames.jl#1051]
Consider the following code, where I want to change only 1 cell, but the entire row gets changed:

```
df=DataFrames.DataFrame(A=[1,2],B=[3,4])

df[2,:A]=7 # this is OK, changes only 1 cell

df[:,1:end]=0.0 # this line somehow makes the change in the next line behave unexpectedly

df[2,:A]=7 # entire 2nd row is 7

```

It's as if the df[:,1:end]=0.0 sets all the cells of that row to the same reference; but I am setting it to 0.0, so I expect this to be a value copy, not reference copy

Versions: julia version 0.4.6-pre DataFrames v"0.7.8"

Btw, I first put this on stackoverflow: http://stackoverflow.com/questions/39320783/julia-dataframe-changing-one-cell-changes-entire-row

**Comment by nalimilan** [comment]
Thanks for the report. Indeed, `df[:,1:end]=0.0` makes both columns share the same underlying array: after runing it, `df[:A] === df[:B]`. This also happens with `df[1:end]=0.0`, which that method calls under the hood. It's kind of worrying nobody noticed this bug before.

Looks like we just need a `copy` call in the latter method when calling `insert_single_column!`.

**Comment by nalimilan** [comment]
BTW, please post the link to this issue on StackOverflow. In general, it's a good idea to post only in one place, and cross-post only if you don't get a reply after a few days; and bug reports better go to GitHub than SO.

**Comment by xximranxx** [comment]
You are right, I thought of github second after stackoverflow, else I would have only posted here
