### ISSUE TITLE
RDatasets broken by recent deprecations in DataFrames

### ISSUE THREAD

**Issue by tlnagy** [JuliaStats/DataFrames.jl#1054]
Gadfly's tests are broken (https://github.com/dcjones/Gadfly.jl/issues/890) on the latest release of `DataFrames` due to https://github.com/JuliaStats/DataFrames.jl/pull/1031 being merged and breaking `RDatasets`. Thought I would post this here since `RDatasets` is pretty low traffic.

@ararslan @nalimilan

**Comment by Mattriks** [comment]
There's a PR to fix this [johnmyleswhite/RDatasets.jl#43](https://github.com/johnmyleswhite/RDatasets.jl/pull/43)

**Comment by nalimilan** [comment]
Thanks for the heads up. Let's close this since there's a PR.
