### ISSUE TITLE
readtable appends "_" to the first column if the file is UTF-8

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/DataFrames.jl#1063]
I found a strong candidate for "most bizarre 0.5-related" error.  This occurs on `DataFrames` master on Windows x64 with 0.5-rc3 but not on 0.4.x.  I have two files, both of which contain the following text:

```
"BLAH","EH","WUT","MEH"
"111","177","222","333"
```

If I save the file with ANSI encoding then `readtable` spits out the expected `DataFrame`:

```
1×4 DataFrames.DataFrame
│ Row │ BLAH │ EH  │ WUT │ MEH │
├─────┼──────┼─────┼─────┼─────┤
│ 1   │ 111  │ 177 │ 222 │ 333 │
```

If I save the file with UTF-8 encoding then I get:

```
1×4 DataFrames.DataFrame
│ Row │ _BLAH │ EH  │ WUT │ MEH │
├─────┼───────┼─────┼─────┼─────┤
│ 1   │ 111   │ 177 │ 222 │ 333 │
````

I'm looking more into this now, but opening the issue in case anyone has an idea what might be going on.

**Comment by johnmyleswhite** [comment]
Can you post a hexdump of the files in both encodings? `_BLAH` looks like the kind of thing we do when your column name isn't a valid symbol?

**Comment by quinnj** [comment]
There is a common option which is `save as UTF-8 w/ BOM`, which adds the ["BOM"](https://en.wikipedia.org/wiki/Byte_order_mark) character at the very beginning of the file. I think in Sublime, you have the option to save it with or without the BOM.

**Comment by amellnik** [comment]
UTF-8 without BOM works as expected, UTF-8 with BOM adds the _.  The image below shows the hex for the version w. BOM on top, w/o BOM on the bottom.

![image](https://cloud.githubusercontent.com/assets/7132414/18290382/1427bbb0-7438-11e6-916e-c683d141d5fc.png)

**Comment by johnmyleswhite** [comment]
Assuming CSV.jl handles this correctly, this might deserve a "wontfix" since we should move over to CSV.jl anyway and it might take a lot of work to respect the BOM.

**Comment by quinnj** [comment]
no, I don't think CSV.jl does anything special to handle this case. A user is allowed to provide their own headers and skip the first row if they want, which would be a workaround. It wouldn't be too hard to add something like this though: auto-detect the presence of the BOM and skip over.

**Comment by johnmyleswhite** [comment]
Oh, but I think you arguably want to respect the BOM and use it to modify your parsing strategy, unless Julia is doing that behind the scenes for us already.

**Comment by nalimilan** [comment]
UTF-8 BOMs are not useful nor recommended by the standard. Though skipping them would certainly be useful, either at the Julia level or in CSV.jl.

**Comment by quinnj** [comment]
or just not support big-endian :)

No, but really, the parsing in CSV.jl is all byte-based, so I believe julia handles this for us already.

**Comment by nalimilan** [comment]
@quinnj There's no big- or little-endian in UTF-8. BOMs are only useful for UTF-16 and UTF-32.

**Comment by quinnj** [comment]
right right.

**Comment by amellnik** [comment]
The problematic CSV files were being generated by a node-based server I wrote, where I followed someone's dodgy jsfiddle too closely and was intentionally appending the BOM to the start of the file.  It looks like this issue will not arise in normal situations, so I'll go ahead and close for now.
