### ISSUE TITLE
Deprecation tests are failing

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/DataFrames.jl#1064]
We're relying on RDatasets' use of `DataFrames.read_rda` to test for a deprecation warning given by `read_rda` by redirecting STDERR and looking for the deprecation message. However, a recently merged RDatasets PR (that was subsequently tagged) fixes the deprecation warning, so there's no message for us to read in the test.

I see two possible courses of action here:

1. Add an RDA file and manually read it using `read_rda` to continue to test the existence of a deprecation warning.

2. We know the deprecation works since the test had been passing until RDatasets fixed it on their end, and `read_rda` here won't change (it's only referenced in a `@deprecate`), we could just remove the test.

Thoughts?

**Comment by andreasnoack** [comment]
Let's just remove the method. It's not worth spending more time on writing a new test for this.

**Comment by ararslan** [comment]
You mean the test? Personally I don't think the deprecation period has been long enough to remove `read_rda` entirely yet.

**Comment by andreasnoack** [comment]
Yes. I meant the test.

**Comment by ararslan** [comment]
Oh, okay. Yeah, that's what I was thinking as well. I can submit a PR for it in a bit. Thanks for your input!
