### ISSUE TITLE
Export `inlinetable`

### ISSUE THREAD

**Issue by diegozea** [JuliaStats/DataFrames.jl#1068]
Hi! 

I have my data in a string. The only way to get a DataFrame from it, without writing a temporary file, is using `inlinetable`. It would be great to export that function, maybe with another name.

```
julia> mytable = """ A,B
                     1,2
                     1,3
                     2,3 """
" A,B\n1,2\n1,3\n2,3 "

julia> @csv_str(mytable)
ERROR: MethodError: `inlinetable` has no method matching inlinetable(::Symbol)

julia> @csv_str($mytable)
ERROR: MethodError: `inlinetable` has no method matching inlinetable(::Expr)

julia> csv"$mytable"
1×1 DataFrames.DataFrame
│ Row │ _mytable │
├─────┼──────────┤
│ 1   │ NA       │

julia> DataFrames.inlinetable(mytable)
3×2 DataFrames.DataFrame
│ Row │ A │ B │
├─────┼───┼───┤
│ 1   │ 1 │ 2 │
│ 2   │ 1 │ 3 │
│ 3   │ 2 │ 3 │
```

**Comment by ararslan** [comment]
Would [CSV.jl](https://github.com/JuliaData/CSV.jl) suit your needs?

**Comment by diegozea** [comment]
I've never used it before. Is there a way to get the values instead of `Nullable` objects?

```
julia> mytable = """ A,B
                     1,2
                     1,3
                     2,3 """
" A,B\n1,2\n1,3\n2,3 "

julia> CSV.read(IOBuffer(mytable))
3×2 DataFrames.DataFrame
│ Row │  A          │ B              │
├─────┼─────────────┼────────────────┤
│ 1   │ Nullable(1) │ Nullable("2")  │
│ 2   │ Nullable(1) │ Nullable("3")  │
│ 3   │ Nullable(2) │ Nullable("3 ") │
```

**Comment by diegozea** [comment]
The `IOBuffer` trick also works with `DataFrames`:

```
julia> DataFrames.readtable(IOBuffer(mytable))
3×2 DataFrames.DataFrame
│ Row │ A │ B │
├─────┼───┼───┤
│ 1   │ 1 │ 2 │
│ 2   │ 1 │ 3 │
│ 3   │ 2 │ 3 │
```

**Comment by nalimilan** [comment]
> I've never used it before. Is there a way to get the values instead of Nullable objects?

You should be able to `convert` the columns to standard vectors if you want. See NullableArrays.jl. (BTW, the next version of DataFrames will return this by default.)

**Comment by nalimilan** [comment]
Closing since you've found a reliable solution. `inlinetable` is supposed to be used for, well, inline tables via macros, I don't think exporting it is a good idea. CSV.jl is the way to go to parse more complex/bigger data.

**Comment by quinnj** [comment]
FWIW, you can do `CSV.read(io; nullable=false)` to return normal Vectors instead of NullableVectors.

**Comment by diegozea** [comment]
Thanks!
