### ISSUE TITLE
Problem with doc button on DataFrames.jl homepage

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaStats/DataFrames.jl#1073]
When I visit the DataFrames.jl home page, which is apparently here:

https://github.com/JuliaStats/DataFrames.jl

and I look for the documentation by moving to the bottom of this page and clicking on the button "docs stable" or "docs latest" in the line that looks like this:

Documentation:  docs stable    docs latest

I get a 404 error and redirected to a page with generic statistical software links.

**Comment by ViralBShah** [comment]
juliastats.org is not loading for me. Looking into it.

**Comment by ararslan** [comment]
It looks like I'm getting stuck in a redirect loop between juliastats.org and juliastats.github.io.

**Comment by nalimilan** [comment]
So this is fixed now?

**Comment by ViralBShah** [comment]
I am still getting infinite loop.

**Comment by KristofferC** [comment]
Works for me. Might have to clear some cache / DNS stuff..

**Comment by StephenVavasis** [comment]
It works for me also, but only in a different browser.  So I suppose I need to clear my browsing history.
