### ISSUE TITLE
In master, `readtable` with `makefactors = true` does not seem to produce the desired type

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataFrames.jl#1074]
The type it does produce is

``` jl
julia> typeof(df_in[:person_1_gender])
Array{Nullable{CategoricalArrays.CategoricalValue{String,UInt32}},1}
```

when it should, I think, produce a

```
CategoricalArrays.NullableCategoricalArray{String,1,UInt32}
```

Somehow the `Nullable` and `Categorical` properties are reversed.

I can look at this later in the week if no one beats me to it.

**Comment by nalimilan** [comment]
That may well indicate a missing conversion method in CategoricalArrays. These things are really complex to get right.

**Comment by nalimilan** [comment]
Can you post a reproducer? In my tests, this works correctly:
```julia
x = """
a,b
x,y
"""
d = readtable(IOBuffer(x), makefactors=true)
typeof(d[:a])
```

**Comment by nalimilan** [comment]
@dmbates Bump.

**Comment by dmbates** [comment]
Seems okay now, thanks.
