### ISSUE TITLE
readtable adds '_' to ' ' in column names

### ISSUE THREAD

**Issue by xximranxx** [JuliaStats/DataFrames.jl#1079]
I believe that spaces are now allowed in a `Symbol` in julia, i.e. `Symbol("a") != Symbol("a ")
`
It also works fine to create a `Dataframe` with column names containing spaces

`writetable` also seems to keep the spaces

However, `readtable` puts '_' where there was a ' '

Practically, this conversion is quite annoying and leads to sometimes just use an `Array` instead of a `Dataframe` because I lose column names by cycling through `readtable`, `writetable`

**Comment by johnmyleswhite** [comment]
Spaces were always allowed in Julia symbols. The relevant question is whether spaces are allowed in Julia identifiers. They are not and there is no reason to believe they ever will be allowed.

If users want to have nice macros for manipulating data, there are two viable approaches I can see: we force all column names to be valid identifiers at I/O time or we require that users fix up their own column names before they can interact with their own data using macros.

Both approaches are reasonable. We choose one approach. If a clear majority of users makes clear that they would like this to be reversed, we can change it, but a single person's vote is not sufficient.

**Comment by xximranxx** [comment]
But it seems inconsistent to me that I can create a DataFrame with a column name containing a space and when I persist this, the column name remains intact but when I read back from file, the column name is altered - also it is altered such that I cannot reverse the alteration

To me this suggests that spaces in column names are possible ... they why even convert when doing readtable? 
Else, to be consistent, why is writetable not altering the column name?

In practice, so many csv files contain spaces in the header/column names ... reading csv into a DataFrame, manipulating it then persisting back is a common process - altering the user's column names irreversibly is not 'nice' 

Perhaps if the conversion were reversable? (e.g. instead of '_' replace space with a char that is rarely used) .. just an idea

**Comment by johnmyleswhite** [comment]
I think it would be good to do more to prevent spaces from appearing in any column name, but we decided to allow people who know what they're doing to force a column name to be an invalid identifier. We could fix this as part of `writetable`.

**Comment by nalimilan** [comment]
Isn't `normalizenames=false` easy enough to find for people who really want to write a CSV file back to disk with the same column names?

I don't think replacing spaces with another special char would be helpful: either it would be a common char, and it would be confusing to convert it to another one when writing; or it would be a very rare one, and it would be very hard to type.

**Comment by xximranxx** [comment]
How about a similar option for `readtable` (`normalizenames`)?
Not allowing spaces in column names is very restrictive

**Comment by nalimilan** [comment]
What do you mean? That's an option for `readtable`.

**Comment by xximranxx** [comment]
Oops...didn't thanks for pointing this out..maybe this solves my problem :)

**Comment by nalimilan** [comment]
Anyway you should have a look at how this works in CSV.jl, since we're likely to deprecate `readtable` in favor of it relatively soon.

**Comment by xximranxx** [comment]
Ok, thanks nalimilan and johnmyleswhite
