### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tshort** [JuliaStats/DataFrames.jl#108]
This issue is to solicit ideas on documentation for the DataFrames package. 

John has gotten a great start at a manual on his branch:

https://github.com/HarlanH/DataFrames.jl/blob/simpleNAs/doc/manual.md

I put together an index file for mapping help keywords to locations in the manual.

https://github.com/HarlanH/DataFrames.jl/blob/simpleNAs/doc/_JL_INDEX_

This is based on a help prototype here::

https://github.com/tshort/HelpTestbed.jl

Please jot down any ideas you have as far as documenting, including: 

* Preferred file format (Markdown, reStructuredText, etc.)
* Best ways to organize the docs
* Preferred format for documentation functions
* Preferred tools (pandoc, sphinx, etc.)

**Comment by garborg** [comment]
Closed assuming we'll follow Julia 0.4's lead.
