### ISSUE TITLE
writetable quotemark=nothing needed

### ISSUE THREAD

**Issue by xximranxx** [JuliaStats/DataFrames.jl#1080]
I notice that `writetable`is surrounding strings with '"', which is given by `quotemark`

But `quotemark`is a `Char`and hence cannot be empty

But I want to write the `DataFrame`to a csv without any chars surrounding my strings

1) Is this already possible somehow?
2) Is this the right place to ask such questions?

**Comment by johnmyleswhite** [comment]
Re (2), questions like this should be sent to julia-users.

**Comment by kdmurray91** [comment]
Are there any plans to implement this? If not, I may have a go in a couple of weeks. This deficiency affected me recently.

**Comment by nalimilan** [comment]
If you want to implement that, I encourage you to work on CSV.jl, since `readtable` is going to be deprecated.

**Comment by quinnj** [comment]
This is currently *not* possible with CSV.jl, but it wouldn't take much work to get it to work.

**Comment by quinnj** [comment]
This is possible w/ CSV.jl
