### ISSUE TITLE
Compact display of Nullables and IJulia

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/DataFrames.jl#1082]
The [show method for Nullables ](https://github.com/JuliaLang/julia/blob/b36141f4799d73113b3597ee94d5925929b2ccd5/base/nullable.jl#L30) has two different displays-- a compact one which shows only the value or `#NULL`, and a longer one which also includes the type information as well as the word `Nullable`.  In general, the compact display is used, but one notable exception is with DataFrames in IJulia.  This leads to ungainly situations like the following on DataFrames master:

![image](https://cloud.githubusercontent.com/assets/7132414/19008542/f43d8540-8720-11e6-93d8-5257a8b198fe.png)

Is there any way to specify in DataFrames (or possibly IJulia) that Nullables should be displayed compactly, even when using the nicer HTML tables from IJulia?

**Comment by johnmyleswhite** [comment]
This seems like it's just an oversight and that the HTML printing should be updated. Care to make a PR?

**Comment by nalimilan** [comment]
If that helps, one needs to call `showcompact` or `sprint(showcompact, x)` to get the short output (instead of `show`, `print`, `string` or `repr`).
