### ISSUE TITLE
Add Query.jl section to the manual

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/DataFrames.jl#1083]
@nalimilan suggested in #1078 that we add a whole section to the manual that gives a short demo how one can use [Query.jl]() to manipulate `DataFrame`s.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaStats/DataFrames.jl/pull/1105 and https://github.com/JuliaStats/DataFrames.jl/pull/1078.
