### ISSUE TITLE
Add NullableArray to a DataFrame

### ISSUE THREAD

**Issue by mwsohn** [JuliaStats/DataFrames.jl#1087]
using DataFrames, NullableArrays
a = [1,2,3]
c = DataFrame()

c[:b] = DataArray(a)
This works but

c[:c] = NullableArray(a)
This fails. Is there a way to get around this?

**Comment by ararslan** [comment]
What version of the package are you using? The version of DataFrames that supports `NullableArray`s has not yet been registered, so to get that functionality you'll need to `Pkg.checkout("DataFrames", "master")` for the time being.

**Comment by mwsohn** [comment]
I see. Thank you.

**Comment by ararslan** [comment]
No problem!
