### ISSUE TITLE
Warning when autocompleting "maximu" with tab key

### ISSUE THREAD

**Issue by jhasse** [JuliaStats/DataFrames.jl#1094]
```
julia> using DataFrames
julia> maximu*TAB*
```

Results in:

```
julia> maximuWARNING: both DataArrays and StatsBase export "autocor"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "inverse_rle"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "rle"; uses of it in module DataFrames must be qualified
julia> maximum
```

This is with Julia 0.5.0 on Windows 10.

**Comment by nalimilan** [comment]
Yes, we're aware of this warning and it's already fixed in master. Note that it doesn't indicate a real problem, you just need to fully qualify these functions if you want to use them. The fact that it's shown on autocompletion is a small Julia bug, though, which you should report there.
