### ISSUE TITLE
In master, has the support for DataFrames.DataFrame(::Array{Int64,1}, ::Array{Symbol,1}) been dropped?

### ISSUE THREAD

**Issue by mwsohn** [JuliaStats/DataFrames.jl#1096]
I use a by() function to generate a DataFrame

DataFrame(frequencies, colnms)

which generates the following error message:

LoadError: MethodError: no method matching DataFrames.DataFrame(::Array{Int64,1}, ::Array{Symbol,1})

This syntax used to be supported. Is there any plan to bring it back?

**Comment by nalimilan** [comment]
Could you give a reproducible example of that syntax? Do you have a precise reference of where is was documented or when it worked?

**Comment by mwsohn** [comment]
The following function works with DataFrames + DataArrays.


function xtab_freq(df::DataFrame,column1,column2)

    function frequency(data,factors)

        # convert factors to symbols
        factor_symbols::Vector{Symbol} = map(factor -> Symbol(factor),
factors)

        # Convert frequency to fit the DataFrame constructor parameter type
        frequencies::Vector{Any} = map(frequency->[frequency],map(x ->
isna(x) ? sum(isna(data)) : sum(dropna(data) .== x), factors))

        DataFrame(frequencies, factor_symbols)
    end

    factors = sort(unique(df[column2]))
if length(factors) > 0
    return by(df, column1, x -> frequency(x[column2], factors))
end
end

See the 11th line, DataFrame(frequencies, factor_symbols).

Thanks

Min

**Comment by nalimilan** [comment]
It works here both with 0.8.3 and master, on Julia 0.4 and 0.5. Minimal reproducer: `DataFrame(Any[[1],[2]], [:a, :b])`.

Can you show the exact error you get?

BTW, if you need frequency tables, you can also use https://github.com/nalimilan/FreqTables.jl

**Comment by femtotrader** [comment]
You might try

    DataFrame(hcat([Date(2016,9,1), Date(2016,9,2)], rand(2,1)), [:Date, :Value])
