### ISSUE TITLE
Conversion to html?

### ISSUE THREAD

**Issue by jw3126** [JuliaStats/DataFrames.jl#1098]
I have a dataframe, which is large but not huge (few hundreds of rows) and I need to convert it to html. Is there a recommended way to do this? 
```
show(io, MIME{Symbol("text/html")}(), df)
```
used to work a long time ago (see #501), but now truncates the frame.

**Comment by nalimilan** [comment]
@johnmyleswhite Maybe we should have a mechanism for printing the full data frame?

**Comment by nalimilan** [comment]
I think we should check the `limit` property of the `IOContext` before skipping some rows. @jw3126 Would you make a pull request?

**Comment by jw3126** [comment]
Sure!
