### ISSUE TITLE
method error for modelmat_cols(CategoricalArrays.CategoricalArray{String,1,Int32})

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataFrames.jl#1100]
Have I just overlooked something?  The method error is coming in an explicit call to `ModelMatrix` in the `MixedModels` code.  I am using https://github.com/JuliaStats/DataFrames.jl/commit/e4ab277bee48253c1d24fd921dc11b0598fb2291 which does require `CategoricalArrays` but there is no method for `modelmat_cols` for a `CategoricalArray`.

I am surprised this wasn't caught by tests.

**Comment by dmbates** [comment]
Of course, now that I check there is a methods for it.  I just can't figure out why it isn't being called.

**Comment by dmbates** [comment]
Never mind.  I appear to have more than one version of the `DataFrames` package sitting around, although how that happened I don't know.

**Comment by dmbates** [comment]
I have tried to back out and start from
```
Pkg.add("DataFrames")
Pkg.checkout("DataFrames")
```
(this is on Windows, unfortunately)

and I get
```
WARNING: Cannot perform fast-forward merge
```
If I check with
```
Pkg.status("DataFrames")
```
it looks as if it is on `master` but the files are not those from master.

Why does git hate me?

**Comment by nalimilan** [comment]
Try `git reset --hard origin/master` inside the package directory. Though be careful if you're on a branch, it will destroy everything.

**Comment by dmbates** [comment]
Thanks.  That seems to have worked.
