### ISSUE TITLE
`dropna` function for rows

### ISSUE THREAD

**Issue by abcsds** [JuliaStats/DataFrames.jl#1111]
I'm trying to get the mean value for each row in a certain amount of columns in a DataFrame. The solutions described in the [julia-users group](https://groups.google.com/forum/#!topic/julia-users/q52Sxff5lME) seem quite useful when there are no `NA` values in the DataFrame. [As such](https://groups.google.com/d/msg/julia-users/q52Sxff5lME/QSHIGn9gCAAJ): 
```julia
mean(convert(Array,df[1,1:3]))
```

Unfortunatelly not having `NA`s doesn't happen often. It seems to me that a `dropna` function for rows could be a fit solution if no `rowwise` function will be implemented.

This is my code suggestion:

```julia
mean(convert(Array,dropna(df[1,1:3])))
```

**Comment by nalimilan** [comment]
That function already exists: http://juliastats.github.io/DataFrames.jl/stable/man/getting_started/

**Comment by abcsds** [comment]
Hi, sorry, maybe I didn't explain myself well:
When calling `eachrow` on a dataframe, we get an iterator
```julia
df = DataFrame(A=[2,3,4], B=[5,6,7])
df[:A][2]=NA;
typeof(eachrow(df))
```

     DataFrames.DFRowIterator{DataFrames.DataFrame}

This means that calling an element of such iterator will return a `DataFrameRow`:
```julia
typeof(eachrow(df)[1])
```

     DataFrames.DataFrameRow{DataFrames.DataFrame}

When calling the `dropna` function on a DataFrameRow, we get a `MethodError`:
```julia
dropna(eachrow(df)[1])
```


```julia
LoadError: MethodError: no method matching dropna(::DataFrames.DataFrameRow{DataFrames.DataFrame})
Closest candidates are:
  dropna(!Matched::DataArrays.DataArray{T,1}) at ~/.julia/v0.5/DataArrays/src/dataarray.jl:431
  dropna{T}(!Matched::DataArrays.PooledDataArray{T,R,1}) at ~/.julia/v0.5/DataArrays/src/pooleddataarray.jl:819
  dropna(!Matched::AbstractArray{T,1}) at ~/.julia/v0.5/DataArrays/src/abstractdataarray.jl:118
while loading In[92], in expression starting on line 1
```

As you can see, there is no method to manage NA's within `DataFrameRow`s.
In the [wikibook](https://en.wikibooks.org/wiki/Introducing_Julia/DataFrames#The_NA_problem) they describe a way of handling `NA`s within rows, and it involves iterating through columns, and then, iterating over each element of the row. This is a method that consumes much resources compared with mapping a function to a row (and looks very bad).


Another option that could solve this is if the `isna` function returned an array of boolean values for the elements in a row that are `NA`. Instead it simply returns weather the whole row is a `NA` value:

```julia
for row in eachrow(table)
    println(row[:], " ")
    println(isna(row))
end
```

```
1×2 DataFrames.DataFrame
│ Row │ A │ B │
├─────┼───┼───┤
│ 1   │ 2 │ 5 │ 
false
1×2 DataFrames.DataFrame
│ Row │ A  │ B │
├─────┼────┼───┤
│ 1   │ NA │ 6 │ 
false
1×2 DataFrames.DataFrame
│ Row │ A │ B │
├─────┼───┼───┤
│ 1   │ 4 │ 7 │ 
false
```

So, if there is a function that cleans NA's from DataFrameRows, either it's not documented, or I simply have not been able to find it. Could you please point me towards a solution? 
Thank you!
