### ISSUE TITLE
Order in sort() and by() appears to be different

### ISSUE THREAD

**Issue by mwsohn** [JuliaStats/DataFrames.jl#1113]
sort function puts the NA (or NULL in Master) at last but by() puts it on top.

print(df)
5×1 DataFrames.DataFrame
│ Row │ a  │
├─────┼────┤
│ 1   │ 1  │
│ 2   │ 3  │
│ 3   │ 5  │
│ 4   │ 4  │
│ 5   │ NA │

print(sort(df[:a]))
[1,3,4,5,NA]

print(by(df,:a,x->size(x,1)))
5×2 DataFrames.DataFrame
│ Row │ a  │ x1 │
├─────┼────┼────┤
│ 1   │ NA │ 1  │
│ 2   │ 1  │ 1  │
│ 3   │ 3  │ 1  │
│ 4   │ 4  │ 1  │
│ 5   │ 5  │ 1  │

Shouldn't the order be the same?

**Comment by nalimilan** [comment]
Indeed. This is fixed on master with the port to `Nullable`.
