### ISSUE TITLE
Apply functions to rows with NAs.

### ISSUE THREAD

**Issue by abcsds** [JuliaStats/DataFrames.jl#1114]
I'm currently working with likert scales, which involves applying simple functions like means and stds over rows. This is an incredibly difficult task with Julia's DataFrames, right now, since there is no default way for these functions to handle NA values. I opened issue #1111 when I found this problem, but it goes a bit further, since there is no way for handling rows as any kind of array (julia `Arrays`, `DataArrays`, or such). 
For columns there is the `colwise` function, which applies a function to every column (without handling NAs, but since columns are DataArrays, that can be done by `dropna`). For rows, the only option is to iterate over each row. The function `eachrow` returns an iterator, that, when collected returns another `DataFrame`.
Let me show an example:

``` julia
using DataFrames
df = csv"""
       a,b
       1,2
       ,3
       4,5
       """
typeof(eachrow(df))
```

```
 DataFrames.DFRowIterator{DataFrames.DataFrame}
```

This means that calling an element of such iterator will return a `DataFrame` with a single row:

``` julia
typeof(eachrow(df)[1])
```

```
 DataFrames.DataFrameRow{DataFrames.DataFrame}
```

To which you can again, only apply column-wise functions. None of these can be converted to julia Arrays if they have NA values.

Also, you cannot simply transpose a `DataFrameRow` to turn it into a "column" and then a DataArray. 

If after looking at this you decide it is my problem for not doing enough research on how solve it, please don't just redirect me to the `Getting started` section of the docs, please redirect me to the exact function that (as @nalimilan mentions) already exists (even just to the code). I am here because I have read the documentation (and the [wikibook](https://en.wikibooks.org/wiki/Introducing_Julia/DataFrames), and the [julia-users forum](https://groups.google.com/forum/#!topic/julia-users/q52Sxff5lME), and googled it), and could't find a way of doing what I can easily do with [R](http://stat.ethz.ch/R-manual/R-devel/library/base/html/apply.html). 
I like what Julia is coming to be, and I'm doing my part by teaching psychologists and social scientists to use it as their analysis tool, but If someone that has a tech background like me cannot find a way to use it, it'll be harder for general users.

**Comment by nalimilan** [comment]
Sorry, I missed you reply on the other issue.

It looks like we just need a function to convert a `DataFrameRow` to a `DataArray`/`NullableArray`. Indeed, there's already such a function for conversion to `Array`. In the meantime, iterate manually using row indices instead of using `eachrow`. This works:
```julia
julia> mean(DataArray(df[2,:]), skipna=true)
3.0
```

But if you're working only with numeric columns, an `Array` or a `NamedArray` might be more appropriate (and certainly more efficient).

**Comment by johnmyleswhite** [comment]
This is a good example where a more SQL-style API would be useful after formatting the data in a COO-like format with columns being `row_id, column_id, likert_value`. Then you'd be able to do something like,

```jl
row_means = coo_data |>
    @groupby(row_id) |>
    @summarize(row_mean = mean(likert_value))
```

**Comment by ararslan** [comment]
Something similar to what @johnmyleswhite is describing is currently available in the [DataFramesMeta.jl](https://github.com/JuliaStats/DataFramesMeta.jl) package.

**Comment by abcsds** [comment]
@nalimilan Thank you for your answer:
When running your code with this example I get the following error:
```
LoadError: function mean does not accept keyword arguments
while loading In[2], in expression starting on line 1

 in kwfunc(::Any) at ./boot.jl:236
 in kwfunc(::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```
The mean function that handles NAs is in the DataArray's package, but importing the DataArrays package generates a conflict in the `head` and `tail` function.

If I do import the DataArrays package:
```
using DataArrays
mean(DataArray(df), skipna=true)
```

I get  the following error message:

```
LoadError: MethodError: Cannot `convert` an object of type DataFrames.DataFrame to an object of type DataArrays.DataArray{T,N}
This may have arisen from a call to the constructor DataArrays.DataArray{T,N}(...),
since type constructors fall back to convert methods.
while loading In[4], in expression starting on line 2

 in DataArrays.DataArray{T,N}(::DataFrames.DataFrame) at ./sysimg.jl:53
```

I'll try the meta package and report back. Thank you guys!

**Comment by nalimilan** [comment]
The  `head` and `tail` conflict is just a harmless warning as long as you don't use these functions. Regarding the error, you tried a different expression than the one I posted.

**Comment by abcsds** [comment]
@nalimilan I copied and pasted your solution. Here are some images showing the code on a Jupyter notebook and on a Julia prompt: http://imgur.com/a/EjgN6

If your solution works on your machine it might be an environment related error. 

Yep, I just removed the DataFrames and DataArrays packages and re-installed. It's working now. Could it have been a compilation error?

**Comment by quinnj** [comment]
Seems like there's nothing else actionable here? Note also that `collect(df_row)` also works for turning a DF row into a Julia array (it includes the symbol as well, but still). There's also https://github.com/JuliaStats/DataFrames.jl/issues/956 which is tracking general column & row-wise processing functions.
