### ISSUE TITLE
Stable docs are currently unreadable

### ISSUE THREAD

**Issue by kmsquire** [JuliaStats/DataFrames.jl#1116]
Looks like something didn't get parsed correctly.

http://juliastats.github.io/DataFrames.jl/stable/

**Comment by nalimilan** [comment]
Indeed I had noticed that too. Looks like the Documenter syntax changed and we only updated master. See https://github.com/JuliaStats/DataFrames.jl/pull/1117.

**Comment by nalimilan** [comment]
Fixed now. I've temporarily created a `fixdocs` label to force the online docs to be updated.
