### ISSUE TITLE
modelmat_cols can't use NullableArrays

### ISSUE THREAD

**Issue by jiahao** [JuliaStats/DataFrames.jl#1123]
On current release on Julia 0.5, the following code for a simple least squares model on [NYC taxicab data](www.nyc.gov/html/tlc/html/about/trip_record_data.shtml) throws an error which appears to be a missing method error in `DataFrames.modelmat_cols`:

```jl
using CSV, DataFrames, GLM
filename = "green_tripdata_2015-09.csv"
isfile(filename) || download("https://s3.amazonaws.com/nyc-tlc/trip+data/green_tripdata_2015-09.csv", filename)
df = CSV.read(filename)
glm(Total_amount ~ Trip_distance + Passenger_count, df, Normal(), IdentityLink())
```

Error:

```
ERROR: MethodError: no method matching modelmat_cols(::Type{Array{Float64,2}}, ::NullableArrays.NullableArray{Float64,1})
Closest candidates are:
  modelmat_cols{T<:AbstractArray{T<:AbstractFloat,2}}(::Type{T<:AbstractArray{T<:AbstractFloat,2}}, ::Symbol, ::DataFrames.ModelFrame; non_redundant) at /Users/jiahao/.julia/v0.5/DataFrames/src/statsmodels/formula.jl:347
  modelmat_cols{T<:AbstractArray{T<:AbstractFloat,2}}(::Type{T<:AbstractArray{T<:AbstractFloat,2}}, ::DataArrays.DataArray{T,1}) at /Users/jiahao/.julia/v0.5/DataFrames/src/statsmodels/formula.jl:357
  modelmat_cols{T<:AbstractArray{T<:AbstractFloat,2}}(::Type{T<:AbstractArray{T<:AbstractFloat,2}}, ::Array{T,1}) at /Users/jiahao/.julia/v0.5/DataFrames/src/statsmodels/formula.jl:358
  ...
```

I'm somewhat aware that there is some churn going on in the internals of `DataFrame`s right now, but in the meantime it would be nice if this example worked.

**Comment by ararslan** [comment]
The current DataFrames master uses `NullableArray`s for columns instead of `DataArray`s, and it looks like there's a method showing up for `DataArray` that shouldn't be there on master. Can you `Pkg.checkout("DataFrames", "master")` and try again?

**Comment by jiahao** [comment]
Ah, I see that it's fixed on master. Any reason not to tag a release at this moment?

**Comment by andreasnoack** [comment]
I think the view is that `NullableArrays` still need functionality before we can tag a release of `DataFrames` so it might take a while before that will happen. The problem seems to be that `CSV` returns a `DataFrame` with `NullableArray` columns.

**Comment by ararslan** [comment]
CSV might want to hold off on that until DataFrames produces `NullableArray`s. cc @quinnj

**Comment by quinnj** [comment]
CSV has been returning NullableArray-DataFrames since the beginning, so that's not going to change. If anything, it's been helpful to push the new NullableArray-DataFrames forward and help "beta" test them. This will all get sorted out soon enough.

**Comment by ararslan** [comment]
> CSV has been returning NullableArray-DataFrames since the beginning

Oh, I had no idea!

> If anything, it's been helpful to push the new NullableArray-DataFrames forward

I can imagine. 👍 

And it's good to know that Jiahao's example works as expected when using DataFrames master!

**Comment by nalimilan** [comment]
I guess it wouldn't be too much work to add `NullableArray` support to `modelmat_col`  in the 0.8.x series without breaking backward compatibility, if somebody is really interested in it.

**Comment by jiahao** [comment]
The very simple hack

```
DataFrames.modelmat_cols(T::Type, b::NullableArray) = DataFrames.modelmat_cols(T, DataArray(Array(b)))
```

appears to work when there are no missing data (which is the case for the NYC taxi data set).

**Comment by nalimilan** [comment]
Closing since nobody seems to be willing to do this work before 0.9.0.

**Comment by ararslan** [comment]
This is still an issue and we no longer use NullableArrays here, so we'll need to find a way to fix this with DataArrays.

**Comment by ararslan** [comment]
My bad. This is because of the types CSV emits, so the solution here is to use `readtable` for now.
