### ISSUE TITLE
using DataFrames in jupyter 

### ISSUE THREAD

**Issue by jhli973** [JuliaStats/DataFrames.jl#1132]
LoadError: UndefVarError: dataFrame not defined
while loading In[12], in expression starting on line 3

`using DataFrames

df = dataFrame(A = [1,2], B = [e, pi], C = ["xx", "xy"])
showln(df)`

**Comment by nalimilan** [comment]
That's `DataFrame`.

**Comment by jhli973** [comment]
Thanks
