### ISSUE TITLE
Plans to implement skiprows in readtable?

### ISSUE THREAD

**Issue by equinaut** [JuliaStats/DataFrames.jl#1133]
I saw mention of adding support for skiprows in #292 but that was back in 2013. I'm using version 0.8.5 and am getting this message when I try to use it:

`ERROR: ArgumentError: Argument 'skiprows' is not yet supported.`

Speaking for myself I'd find this feature to be very useful. Does anybody have plans for finishing it?

**Comment by ararslan** [comment]
Actually `readtable` will be deprecated soon in favor of [CSV.jl](https://github.com/quinnj/CSV.jl), so no further development of it will take place here.
