### ISSUE TITLE
problem with WeakRefString in DataFrame

### ISSUE THREAD

**Issue by mkaut** [JuliaStats/DataFrames.jl#1134]
We are having a problem with corrupt string data in a data frame.
When using `describe`, we see that the string column has type `WeakRefStrings.WeakRefString{UInt16}`, not String.

We create the data frame in a function that reads from an Access database, `df = makedataframe()`.
The data frame `df` works at first, but after a while the column represented by WeakRefString gets filled by garbage data.

Now, the documentation of WeakRefString says explicitely that 

> no original reference is kept to the parent string/memory, so WeakRefString becomes unsafe once the parent object goes out of scope (i.e. loses a reference to it)

Does it mean that one can only use data frames with strings in the same scope when they were created and, therefore, creating them in separate functions is not safe?
I hope this is not the case and I am just missing something obvious...

**Comment by nalimilan** [comment]
`WeakRefString` isn't defined in DataFrames. Please file an issue against the package that you use to import your data. Thanks!

**Comment by quinnj** [comment]
Happy to help however I can (being author of CSV.jl, Feather.jl, and ODBC.jl, which are the ingestion packages that produce weakrefstrings). WeakRefStrings should be safe as long as you keep them in a NullableArray (which keeps the necessary references around to keep the data valid). If you're extracting them from a NullableArray, however, that's when you'd hit the warning from the WeakRefStrings.jl package. If you can detail your workflow/process a little more, I can help determine if it's just a workflow problem, or if there's an actual bug somewhere.

**Comment by mkaut** [comment]
@quinnj  Thanks. It looks to me that our database-reading function does exactly what you say we should not do, as we pass all data frames through the following function (after reading them via ODBC):

    function denullify!(df)
        for n in names(df)
            df[n] = dropnull(df[n])
        end
    end

Is this what causes the problem?

After denullifying, the data frame is returned from the database-reading function and then it gets passed around the rest of the code - where we have experienced the corruption of WeakRefStrings columns.

At the moment, we side-step the issue by explicitly converting the WeakRefStrings columns to String after calling `denullify`, but I guess there must a more standard way...

Note: for some columns, we first (before `denullify`) replace nulls by default values using

    function replaceNULL!(df,col,val)
        df[DataArray([convert(Bool,i) for i in dropnull(map(isnull,df[col]))]),col] = val;
    end
I have a feeling that there is an easier/better way of doing this as well...
