### ISSUE TITLE
`writetable` should take an output stream as an argument

### ISSUE THREAD

**Issue by ntdef** [JuliaStats/DataFrames.jl#1140]
Looks like the `writetable` function only takes a string as an argument for the destination. It would be nice if it could write to any stream, especially for cases where you want to write straight to stdout like

    writetable(STDOUT, data) 

I would imagine it's a pretty simple addition. I can take a hack at it.

**Comment by ntdef** [comment]
Ah, I see there's a `printtable` function. However, there's no docstring for it and it's not listed as an option in the documentation.

**Comment by ararslan** [comment]
The I/O functionality in this package will actually be removed in the next release of DataFrames. Instead we encourage people to use CSV.jl.

**Comment by ntdef** [comment]
Is there an issue where that's being discussed? It doesn't seem very intuitive for users that they would need a separate package for IO, just as a first impression. The R and Python data table libraries don't separate the functionality.

**Comment by ararslan** [comment]
(Also note that this issue is a duplicate of #1011)

> Is there an issue where that's being discussed?

Hm, I'm actually not sure where that was decided. @nalimilan and @quinnj, can either of you shed some light on that?

**Comment by nalimilan** [comment]
I think discussions are scattered since it's an old issue. Basically we want to use DataStreams to support reading from and writing to any input format on the fly. CSV.jl already does that and is more efficient than `readtable`. We could still reexport the required functions from DataFrames, but installing a small package with an explicit name doesn't sound like a big deal.

**Comment by quinnj** [comment]
I've actually always imagined having DataFrames require CSV.jl, but I guess that's not strictly necessary. It might be good though, since csv is probably the primary type of IO for a dataframe.

**Comment by ntdef** [comment]
I would agree with that sentiment. It just lowers friction for people who want to do data manipulation quickly and I think it would help adoption.
