### ISSUE TITLE
UnicodeError: invalid character index

### ISSUE THREAD

**Issue by gdowdy3** [JuliaStats/DataFrames.jl#1149]
I've encountered a bug that I don't understand.

I have a .txt file [BugTest.txt](https://github.com/JuliaStats/DataFrames.jl/files/721643/BugTest.txt) which contains a very simple data table with one column and two rows:

>Data
Inventory Subcommittee (Operations Committee)
Inventory Subcommittee (Operations Committee)

I read in this data with the commands

    using DataFrames, DataArrays
    table = readtable("BugTest.txt");

Then, when I enter

    table[1,1] == table[2,1]

the answer is `false`.

If I enter

    table[2,1]

the result is what I'd expect:

    "Inventory Subcommittee (Operations Committee)"

On the other hand, if I enter

    table[1,1]

the result is:

```
 UnicodeError: invalid character index

 in slow_utf8_next(::Array{UInt8,1}, ::UInt8, ::Int64) at .\strings\string.jl:67
 in next at .\strings\string.jl:92 [inlined]
 in escape_string(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::String, ::String) at .\strings\io.jl:140
 in print_quoted at .\strings\io.jl:158 [inlined]
 in show at .\strings\io.jl:72 [inlined]
 in show at .\replutil.jl:4 [inlined]
 in limitstringmime(::MIME{Symbol("text/plain")}, ::String) at C:\Users\User1\.julia\v0.5\IJulia\src\inline.jl:25
 in display_dict(::String) at C:\Users\User1\.julia\v0.5\IJulia\src\execute_request.jl:28
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\User1\.julia\v0.5\IJulia\src\execute_request.jl:188
 in eventloop(::ZMQ.Socket) at C:\Users\User1\.julia\v0.5\IJulia\src\eventloop.jl:8
 in (::IJulia.##13#19)() at .\task.jl:360

```

A few other curious things I've noticed... If I enter

    println(table[2,1])

the result is what I would expect

    Inventory Subcommittee (Operations Committee)

However, if I enter

    println(table[1,1])

the result is

    base64 binary data: SW52ZW50b3J5IFN1YmNvbW1pdHRlZaAoT3BlcmF0aW9ucyBDb21taXR0ZWUpCg==

If I enter

    contains(table[1,1],"Inventory Subcommittee")

or

    contains(table[1,1],"(Operations Committee)")

the result is `true`.  So Julia can interpret the contents of `table[1,1]` to some extent.  But if I enter

    contains(table[1,1],"Inventory Subcommittee (Operations Committee)")

the result is `false`.

Can anyone explain what's going on here?

In case it matters, I am entering all the above commands in the Jupyter interface on a computer running Windows.

**Comment by andreasnoack** [comment]
The first line has a unicode symbol which is causing the problems. It might be encoded wrongly but if I open it in TextEdit (but not SublimeText) on my Mac it shows up like
```
Data
Inventory Subcommittee†(Operations Committee)
Inventory Subcommittee (Operations Committee)
```
You can try deleting the character between `e` and `(` and make a real space.

**Comment by nalimilan** [comment]
And the error when trying to print that string is because the file is encoded in ISO-8859-15, while `readtable` expects UTF-8. Use the StringEncodings package to read it.

**Comment by gdowdy3** [comment]
Thanks for the help, folks.

This may be a longshot, but do either of you know a way that I could read in the .txt/.csv without knowing what encoding it uses and automatically convert it to UTF-8?

**Comment by nalimilan** [comment]
For a given language, only a small set of encodings are common, so you can try all of them manually. Else, some software like ICU allows trying to detect it, though this doesn't always work. I had made a PR against ICU.jl to add these functions, but it's not been merged: https://github.com/nolta/ICU.jl/pull/9 I think you can find external software to do that.

**Comment by nalimilan** [comment]
Oh, and no, you can't read text without knowing its encoding. Nobody would be using encodings if they weren't needed. But with ISO-8859 encodings, you should be able to discard non-ASCII characters and still get something which can be parsed as valid CSV; but of course some data (like accentuated characters) will be lost.
