### ISSUE TITLE
Storing Arrays in a DataFrame column

### ISSUE THREAD

**Issue by krauti** [JuliaStats/DataFrames.jl#1157]
Hi all,
awesome work on the DataFrames, I really love it and use it constantly for my phd work. I often have big datasets, where each row corresponds to a point in my measurements.
I am currently dealing with a vectors in different coordinate systems. Its quite a long way from the raw data until the reciprocal space vector is found, and that is why I want to store it in a SVector{3,Float64} type from the StaticArrays package, along with the transformation matrix SMatrix{3,3}.
As far as I understand, this is currently not possible. What is your plan for this kind of situation? Create a column for each index in my scripts, and all the overhead related to sorting stuff into those columns?
Thanks, Max

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/DataFrames.jl/issues/1119. You can already store any vector as a column using the constructor `DataFrame([col1, col2], [:col1, :col2])`.

**Comment by krauti** [comment]
Thanks, got it working.
