### ISSUE TITLE
Deprecation warnings in 0.5

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/DataFrames.jl#1158]
I searched the issues page and I was very surprised I did not see any issue for these:
```
WARNING: the no-op `transpose` fallback is deprecated, and no more specific `transpose` method for Symbol exists. Consider `permutedims(x, [2, 1])` or writing a specific `transpose(x::Symbol)` method if appropriate.

WARNING: both DataArrays and StatsBase export "autocor"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "inverse_rle"; uses of it in module DataFrames must be qualified
WARNING: both DataArrays and StatsBase export "rle"; uses of it in module DataFrames must be qualified
```
There is no minimal example, these come up with the simplest usage of `DataFrames`, like eg. `df = DataFrame(); df[:vals] =0.5`

**Comment by andreasnoack** [comment]
The last three warnings are issues in `DataArrays`. I've just pushed a fix for those. The first one is already fixed on the master branch. Unfortunately, we can't release a new version right now because the master branch is not ready for a release yet.

**Comment by Datseris** [comment]
Okay, thank you for the notice. 
You would advise against me using `Pkg.checkout("DataFrames")` ?

**Comment by nalimilan** [comment]
Yes. See https://discourse.julialang.org/t/announcement-dataframes-0-9-0-planned-for-february/266 and https://discourse.julialang.org/t/teaching-data-analysis-with-julia-what-to-do-about-dataframes-and-all-that/422.

**Comment by Datseris** [comment]
Oh wow, seems like huge changes! Okay I will be patient and hope to find about all the changes in some documentation!
