### ISSUE TITLE
Error following Documentation: Reshaping and Pivoting Data -> d = stack(iris, [1:4])

### ISSUE THREAD

**Issue by sylvaticus** [JuliaStats/DataFrames.jl#1162]
I am trying to follow the documentation in http://dataframesjl.readthedocs.io/en/stable/reshaping_and_pivoting.html (identical to "latest" on this specific point).
The first example is:
```
using DataFrames, RDatasets
iris = dataset("datasets", "iris")
iris[:id] = 1:size(iris, 1)  # this makes it easier to unstack
d = stack(iris, [1:4])
```
That however lead in julia 0.5 to the following error: 
```
LoadError: MethodError: no method matching getindex(::DataFrames.Index, ::Array{UnitRange{Int64},1})
while loading In[8], in expression starting on line 4

 in stack(::DataFrames.DataFrame, ::Array{UnitRange{Int64},1}) at /home/lobianco/.julia/v0.5/DataFrames/src/abstractdataframe/reshape.jl:93
```
If I instead stack using column names it works.

By the way, also in the documentation, in "stable" I have at bottom of the page a nice widget to change version and/or format (PDF), while that widget is not present in "latest", so it was hard to find "stable" (I had to guess the url).

**Comment by nalimilan** [comment]
Thanks for the report. Indeed, this example has not been updated to reflect the new Julia behavior. The last line should simply be `d = stack(iris, 1:4)`. Ideally we would run examples during the tests to catch this kind of mistake automatically.

I have a fix at https://github.com/JuliaStats/DataFrames.jl/pull/1163.

**Comment by nalimilan** [comment]
> By the way, also in the documentation, in "stable" I have at bottom of the page a nice widget to change version and/or format (PDF), while that widget is not present in "latest", so it was hard to find "stable" (I had to guess the url).

The "stable" docs are still using the old version of the manual AFAICT, this should be fixed when we will tag a new release.
