### ISSUE TITLE
Should dataframes implicitly convert FloatRange types?

### ISSUE THREAD

**Issue by r-handsfield** [JuliaStats/DataFrames.jl#1168]
Only integers are allowed as DataFrame index arguments, however many Base numeric operations that someone might use to create an index return `FloatRange` types.

```julia
julia> df = DataFrame(A=1:20);
julia> train = ( 1:ceil( 0.8 * nrow(df) ) )::FloatRange{Float64}

julia> df[ train, : ]
ERROR: MethodError: no method matching sub2ind(::Tuple{Int64}, ::Float64)
Closest candidates are:
  sub2ind(::AbstractArray{T,N}, ::Any...) at abstractarray.jl:1419
  sub2ind(::Tuple{Vararg{Integer,N}}) at abstractarray.jl:1429
  sub2ind(::Tuple{Vararg{Integer,N}}, ::Integer...) at abstractarray.jl:1433
  ...
 in macro expansion at /home/rh/.julia/v0.5/DataArrays/src/indexing.jl:148 [inlined]
 in macro expansion at ./cartesian.jl:64 [inlined]
 in macro expansion at /home/rh/.julia/v0.5/DataArrays/src/indexing.jl:147 [inlined]
 in _getindex! at /home/rh/.julia/v0.5/DataArrays/src/indexing.jl:139 [inlined]
 in _getindex(::DataArrays.DataArray{Int64,1}, ::Tuple{FloatRange{Float64}}) at /home/rh/.julia/v0.5/DataArrays/src/indexing.jl:162
 in getindex(::DataArrays.DataArray{Int64,1}, ::FloatRange{Float64}) at /home/rh/.julia/v0.5/DataArrays/src/indexing.jl:173
 in copy!(::Array{Any,1}, ::Base.Generator{Array{Any,1},DataFrames.##20#21{FloatRange{Float64}}}) at ./abstractarray.jl:477
 in getindex(::DataFrames.DataFrame, ::FloatRange{Float64}, ::Colon) at /home/rh/.julia/v0.5/DataFrames/src/dataframe/dataframe.jl:277
```
The fix is to convert from `FloatRange{Float64}` to `UnitRange{Int64}`, but I think this would be difficult to debug and fix for most Julia users because
1) `FloatRange` and `UnitRange` are (comparatively) arcane Julian types, not broadly understood like Base`Float` or `Int`
2) You can't easily convert from `FloatRange` to `UnitRange`; you need to go upstream from the error and change the generating computations, or dump the `FloatRange` and compute a `UnitRange` from its parameters.

R handles this problem by having a single `numeric` type, but I don't know how it works under the hood. Dedicated subsetting functions might work as well, but I don't think that's the right solution.

In general, I'd like Julia to be accessible from the low-level API math (as much as practical). As long as a sequence conforms to `UnitRange` topology, it should be a reasonable index. An implicit float index conversion might look something like
```julia
# ref DataFrames.jl/src/dataframe/dataframe.jl::275
function Base.getindex{R<:Real}(df::DataFrame, row_inds::FloatRange, col_inds::Colon)

    if ( mod([row_inds.start, row_inds.step, row_inds.len], 1) == [0; 0; 0] )
      row_inds = UnitRange( Int(row_inds=s.start), Int(row_inds.len) )::UnitRange{Int64}
    else
      error("row_inds does not conform to UnitRange topology. One of the start, 
            step, or length values is probably a fraction.")
    end
    
    new_columns = Any[dv[row_inds] for dv in df.columns]
    return DataFrame(new_columns, copy(index(df)))
end

```

---

From the interface documentation in `abstractdataframe.jl`, table columns are explicitly integers:
> Table columns are accessed (`getindex`) by a single index that can be a symbol identifier, an integer, or a vector of each.

Table rows, however, don't seem to be typed as strictly, unless Matrix indexing requires integers.
> Rows and columns can be indexed like a `Matrix` with the added feature of indexing columns by name.

Considering their probable ubiquity, Is it reasonable to accommodate `FloatRange` types, or provide some workaround for a user who passes their own index?

**Comment by ararslan** [comment]
Note that in the error stack trace, you're getting a `MethodError` from Base functions, which signals that this isn't an operation supported in Base. At one point float indexing was allowed for Base arrays but that has since been removed. I feel pretty strongly that we should not go against the precedent set in Base to disallow float indexing.

If you have a computation which gives you a vector of floats that you need to use for indexing, cast them to integers first using `Int.(x)` or similar. In the case of `ceil`, just use `ceil(Int, 0.8 * nrow(df))`.

**Comment by andreasnoack** [comment]
I don't think we want to move in that direction. We have had several discussions of that in base and decided against it. There can be subtle issue with floating point indexing and I don't think we want to go solo relative to base. The view has generally been that it is better to ask people to use integer arithmetic for index calculations.
