### ISSUE TITLE
Julia 0.6 Formula broken?

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/DataFrames.jl#1176]
Both DataFrames and StatsBase export `Formula` as the process of re-structuring [1018](https://github.com/JuliaStats/DataFrames.jl/issues/1018) is occurring. However, both give an error when creating an instance of `Formula`. This hampers various functions in the `GLM` package and those that depend on it such as `MixedModels` (i.e., all packages that rely on `Formula`). For example,
```
using DataFrames
fm = Formula(y ~ x)
UndefVarError: y not defined
```

**Comment by andreasnoack** [comment]
The `~` is no longer a macro so you'd have to do `@formula y~x` instead of just `y~x`.

**Comment by Nosferican** [comment]
I remember the discussion, but wasn't aware that the change was implemented. Should I go ahead and update the documentation for it, then?

**Comment by ararslan** [comment]
The documentation already reflects the updated formula syntax: https://juliastats.github.io/DataFrames.jl/stable/man/formulas/#The-Formula,-ModelFrame-and-ModelMatrix-Types-1

**Comment by Nosferican** [comment]
I meant the documentation in `GLM`, `MixedModels`, and other packages that rely on the struct. Since it is implemented and documented in `DataFrames` I will go and update the documentations on the affected packages. Thanks.

**Comment by ararslan** [comment]
Thanks for the willingness to help. I actually have a branch to make the change for GLM, so I'll take care of that one. But PRs elsewhere are of course welcome.

**Comment by Nosferican** [comment]
Will do.
