### ISSUE TITLE
ArgumentError: Data and missingness arrays must be the same size

### ISSUE THREAD

**Issue by ptoche** [JuliaStats/DataFrames.jl#1192]
This is more likely caused by some basic misunderstanding on my part. What could be causing this ``ArgumentError``?

I have a function that returns a ``DataFrame``. I get the error if I execute the function twice. I suspect that the second run attempts to append data created during the first run. I do not understand why: I assume that what's created inside the function is discarded afterwards. When I execute the function, I do not assign it to a name, so is the problem that Julia is trying to append data to the invisible name it creates after the first run?

If you feel it's more appropriate to ask this at stackoverflow, I will. Thanks! 

        workspace()
        type Params
            π::Float64
            α::Float64
        end

        function Params(;
            π::Float64 = 1.0,
            α::Float64 = 2.0)
            Params(π, α)
        end 

        using DataFrames
        function show_constants(mp::Params)
            π = mp.π; α = mp.α;
            d = DataFrame(
                Name = @data(["π"]),
                Description = @data(["pi"]),
                Value = @data([π])
            )
            push!(d, @data(["α", "alpha", α]))
            return(d)
        end

        mp = Params()
        show_constants(mp)
        show_constants(mp) 
        ## ArgumentError: Data and missingness arrays must be the same size

**Comment by ararslan** [comment]
This looks like an actual problem rather than a usage problem. Smaller reproducer:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-rc2.0 (2017-05-18 02:31 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using DataFrames

julia> function test()
           d = DataFrame(a=@data [1])
           push!(d, [2])
           d
       end
test (generic function with 1 method)

julia> test()
2×1 DataFrames.DataFrame
│ Row │ a │
├─────┼───┤
│ 1   │ 1 │
│ 2   │ 2 │

julia> test()
ERROR: ArgumentError: Data and missingness arrays must be the same size
Stacktrace:
 [1] DataArrays.DataArray{Int64,1}(::Array{Int64,1}, ::BitArray{1}) at /Users/alex/.julia/v0.6/DataArrays/src/dataarray.jl:40
 [2] test() at ./REPL[1]:2
```
Does happen if you don't set `@data` on the column when you define it, so as a temporary workaround while we figure this out, I recommend omitting `@data` unless you need to insert `NA` literals. Columns should be promoted to `DataArray`s anyway on construction of the `DataFrame`, so it shouldn't matter.

**Comment by ptoche** [comment]
Thanks Alex! I'm using ``@data`` only because it was used in the template or piece of code I must have copy-pasted at the time. I assumed it was a normal way to create a DataFrame (Did I read the user manual? not the whole thing obviously... awkward). I have no problem omitting it. I don't even know why I had it there in the first place. Thanks!

**Comment by ararslan** [comment]
> In that case, why is the `DataFrame` constructed without the `@data` macro?

For convenience. It would be redundant to make people specify `@data` over and over again in the constructor when we're just going to promote all columns to `DataArray` anyway.

> What are the pros and cons of using `@data`?

It should never be necessary to use when constructing `DataFrame`s, only when directly constructing a `DataArray`. So that information should live in the DataArrays repo rather than here.

**Comment by ptoche** [comment]
Thanks Alex. For me, it's the ``DataArray`` readme.md that helped me clarify the purpose of the ``@data`` macro, while the ``DataFrames`` introduced it without stating its purpose. From reading the Getting Started section, I was under the impression that ``@data`` was either required or good practice. From reading the ``DataArray`` readme, my current understanding is that the ``@data`` macro exists to deal with ``NA``s efficiently. So now you're saying that the ``@data`` macro should not be used in a ``DataFrame``, I'm confused... what if there are ``NA``s in that DataFrame?

**Comment by ararslan** [comment]
Sorry, I wasn't clear. `DataFrame`s convert the specified columns to `DataArray`s upon construction, so you don't need to tell it that what you're giving it is a `DataArray` unless you need to explicitly construct a `DataArray` when constructing the `DataFrame`.

This may be better with an example:
```julia
julia> x = [1,2,3] # Not a DataArray
3-element Array{Int64,1}:
 1
 2
 3

julia> d = DataFrame(X=x)
3×1 DataFrames.DataFrame
│ Row │ X │
├─────┼───┤
│ 1   │ 1 │
│ 2   │ 2 │
│ 3   │ 3 │

julia> typeof(d[:X]) # X is a DataArray even though we didn't tell it to be one
DataArrays.DataArray{Int64,1}
```
But there are cases when you do need to explicitly construct a `DataArray`, like when there are missing values:
```julia
julia> d = DataFrame(Y=@data [1,NA,3])
3×1 DataFrames.DataFrame
│ Row │ Y  │
├─────┼────┤
│ 1   │ 1  │
│ 2   │ NA │
│ 3   │ 3  │
```
But that's only when you need to construct a literal `DataArray`.

Does this make more sense?

**Comment by ptoche** [comment]
Thanks Alex. I think I've got it now. The ``@data`` construct is there to help handle ``NA``s, whether it be inside a ``DataArray`` or inside a ``DataFrame``. If there are no ``NA`` values, then the ``@data`` macro is unnecessary. :-)

**Comment by ararslan** [comment]
Precisely. More specifically, if you just say `[1, NA, 3]`, you get `Vector{Any}`. But `@data [1, NA, 3]` gives you the expected `DataArray`.

**Comment by ptoche** [comment]
Great! Thanks Alex.

**Comment by quinnj** [comment]
DataFrames no longer promote columns to DataArrays by default, so I don't think there's any issue here anymore.
