### ISSUE TITLE
ModelFrame Error

### ISSUE THREAD

**Issue by alexhallam** [JuliaStats/DataFrames.jl#1193]
I was following along with the [docs](http://dataframesjl.readthedocs.io/en/latest/formulas.html) and got the following error 

```julia
julia> df = DataFrame(X = randn(10), Y = randn(10), Z = randn(10))
julia> mf = ModelFrame(Z ~ X + Y, df)
ERROR: MethodError: no method matching ~(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  ~(::AbstractArray) at deprecated.jl:56
```
here is my `versioninfo()`

```julia
julia> versioninfo()
Julia Version 0.6.0-rc3.0
Commit ad290e9 (2017-06-07 11:53 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

```

**Comment by ararslan** [comment]
You're actually using the old docs. Where did you find a link to those? The new documentation can be found on the README. Here's the relevant section of the current docs: https://dataframesjl.readthedocs.io/en/latest/formulas.html

In this case, the issue is that you need to wrap your formula in `@formula`, i.e.
```julia
mf = ModelFrame(@formula(Z ~ X + Y), df)
```

**Comment by ararslan** [comment]
(sorry initially reposted your same link, updated with the correct link)

**Comment by nalimilan** [comment]
I wonder there would be a way to remove that old page. It's going to mislead lots of users. Any idea how to find out who controls the account? Maybe @johnmyleswhite?
