### ISSUE TITLE
Should be able to rename column without change

### ISSUE THREAD

**Issue by oxinabox** [JuliaStats/DataFrames.jl#1195]
Consider the MWE:

``` julia
df=DataFrame(model=["good model", "bad Model"], error_rate=[0.1, 0.9])
rename(df) do nn
    Symbol(replace(string(nn), "_", ""))
end

Tried renaming model to model, when model already exists in the Index.

 in rename!(::DataFrames.Index, ::Array{Tuple{Symbol,Symbol},1}) at /home/ubuntu/.julia/v0.5/DataFrames/src/other/index.jl:40
 in rename!(::DataFrames.Index, ::##22#23) at /home/ubuntu/.julia/v0.5/DataFrames/src/other/index.jl:50
 in rename! at /home/ubuntu/.julia/v0.5/DataFrames/src/abstractdataframe/abstractdataframe.jl:134 [inlined]
 in rename at /home/ubuntu/.julia/v0.5/DataFrames/src/abstractdataframe/abstractdataframe.jl:139 [inlined]
 in rename(::Function, ::DataFrames.DataFrame) at /home/ubuntu/.julia/v0.5/DataFrames/src/abstractdataframe/abstractdataframe.jl:140
```

I was attempting to remove all underscores from the column names, because they cause problems when working with LaTeX.

It makes sense that I should be allowed to not change the name at all, particularly for the function form.

My quick hack as a work around:
```
old_names = names(df)
new_names = Symbol.(replace.(string.(old_names), ["_"], [""]))
change_inds = old_names .!= new_names
rename!.([df], old_names[change_inds], new_names[change_inds]) |> first
```

**Comment by nalimilan** [comment]
Makes sense. Would you make a pull request to fix this?

**Comment by oxinabox** [comment]
Yeah sure,
should be a trivial change.
Just add a line [here](https://github.com/JuliaStats/DataFrames.jl/blob/19821b9060a691646114c064e1bc0b8e290c8f66/src/other/index.jl#L39) to check if `from==to`, 

and a test cast to prove it worked.

Looks like the same thing is need for DataTables.jl too:
https://github.com/JuliaData/DataTables.jl/blob/master/src/other/index.jl#L35
