### ISSUE TITLE
Julia master issue with unique! in testing

### ISSUE THREAD

**Issue by colbec** [JuliaStats/DataFrames.jl#1196]
In:

```
Julia Version 0.7.0-DEV.667
Commit 2de5dab84f (2017-06-21 05:08 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
```

when testing DataFrames against Julia master 0.7 there is an issue with the `unique!` function in `test/duplicates.jl`. Julia complains that `unique! `is exposed by both Base and DataFrames and it does not seem to like that. I tried prefixing the functions mentioned in duplicates.jl but that does not seem to resolve things. Released Julia 0.6 tests without problem.

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/DataTables.jl/pull/75. But there might be other issues on master.
