### ISSUE TITLE
Automatically build an index of the DataFrames website

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#121]
Right now, the website has a simple index stored in the index.md file that Jekyll turns into index.html. This index was created by hand.

Similarly the PDF manual has an index that was created by hand and is an explicit section `00` inside of  the `sections` area of the `gh-pages` branch.

In the future, we should find a way to automatically build both of these indices while compiling the website and PDF manual.

**Comment by garborg** [comment]
No longer relevant after the switch to readthedocs.
