### ISSUE TITLE
error in examples for writetable + can't omit quotemark

### ISSUE THREAD

**Issue by rapus95** [JuliaStats/DataFrames.jl#1211]
acording to the examples that should work: `writetable("output.dat", df, quotemark = '', separator = ',')`

though trying it told me that `''` (2 single quotes) is not a valid char. seems legit so far. But how can I use nothing as quotemark?

**Comment by davidanthoff** [comment]
You can use [CSVFiles.jl](https://github.com/davidanthoff/CSVFiles.jl#save-a-csv-file). You can pass a ``nothing`` value for the ``quotechar`` argument to omit quotemarks.

**Comment by nalimilan** [comment]
Thanks for the report. That's a duplicate of https://github.com/JuliaStats/DataFrames.jl/issues/1080.
