### ISSUE TITLE
Write but not read element arrays

### ISSUE THREAD

**Issue by rand5** [JuliaStats/DataFrames.jl#1213]
I can create a dataframe where the elements are arrays, but when I write and read them back in, they become strings.
```
d = DataFrame([Array{Float64,1}], [:Test],1)
d[1,:Test] = rand(5)
writetable("test.csv",d)
d1 = readtable("test.csv")
typeof(d[1,:Test])==typeof(d1[1,:Test])

false
```

**Comment by nalimilan** [comment]
`readtable` and `writetable` are going to be removed soon in favor of CSV.jl/CSVFiles.jl. Anyway, I don't think it's really possible to store arrays of arrays in CSV, which is a pretty limited format.

**Comment by rand5** [comment]
I'll clarify, storing arrays of arrays in CSV is not a problem- the issue is reading it back into Julia.

**Comment by nalimilan** [comment]
Yes, the problem is that there's no standard syntax to represent an array in CSV.

**Comment by quinnj** [comment]
To support this in CSV.jl, you would just need to define your own `Base.parse(::Type{Vector{Float64}, str)` method, then read the csv file like
```julia
CSV.read(filename; types=[Vector{Float64}])
```
