### ISSUE TITLE
StatsModels Enhanced Formulae Language (Two possible approaches)

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/DataFrames.jl#1216]
Currently `DataFrames.@formula` macro generates the `DataFrames.Formula` struct which has fields: `lhs` and `rhs`.  For categorical variables (`DataArrays.PooledDataArray`), `DataFrames.ModelFrame` can use a `Dict{Symbol, DataFrames.ContrastsMatrix}` to prepare the object for `DataFrames.ModelMatrix` to generate the desired `Matrix` and keep track of relevant data (e.g., `DataFrames.coefnames`).

### First Approach
The feature request is to allow for additional operators other than the currently implemented `+`, `*`, `&`. For categorical variables, codings are enabled through
```
mf = ModelFrame(@formula(y ~ x), df, contrasts = Dict(:x => EffectsCoding()))
```
and the following codings are available
- DummyCoding (default)
- EffectsCoding
- HelmertCoding
- ContrastsCoding

A welcomed addition would be to allow for codings for numerical variables (`DataArrays.DataArray`). For example,
- IdentityCoding (default)
- Log
- Poly(d::Integer)
```
fm = DataFrames.@formula(y ~ x1 + x2)
mf = DataFrames.ModelFrame(fm, df, contrasts = Dict((:x1, LogCoding()), (:x2, PolyCoding(2)))
```

### Second Approach
Modifying `DataFrames.Formula` and `DataFrames.@formula` to hold a third field (`lhs`, `rhs`, `coding`). This can be accomplished in a similar fashion as:
- Stata's `reg y i.x` for dummy coding
- R's `lm(y ~ log(x), df)` for common transformation
and implement these as we currently handle `+`, `*` and `&` for interactions.
```
DataFrames.@formula(y ~ log(x1) + poly(x2, 2) + i.x3 + EffectsCoding(x4))
```

Additional thought:
- The polynomial transformation can be pretty useful especially when building models where keeping track of derived features is essential. For example, for accurately computing the marginal effects of a logistic regression. Other functions that might use the information are multicollinearity diagnostics or lasso / net-elastic estimators in the group-versions.

**Comment by ararslan** [comment]
I believe @kleinschmidt is doing some work to this effect in [StatsModels](https://github.com/JuliaStats/StatsModels.jl), which will be the future home of the modeling code currently in DataFrames.

**Comment by kleinschmidt** [comment]
Correct! I'm working on a prototype that allows arbitrary functions in [StreamModels ](https://github.com/kleinschmidt/StreamModels.jl) (which I hope will eventually be adopted into StatsModels).  The README there is out of date but I've finished another iteration of prototyping and I'll update the README soon.

**Comment by kleinschmidt** [comment]
(The code in the master branch reflects the latest iteration though)

**Comment by Nosferican** [comment]
After deciding to scratch DataTables.jl + NullableArrays.jl framework (and parts of DataArrays.jl) in favor of Null.jl and continuing development in DataFrames.jl I wasn't sure if the plans to port src/StatsModels to StatsModels.jl were to continue. It wasn't mentioned in [Latest Announcement](https://discourse.julialang.org/t/announcement-an-update-on-dataframes-future-plans/4646).

I could look at StreamModels.jl and see what the timeline is in StatsModels.jl (the repository still uses the DataTables.jl previous framework and might do until back-porting to DataFrames.jl is complete). Thanks.

**Comment by kleinschmidt** [comment]
The plan is to make DataFrames.jl as lightweight as possible, which means (at least) moving all the formula/modeling stuff out to a separate package (that will work with other tabular data stores as well).

**Comment by Nosferican** [comment]
Will go ahead and close the issue here. Might open it in StatsModels or StreamModels (if you think it will be a better option, let me know).

**Comment by kleinschmidt** [comment]
I think StatsModels is the better choice, it'll be good to have a place there to discuss the design space for these things!
