### ISSUE TITLE
Appending to non-emty file: KeyError: key "Column names don't match names in file" not found

### ISSUE THREAD

**Issue by KarolisM** [JuliaStats/DataFrames.jl#1218]
Issue arises when one tries to append DataFrame to already existing non-empty file, for example:
```
using DataFrames

dataSupl = DataFrame(sample=String["as1"], stdevofnormcov=Float64[0.2])
println(STDERR, dataSupl, "\n")

if !isfile("test.csv")
    writetable("test.csv", dataSupl)
end

dataSupl = DataFrame(sample=String["as1"], stdevofnormcov=Float64[0.4])
println(STDERR, dataSupl, "\n")

if !isfile("test.csv")
    writetable("test.csv", dataSupl)
else
    writetable("test.csv", dataSupl, append=true)
end
```

Result:
![image](https://user-images.githubusercontent.com/8409950/29637712-acd70e58-885d-11e7-9624-e354ffe91c5a.png)

Clearly, two data frames have the same header. 

From your tests:
https://github.com/JuliaStats/DataFrames.jl/blob/7e47d0d5606e48e89600efdc4264724d106ae2a3/test/io.jl#L372

It seems that false is checked but true is not.

From code:
https://github.com/JuliaStats/DataFrames.jl/blob/86e56e221adb1fdb9b4dca76a6c2ddbb5ae3cf8f/src/abstractdataframe/io.jl#L119

Append, file and size are checked and if true: file is read with readtable() and with header=false flag. 
Then code checks if header=true in writetable() and compares to dataframe from readtable(...header=false...):

https://github.com/JuliaStats/DataFrames.jl/blob/86e56e221adb1fdb9b4dca76a6c2ddbb5ae3cf8f/src/abstractdataframe/io.jl#L129

readtable() header flag should be true. In this case. According to current logic. Only way around is to:

```
if !isfile("test.csv")
    writetable("test.csv", dataSupl)
else
    writetable("test.csv", dataSupl, append=true, header=false)
end
```
But documentation does not state that. At least, I didn't find..

**Comment by nalimilan** [comment]
Sorry, but `writetable` is going to be deprecated in favor of CSV.jl and CSVFiles.jl. I suggest checking whether what you need works with these packages, and if not file an issue there.

**Comment by quinnj** [comment]
`readtable` `writetable` are now deprecated.
