### ISSUE TITLE
DataStream Cleanup

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#133]
Priorities:
* Don't return an empty DataFrame at the end of the DataStream iteration loop. Instead of using integer states, use DataFrame states.
* Decide where `coltypes(ds)` gets set and where it actually needs to be used. In many cases, it's simpler to just use the `coltypes` of the incoming minibatches. Perhaps `coltypes(ds)` should not even exist.

**Comment by garborg** [comment]
Removed.
