### ISSUE TITLE
Add configuration options to control max rows and columns for printing

### ISSUE THREAD

**Issue by GlenHertz** [JuliaStats/DataFrames.jl#140]
This is a fork of Issue #136 to add global configuration setting(s) to control how many lines get printed out when there is too much data to display.  Pandas ([link](http://pandas.pydata.org/pandas-docs/stable/basics.html?highlight=set_printoptions#working-with-package-options)) and R (eg `max.print`) both have methods to globally control printing options.

Perhaps this is best accomplished with support from the Julia core team as these interfaces could be used for controlling the printing of Arrays, etc.

Glen

**Comment by quinnj** [comment]
This can now be configured using an `IOContext` with the `:displaysize=>(rows,cols)` argument, like
```julia
julia> show(IOContext(STDOUT, :displaysize=>(10,10)), df)
10×10 DataFrames.DataFrame
│ Row │ ├─────┼
│ 1   │
⋮
│ 9   │ │ 10  │

│ Row │ x1  │
```
