### ISSUE TITLE
Creating model matrix columns from a PooledDataVector

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataFrames.jl#161]
I feel rather dumb for having done this in such an awkward way in some examples in the Glm code.  The way that a factor is incorporated in a model matrix in R is through indexing the rows of a constrasts matrix.  The default contrasts in R are the treatment contrasts defined by contr.treatment.  The contr_treatment generic in the Glm package is patterned on the R function.  To generate the columns of a model matrix for a PooledDataVector use

```julia
contrasts(vv::PooledDataVector) = contr_treatment(length(vv.pool))[vv.refs,:]
```

Enhancements would take into account dropping unused levels and situations where you don't need contrasts but instead need the indicators (which can also be simplified), switching to other forms of contrasts, etc.

**Comment by nalimilan** [comment]
Closing given the big improvements in contrasts handling that have happened since then.
