### ISSUE TITLE
Pretty-printing of Formula objects

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#163]
7ef52711e16a44cc5851ebfd04358cd8f2127368 starts to define a `show` method for Formula objects. Making this nice will make the output from GLM's much more readable. We probably need a full `deparse` method to get something clean.

**Comment by quinnj** [comment]
Can be re-opened at https://github.com/JuliaStats/StatsModels.jl if still desired.
