### ISSUE TITLE
SubDataFrame and SubArray are not compatible

### ISSUE THREAD

**Issue by tshort** [JuliaStats/DataFrames.jl#167]
This is a subset of issue #142. 

Because DataArrays are now AbstractArrays, `sub(dv, idx)` does work (the `show` method is messed up, though). For a DataFrame `df`, we want `sub(df, [2,4])["colA"]` to return the same thing as `sub(df["colA"], [2,4])`. It can't now because the indexes on SubDataFrames and SubArrays are different. SubDataFrames use an integer array for indexes:

``` jul
type SubDataFrame <: AbstractDataFrame
    parent::DataFrame
    rows::Vector{Int} # maps from subdf row indexes to parent row indexes
```

SubArrays use a RangeIndex for indexes:

``` jul
typealias RangeIndex Union(Int, Range{Int}, Range1{Int})
```

The biggest reason for the incompatibility is that RangeIndex does not include Vector{Int}. 

To make these more compatible, we need to work with Julia core to come up with a common indexing type. It would be best if SubDataFrames could store a Range as well as Vector{Int}, and SubArrays could store a Vector{Int} index as well as Ranges.

**Comment by quinnj** [comment]
The original indexing issue now works.
```julia
julia> view(df, [2,4])[:x1]
2-element Array{Float64,1}:
 0.0
 0.0

julia> view(df[:x1], [2,4])
2-element SubArray{Float64,1,Array{Float64,1},Tuple{Array{Int64,1}},false}:
 0.0
 0.0
```
