### ISSUE TITLE
Formula/ModelMatrix should support functions of variables

### ISSUE THREAD

**Issue by HarlanH** [JuliaStats/DataFrames.jl#19]
This requires two things. The function should work on a DataVec (currently log() does, see datavec.jl), and the ModelFrame (or maybe ModelMatrix) constructor should evaluate the function.

**Comment by nalimilan** [comment]
See also https://github.com/JuliaStats/DataFrames.jl/issues/867 about using `y ~ pool(x)` to treat a numeric variable as categorical only in a specific model.

**Comment by ararslan** [comment]
Planned in StatsModels, where the modeling functionality has moved.
