### ISSUE TITLE
Long time for initial load of DataFrames package

### ISSUE THREAD

**Issue by dreiss-isb** [JuliaStats/DataFrames.jl#208]
I finally started using DataFrames and it has sped up my code immensely.

Now my largest bottleneck is simply the loading of the package  -- about 15 seconds on my Mac pro.

The primary bottleneck seems to be in operators.jl ...

How easy would it be to create a DataFrames package sysimage for loading? Or a better solution...?

**Comment by garborg** [comment]
Closing for now as not DataFrames-specific. Can reopen if still slow after package load time has progressed (ecosystem-wide).
