### ISSUE TITLE
NAtype is oddly capitalized

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaStats/DataFrames.jl#211]
It took me a while to figure out what I was doing wrong when I was grepping through the DataFrames code for the definition of `NAType`. Turns out it's spelled `NAtype`. Is it just me or does not capitalizing the "T" seem odd?

**Comment by ararslan** [comment]
`NAtype` is no longer part of DataFrames but rather of DataArrays. Since this doesn't apply here anymore I'm going to go ahead and close the issue. Could be worth bringing it up again on DataArrays though.
