### ISSUE TITLE
An ETA on Kevin's revisions to PooledDataArray to parameterize the type of the refs field?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataFrames.jl#241]
I had seen messages coming through about @kmsquire providing a parameterized refs field for the PooledDataArray type and the ability to switch to a more compact representation when the size of the pool is small.  It seems that this is still in Kevin's fork.  Is there something I can do to facilitate bringing this into the main branch?  One of the data sets for the "torture test" of the mixed-models software has a factor with 800,000+ levels.

**Comment by garborg** [comment]
Believe this was done long ago.
