### ISSUE TITLE
Equivalent of R's "." in formulas

### ISSUE THREAD

**Issue by IainNZ** [JuliaStats/DataFrames.jl#246]
It'd be great to have an equivalent of R's "." to select all columns for model fitting, e.g.

glm(:(outcome ~ .), df, Bernoulli())

@dmbates points out in JuliaStats/GLM.jl#18 that this pretty darn hard (at least with the way R has it), but it'd be great to have.

**Comment by quinnj** [comment]
Can be re-opened at https://github.com/JuliaStats/StatsModels.jl/issues if still desired.
