### ISSUE TITLE
Implement `na_rm` for math functions?

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#259]
I'd like to change functions like `sum` to use keyword arguments so that we can provide the R-like `sum(x, na_rm = true)`. What do people think of this? Do we want to also implement `na_fail` and `na_replace`? For many functions like `mean`, I think `na_rm` is the only option that sanely respects the level of uncertainty when you have `NA`'s.

**Comment by garborg** [comment]
Long done.
