### ISSUE TITLE
Type assumptions about inserting columns

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#260]
I think the following behavior should be treated as a bug:

    julia> using DataFrames
    julia> df["a"] = repmat([1, 3, 5], 10, 1)
    julia> nrow(df)
    1

If we attempt to insert a vector, we should automatically expand the DataFrame. At one point, I thought we were doing this (although I'm not sure).

**Comment by garborg** [comment]
No longer allowed.
