### ISSUE TITLE
New DataFrame bug with multiproc code

### ISSUE THREAD

**Issue by dreiss-isb** [JuliaStats/DataFrames.jl#265]
I have spent many hours trying to track down the cause of this error in my program, and I believe it stems from DataFrames serialization. I say it is "new" because I didn't see it in Julia v0.1.2, using the corresponding version of DataFrames package. It seems to lead to occasional memory corruption and/or random crashes of my parallelized code (which sends and receives small DataFrames to/from the child nodes).

I have come up with a simple test case. Download [this code](https://dl.dropboxusercontent.com/u/495317/test3.jl) and [this csv file](https://dl.dropboxusercontent.com/u/495317/test3.csv) to the same directory. Run the code with the "-p 2" option:

julia -p 2

and in julia, simply

load("test3.jl")

This will crash randomly between a few and a few dozen iterations, with either a segfault, or a serialization error.

I'd appreciate any pointers to fixing this. Thanks.

**Comment by garborg** [comment]
Closing as not actionable / likely resolved. Please re-open with a minimal test case if you can reproduce.
