### ISSUE TITLE
Can `Index` be made to accept `String` types?

### ISSUE THREAD

**Issue by quinnj** [JuliaStats/DataFrames.jl#289]
I've gotten this error a few times while constructing DataFrames on the fly in the ODBC and SQLite packages. 
```julia
 ERROR: no method Index(Array{String,1},)
```
Is there a reason `Index` doesn't accept an array of Strings? My workaround is to try and make sure these arrays end up as `ASCIIString`s or `UTF8String`'s, but it crops up every so often when I throw a `String` in somewhere. Not a major concern, but I just wanted to bring it up, because it's unexpected.

**Comment by garborg** [comment]
No longer relevant since the move from strings to symbols.
