### ISSUE TITLE
Add advanced features for `readtable()`

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#292]
We need to support all of the following to fully match R's and pandas' level of functionality:
- [ ] Support reading from URL's
- [ ] Support reading files with multicharacter delimiters
- [x] Decompress files on the fly using GZip or BZip2
- [ ] Automatically parse date and time columns
- [ ] Implement `skiprows`, which specifies the indices of lines in the raw input to skip and defaults to `Int[]`. The current implementation has a placeholder that does nothing.
- [ ] Implement `skipend`, which specifies the number of lines to skip at the bottom of a file  and defaults to `0`.
- [ ] Implement `converters`, which specifies a `Dict` of functions, each of which specifies how to convert the values in a named column to a desired type.
- [ ] Implement `encoding`, which specifies whether a file is encoded in `:utf8` or `:latin1`. The current implementation has a placeholder that does nothing.
- [ ] Implement `allowescapes` and `escapemark`, which allow characters like `\n` or `,` to be escaped in unquoted fields.

**Comment by holder66** [comment]
Looks like skiprows is not working:
`julia> anneal=readtable("anneal.tab", separator=' ',skiprows=[2, 3])
ERROR: ArgumentError: Argument 'skiprows' is not yet supported.
 in readtable at /Users/henryolders/.julia/v0.4/DataFrames/src/dataframe/io.jl:823
 in readtable at /Users/henryolders/.julia/v0.4/DataFrames/src/dataframe/io.jl:945
`

**Comment by quinnj** [comment]
These are mostly implemented in CSV.jl; additional issues can be opened there for specific requests.
