### ISSUE TITLE
InexactError() on division of integer columns

### ISSUE THREAD

**Issue by sam81** [JuliaStats/DataFrames.jl#306]
not sure if the following behaviour is intended:

    x = [1:10]
    y = [2:11]
    df = DataFrame({"x"=>x, "y"=>y})

    julia> df["x"] ./ df["y"]
    ERROR: InexactError()
     in ./ at /home/sam/.julia/DataFrames/src/operators.jl:805

the division between columns of integers gives an error, I can perform
the division by converting first to float

    julia> float(df["x"]) ./ float(df["y"])
    10-element Float64 Array:
     0.5     
     0.666667
     ....
 
I find this somehow unintuitive given that division of column vectors
works without problems in the base language:

    julia> x ./ y
    10-element Float64 Array:
     0.5     
     0.666667

**Comment by garborg** [comment]
Long fixed.
