### ISSUE TITLE
Make the DataFrame constructor take a header option

### ISSUE THREAD

**Issue by ViralBShah** [JuliaStats/DataFrames.jl#307]
Even though `readtable` exists, out of habit, I end up loading files with `readcsv` sometimes - `df = DataFrame(readcsv("file"))`. `readcsv` returns an `Array{Any}`, with the first row often being a header. 

When creating a dataframe from `Array{Any}`, is there a way to ask it to treat the first row as a header? I imagine this is even possible to autodetect, if the type of the first row is different from the rest of the rows.

**Comment by garborg** [comment]
Closing as this workflow hasn't come up for some time.
