### ISSUE TITLE
blocked arrays for DataVec?

### ISSUE THREAD

**Issue by HarlanH** [JuliaStats/DataFrames.jl#31]
There's an argument that DataVecs should not be unitary vectors, but instead should be blocked arrays. This would allow relatively common data-cleaning operations such as "delete 17 random rows from this billion-row DataFrame" to be very fast instead of very slow. Basically, columns would be stored in chunks of, say, 4KB (often the size of disk blocks), and single row deletions would require only a shuffling of a single block. Blocks would merge when two adjacent blocks were less than half full. A block structure might also be convenient for indexing, and likely for memory-mapping too. On the other hand, other operations would be more complex.

**Comment by quinnj** [comment]
This would be better experimented w/ as a stand-alone package `BlockArrays.jl` or something where individual columns/vectors could be blocked. DataFrames is now mostly agnostic to the underlying column types.
