### ISSUE TITLE
DataFrame should provide complete variable names.

### ISSUE THREAD

**Issue by mweiden** [JuliaStats/DataFrames.jl#319]
Given a DataFrame:

```
julia> form = readtable("test/data/factors/mixedvartypes.csv",makefactors = true)
```

the fields in the DataFrame type do not readily provide variable labels in the case of factors. Given that factorvar is a factor with three possible values

```
julia> form["factorvar"].pool
3-element UTF8String Array:
 "blue"
 "green"
 "yellow"
```

it would make sense to me that indicator variables that are derived from factored categorical variables should have variable names constructed for them in a field in DataFrame (perhaps something like "factorvar:blue"). This information could then be more easily pulled from the frame to label the variables in modules such as GLM.

To illustrate check out this LmMod.

```
julia> fm3 = lm(:(y ~ factorvar), form)

Formula: y ~ factorvar

Coefficients:
3x4 DataFrame:
        Estimate Std.Error t value  Pr(>|t|)
[1,]        0.25  0.193649 1.29099   0.25317
[2,]        0.75  0.295804 2.53546 0.0521814
[3,]        0.75  0.433013 1.73205  0.143811
```

the row indicies at left are pretty unsatisfying descriptors for what is being estimated. I am guessing that this is because ModelFrame does not make it easy to label the expanded variables.

Comparatively, the GLM.jl documentation mentions that in R more descriptive information is given:

```
> coef(summary(lm(optden ~ carb, Formaldehyde)))
               Estimate  Std. Error    t value     Pr(>|t|)
(Intercept) 0.005085714 0.007833679  0.6492115 5.515953e-01
carb        0.876285714 0.013534536 64.7444207 3.409192e-07
```

**Comment by quinnj** [comment]
Should be re-opened at https://github.com/JuliaStats/StatsModels.jl/issues if this is still an issue.

**Comment by ebbythomas** [comment]
In Julia, if you have a model named "model",
```
coefnames(model.mf)
```
gives you the names of all the variables, whether it is categorical or ordinal.
Again, if you parse it you cane get out of the StatType of the model names
```
parse.coefnames(model.mf)
```
