### ISSUE TITLE
Remove seemingly equivalent ways of producing subsets of DataFrames

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#323]
We have too many ways of producing things that seem like subsets of a `DataFrame`. After I added `filter`, we now have four ways that seem superficially equivalent, but reflect two different algorithms:

```
julia> df[:(A % 2 .== 0 && B % 4 .== 0), :]
ERROR: type: non-boolean (DataArray{Bool,1}) used in boolean context
 in anonymous at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1457
 in with at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1458
 in getindex at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:428

julia> sub(df, :(A % 2 .== 0 && B % 4 .== 0))
ERROR: type: non-boolean (DataArray{Bool,1}) used in boolean context
 in anonymous at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1457
 in with at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1458
 in sub at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1014

julia> subset(df, :(A % 2 .== 0 && B % 4 .== 0))
ERROR: type: non-boolean (DataArray{Bool,1}) used in boolean context
 in anonymous at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1457
 in with at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1458
 in sub at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1014

julia> filter(:(A % 2 .== 0 && B % 4 .== 0), df)
ERROR: type: non-boolean (DataArray{Bool,1}) used in boolean context
 in anonymous at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1457
 in with at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1458
 in filter at /Users/johnmyleswhite/.julia/DataFrames/src/dataframe.jl:1023
```

I think we should:
- Return `SubDataFrame` objects everywhere when accessing all columns of a DataFrame, which is what `sub` does, but direct indexing does not do.
- Rename `sub` to `filter` after flipping the argument order. We will then remove `sub` and `subset` completely.

Having multiple ways of doing the same thing troubles me in general, but seems particularly problematic when the different ways are not strictly aliases of one another. Over time, end-users discover that, even though all subset operations are equal in outcome, some are more equal than others.

**Comment by quinnj** [comment]
I don't think this is an issue anymore; DataFrames doesn't have `subset` or `filter` anymore and `view` or bit/bool array indexing seem to be fairly standard and non-controversial.

**Comment by nalimilan** [comment]
Funny timing, as we just deprecated `select` in Base (https://github.com/JuliaLang/julia/pull/23051).
