### ISSUE TITLE
typeassert, expected Int32, got Int64 in readtable.

### ISSUE THREAD

**Issue by dinurp** [JuliaStats/DataFrames.jl#330]
Hi,
In src/io.jl, nrows and nbytes needs to be Int for the subsequent call to readtable(IO). Here nbytes is Int64 as returned by filesize. This fails in 32 bit builds.
710:    else
711:       io = open(pathname, "r")
712:        nbytes = filesize(pathname) 
713:   end
714:
715:    if nrows == -1
716:         nrows = nbytes
714:    end

This resulted in error while loading some RDatasets.
https://github.com/johnmyleswhite/RDatasets.jl/issues/12

Regards,
Dinu

**Comment by garborg** [comment]
Passing on 32-bit for some time.
