### ISSUE TITLE
'Union All' Alias to 'rbind' in Join function?

### ISSUE THREAD

**Issue by randyzwitch** [JuliaStats/DataFrames.jl#343]
Within the `join` function, there are currently four choices: 'Inner', 'Right', 'Left', and 'Outer'. There's actually a fifth, lesser used 'Union' join, which is similar to the `rbind` scenario of stacking multiple files. (Technically, `rbind` is 'Union All' in SQL, stacking all rows from tables....'Union' is the case of stacking two or more tables AND de-duplicating records)

Should we make an alias of 'Union All' to `rbind` within the `join` function to represent the fifth join choice? rbind and cbind are relatively arbitrary as terms IMO (just R syntax), whereas 'Union All' is SQL standard syntax. 

Only downside would be, by moving to 'Union All' syntax, it would naturally imply needing to extend the `join` function to do de-duplication using 'Union' for completeness.

http://www.w3schools.com/sql/sql_union.asp

**Comment by fiatflux** [comment]
I think this can be closed now.

**Comment by randyzwitch** [comment]
Agreed
