### ISSUE TITLE
Mathematical operations for DataFrames

### ISSUE THREAD

**Issue by nfoti** [JuliaStats/DataFrames.jl#346]
Common math operations that work along dimensions of `Array`s would be useful for `DataFrame`s (and `DataArray`s as discussed in issue #325).  The use case I envision is there are many numerical columns and some categorical columns, and say we want to compute the average of the numerical columns.  It would be great to be able to say `df["mean_col"] = mean(df[:,numeric_colinds], 2, skipna=true)` without having to convert to a `DataMatrix` first.  If someone tries to take the mean of something that doesn't make sense an error can be thrown.

If people think this is useful I'm willing to take a stab at it.  I prefer the `mean(df, dim, skipna)` interface to `rowmeans` and `colmeans` to stay consistent with the rest of Julia but if others prefer the R names I can go along with that.

Thanks.

**Comment by garborg** [comment]
Closing as ensuing discussions have also landed on 'no' to treating DataFrames this way.
