### ISSUE TITLE
DataFrame assignment behavior

### ISSUE THREAD

**Issue by nfoti** [JuliaStats/DataFrames.jl#348]
Say I have the following code:
```
df = DataFrame(A = 1:4, B = randn(4))
df[["A","B"]] = randn(4,2)
```
I would expect `df` to now be a 4x2 `DataFrame` filled with the result of `randn(4,2)`.  However, I end up with a 4x2 `DataFrame` where each entry is the 4x2 matrix returned by `randn(4,2)`.  Is this intentional?

**Comment by garborg** [comment]
As long-settled on, throws an error these days.
