### ISSUE TITLE
Feature request: exposing function equivalent to get_dummies?

### ISSUE THREAD

**Issue by randyzwitch** [JuliaStats/DataFrames.jl#355]
In the documentation, there's a reference to auto-conversion of `PooledDataArray` into 0/1 columns. Can this be exposed as a public function within DataFrames, similar to get_dummies in pandas?

Yes, it's unnecessary/wasteful in terms of calculation performance within Julia, but it's a useful step when dumping a DataFrame to .csv for other uses.

``` plaintext
Pooling columns is important for working with the GLM package. When fitting
regression models, PooledDataArray columns in the input are translated into 0/1 
indicator columns in the ModelMatrix – with one column for each of the levels of the 
PooledDataArray. This allows one to analyze categorical data efficiently.

```

**Comment by quinnj** [comment]
@nalimilan, can you say whether this is still relevant?

**Comment by nalimilan** [comment]
Certainly not in DataFrames. There's `StatsBase.indicatormatrix`, and we could add a specialized method for `CategoricalArray`.
