### ISSUE TITLE
Ergonomic ways of recoding data

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/DataFrames.jl#369]
In many scientific disciplines, and in particular in social sciences (where I work), recoding data is one of the major steps, sometimes the most time-consuming and often the most dangerous (in terms of what mistakes one can easily do that go unnoticed). One of the limitations of R as compared to SAS is that recoding data was not very intuitive due to the vectorized logic.

For those not familiar with SAS, the strength of its `data` step (and maybe its only stength actually) is that it hides the fact that the operations are run in a loop over all rows of a table. This gives a very natural way of thinking of potentially complex interaction of (possibly nested) `if` conditions. A simple example:

```
data table2;
set table1;
a = b + c**2;
if x in (1, 2, 3) and y = 1 then z = 1;
else if x = 4 then z = y;
else z = 3;
run;
```

In R, one would rather use vectorized assignments, like:

```
df <- data.frame(b=runif(10), c=runif(10), z=10, x=1:10, y=2:11)
df <- within(df, {
    a <- b + c^2
    z[x %in% 1:3 & y == 1] <- 1
    z[x == 4] <- y[x == 4]
})
```

But this solution can get cumbersome with complex conditions, and `[x == 4]` must be repeated twice, which breaks the DRY principle (there's also the issue of assignments with NA indexing...).

In Julia, I guess something similar to R would be used, or a manual loop could be run over the rows of a DataFrame, each time indexing the DataFrame to extract one row an apply operations to it. But repeatedly indexing using 
`df[i, :]` is painful, and you need to remember to assign the result of your computations for each variable.

Maybe there would be a solution to add some syntactic sugar in order to get closer to the SAS `data` syntax? This could also allow for automatic parallel processing depending on the number of cores and on the number of rows in the table.

A related feature would be a simple but short function allowing to rename/group levels of a variable, usually categorical ones. In R, John Fox's package car provides recode(): http://hosho.ees.hokudai.ac.jp/~kubo/Rdoc/library/car/html/recode.html

Typical case is for recoding data which comes coded using numbers to something more explicit, with some regrouping of levels :

```
recode(x, "1:2='A'; c(3, 5)='B'; else='C'")
recode(x, "lo:20='A'; 21='B'") # lo for Lower bound
```

The current limitation of this function is that the recoding "formula" is fully quoted, which means that syntax highlighting and built-in error checking is lost. This could probably be improved with some language trickery, since nothing is fundamentally incompatible with standard language features in such a syntax. One could also think of having a way of specifying `<=` or `<` in order to handle numeric variables similar to `cut()`.

It would be great to see Julia beat alternatives on both the computation and data management aspects. This would really be a compelling feature.

**Comment by quinnj** [comment]
@nalimilan, is this still relevant?

**Comment by nalimilan** [comment]
Probably not. We now have Query.jl, DataFramesMeta.jl, and `recode` in CategoricalArrays.jl.
