### ISSUE TITLE
LINQ like API to work with Data frames

### ISSUE THREAD

**Issue by lindahua** [JuliaStats/DataFrames.jl#381]
This is not related to the approach being discussed in #206, which seems to focus more on running SQL strings. 

I think it would also be nice to have an API similar to LINQ for data frames, with which we can write
```julia
df2 = @select (name, date, val).
       from(my_df).
       where(10 < val < 20).
       orderby(val, "desc") 
```
This is well formed syntax in Julia, and it is doable if we implement the ``@select`` macro properly.

**Comment by ararslan** [comment]
Looks like the discussion of such an API has been continued in https://github.com/JuliaStats/DataFrames.jl/issues/1025.
