### ISSUE TITLE
Error showing wide dataframes

### ISSUE THREAD

**Issue by ViralBShah** [JuliaStats/DataFrames.jl#383]
I have a dataframe that is quite wide to display, and used to load just fine earlier. It loads fine now, but never returns. If I press ctrl-c, it gives me this, and I can continue working with it.

````
julia> @time vl = DataFrame(vl)
elapsed time: 0.559995546 seconds (173700240 bytes allocated)

^CEvaluation succeeded, but an error occurred while showing value of type DataFrame:
ERROR: interrupt
````

**Comment by garborg** [comment]
No longer an error, but still annoying -- new issue here: #760
