### ISSUE TITLE
Implement URL retrieval for readtable

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/DataFrames.jl#385]
This feature has been stubbed out and currently throws the error "URL retrieval not yet implemented"

https://github.com/milktrader/Quandl.jl/issues/8

https://github.com/milktrader/Quandl.jl/issues/1

**Comment by quinnj** [comment]
CSV.jl can read from any IO object, including the result of a `HTTP.get(url)` call, so this is supported
```julia
CSV.read(HTTP.body(HTTP.get(csv_url)))
```

**Comment by davidanthoff** [comment]
[CSVFiles.jl](https://github.com/davidanthoff/CSVFiles.jl) also supports reading from a URL directly:
````julia
df = DataFrame(load("http://someurl.org/somefile.csv"))
````
