### ISSUE TITLE
Question: common mathematical reductions isolating numerical columns

### ISSUE THREAD

**Issue by sglyon** [JuliaStats/DataFrames.jl#391]
Disclaimer: I love pandas and would like to see more pandas goodness in dataframes.

I am proposing that common reductions like sum, mean, std, ect. Should work on all dataframes, but just isolate numerical columns. If a dataframe has some numerical columns and some non-numerical ones, it would be nice for the behavior of these functions to work on numerical columns without throwing an error. This is the behavior of pandas and it quite handy.

---

EDIT: I believe we should have things like `colmeans` `colvars` calculate the associated reductions on only numeric columns.

**Comment by quinnj** [comment]
Please re-open if still relevant.
