### ISSUE TITLE
Rename "makefactors" argument to readtable()

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/DataFrames.jl#399]
`makefactors` is clearly inspired from R. But in Julia factors do not exist at the moment, and they have no name. Cf. the discussion at https://github.com/JuliaStats/DataFrames.jl/issues/6?source=cc#issuecomment-8875221.

Anyway, the `makefactors` argument to `read.table()` is not about the nature of the variable (nominal, ordinal...), since that cannot be know from the CSV file. The argument is only about how to store the data, i.e. DataArray or PooledDataArray. The user will have to decide how to treat the data later anyway. So what about calling the argument "pool"?

**Comment by quinnj** [comment]
Moved to https://github.com/JuliaData/CSV.jl/issues/98
