### ISSUE TITLE
Allow easily reading CSV2 (with ; as delimiter and , as decimal mark)

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/DataFrames.jl#402]
If you have the chance of living in a country where the decimal mark is `,`, you probably know that using CSV is the most terrible experience you can have with data formats. :-)

Here in France, as in many countries, Microsoft Excel can only write pseudo-CSV files with `,` as decimal mark and `;` as a delimiter. Other applications, like LibreOffice, still stick to the traditional CSV format by default.

One of the many problems this creates is that simply using the extension to choose the delimiter, as does `readtable()`, does not work in this case. This is why R provides a `read.csv2()` function for convenience, since beginners usually do not understand the subtleties of pseudo-CSV enough to tweak delimiter and decimal mark by hand. But at the moment, `readcsv()` is used by base Julia, so adding `readcsv2()` in DataFrames would not be acceptable.

I fear that the current situation where Base provides `readdlm()` and `readcsv()`, and DataFrames provides `readtable()`, is going to create confusion, since `readcsv()` looks like the first place to look at for anybody willing to read a CSV database, even if what they need is a DataFrame. Also,  `readdlm()` and `readtable()` look like they are reading different formats, while actually the difference lies in the interpretation.

So the small issue of the `;` delimiter leads to questioning much deeper things. I don't have the solution, but one way would be to make names more explicit, to make it clear that one function creates arrays and the other data frames. What do you think?

**Comment by quinnj** [comment]
Opened https://github.com/JuliaData/CSV.jl/issues/97 to track alternative decimal float parsing and CSV.jl already supports arbitrary delimiters.
