### ISSUE TITLE
Do not import anything, just explicitly extend it

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#409]
I've increasingly come to think that Julia code is more readable if we avoid doing any broad `import` calls and only use `Base.foo` names instead. This makes it easy to identify the source of any function and makes it more obvious when you're doing something that might have negative consequences.

**Comment by garborg** [comment]
Complete as of 84ebf99cf1427a3554d0fbeaa0ec038e6bf5d565
