### ISSUE TITLE
Readtable not honoring properly formatted csvs

### ISSUE THREAD

**Issue by garborg** [JuliaStats/DataFrames.jl#425]
This really shouldn't happen:

``` julia
string = "actor,fave_character\nJohnny,\t\nSally, \nLeland,%\n";
open("test.txt", "w") do io
    println(io, string)
end
df = readtable("test.txt")
```

replaces characters with NAs:

```
           actor fave_character
[1,]    "Johnny"             NA
[2,]     "Sally"             NA
[3,]    "Leland"            "%"
```

This is because of the attempt to play nice with nonstandard formats (whitespace around field delimiters).

I know that there's not much a of standard, but my thought is that the function can't mess up reading files that follow the basic rules.

My understanding of the basics:
There are 3 kinds of separators -- call them 'EOL', 'separator', and 'quotemark' for consistency with DataFrames code.
Where the first two go is self-explanatory. The third must bookend any fields that have either of the first two as characters, and may bookend other fields.
Fields bookended with quotemarks must escape any quotemark characters in their contents, in one of a couple ways.

The user may be required to specify delimiters and quote-escaping method, but if they specify correctly, or the file follows the function's defaults, data shouldn't be corrupted.

**Comment by quinnj** [comment]
CSV.jl correctly handles this (by not assuming null fields unless the field actually is two consecutive delimiters or a custom null string is provided and matched).
