### ISSUE TITLE
Add non-copying rbind!/append! for DataFrames

### ISSUE THREAD

**Issue by quinnj** [JuliaStats/DataFrames.jl#429]
As discussed here:

https://groups.google.com/forum/#!searchin/julia-stats/rbind!/julia-stats/XEgULfbODDI/Ps-8_pFjJxgJ

**Comment by garborg** [comment]
`append!` and `DataFrames.hcat!` exist these days (`DataFrames.hcat!` hasn't been exported as there's so much in flux, package-design-wise).
