### ISSUE TITLE
make rbind() work with DFs with non-identical column sets

### ISSUE THREAD

**Issue by HarlanH** [JuliaStats/DataFrames.jl#44]
* any columns present in one but not the other should have NAs in the missing values
* columns should be in the order of the first argument's DF, followed by any unique columns in the second argument's DF
* attempt to promote column types; throw an error if they can't be reconciled
* use the first DF's columns' meta-data (NA behavior)

did I miss any obvious requirements?

**Comment by garborg** [comment]
Long done.
