### ISSUE TITLE
Clean up colwise

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#485]
Instead of offering functions `colmean`, `colstd`, etc., I'd like to lean more heavily on `colwise`. Right now its behavior surprises, although I think I understand the logic.

```
using DataFrames
    df = DataFrame(A = 1:4, B = randn(4))
    colwise(cumsum, df) # -> Evaluates to Array{Any}
```

I assume we do this with the assumption that the return values for a function may differ in length across columns, which means that we can't do better than return a generic `Array{Any}`. That might be the right approach, but it's worth making sure that we prefer this very general strategy over something that would produce a more easily interpreted DataFrame.

**Comment by mkborregaard** [comment]
Revisiting this 2 years later, colwise still returns an array of Any, where each element is a Vector, even when the result of each operation is a scalar. Example:
```julia
df =DataFrame(a = repeat([1,2,3,4], outer =[2]), b =repeat([2,3], outer =[4]), c =randn(8))
colwise(sum, df)
```
gives
```
3-element Array{Any,1}:
 [20]    
 [20]    
 [5.0978]
```
This is not really convenient for any further work on the column results.

**Comment by cjprybol** [comment]
@mkborregaard this has been addressed in DataTables by https://github.com/JuliaData/DataTables.jl/pull/28

**Comment by mkborregaard** [comment]
Great, thanks for the heads up! Must be nice to be able to close a three year old issue :-)
