### ISSUE TITLE
Ensure complete code coverage

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#489]
Our current test suite seems to be a bit inadequate. Thanks to Jeff's recent patch to Julia, running `julia --code-coverage test/runtests.jl` shows how much of our codebase is either not touched at all by our test suite or is touched in a way that the code coverage tool can't detect.

**Comment by quinnj** [comment]
More specific issues can be opened to add coverage to specific parts of the codebase.
