### ISSUE TITLE
I/O interface changes

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#495]
- [x] Always clean names to make them valid Julia identifiers
- [ ] Implement alternative decimal place support for floating point inputs
- [ ] Add allowquotes option in addition to passing empty `quotemark` argument
- [ ] Allow (possibly default to) using mmap to access bytes of input file instead of reading them into a buffer in memory

**Comment by quinnj** [comment]
All implemented in CSV.jl
