### ISSUE TITLE
Clear statement of core functionality

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#502]
I'd like to finally formalize a specification of the core functionality we expect from every AbstractDataFrame. Here's a start at it, which proposes the long-term specification that will make sense when Julia's Base indexing produces views rather than copies.
# Basic Data Structure Properties

An AbstractDataFrame (ADF) is a database-like object that possesses the following properties:
- It has C columns, each of which is a "dense" abstract vector of length N. Each column, being a Julian vector, has a fixed type. Two distinct columns, C1 and C2, may have different types.
- The columns have a well-defined ordering, which means that it is always possible to reliably refer to columns by a numeric index.
- The columns have well-defined names, which means that it is always possible to reliably refer to columns using strings. These names **must** be valid Julia identifiers.
- The rows have a well-defined ordering, which means that it is always possible to reliably refer to columns by a numeric index. But, unlike standard SQL databases, the numeric ID of a row may change if the total number of rows in the DataFrame is changed. In other words, row ID's cannot be used as unique keys for rows in a DataFrame that might change.
# Basic Indexing

DataFrame's allow indexing that mixes ideas from matrices and dictionaries. Importantly, the rows and columns of a DataFrame are indexed in different ways:
- Rows can only be indexed using numeric or Boolean indices.
- Columns can be indexed using numeric, Boolean and string indices.

More precisely, the following grammar describes the basic index types that can be used with a DataFrame:
- SingleRowIndex -> Real
- SingleColumnIndex -> Real | String
- MultiRowIndex -> AbstractVector{T <: Real} | Colon
- MultiColumnIndex -> AbstractVector{T <: Real} | AbstractVector{T <: String} | Colon
- BooleanRowIndex -> AbstractVector{Bool}
- BooleanColumnIndex -> AbstractVector{Bool}

BooleanRowIndex and BooleanColumnIndex also impose additional semantic requirements that are not expressed in terms of Julia's type system.
- A Boolean row index must have the same length as the number of rows in the indexed ADF.
- A Boolean column index must have the same length as the number of columns in the indexed ADF.

Given these types of indexing operands, the indexing operations produce the following results:
- df[SingleColumnIndex] -> Vector | DataVector | PooledDataVector
- df[MultiColumnIndex] -> SubDataFrame
- df[SingleRowIndex, SingleColumnIndex] -> Value of type eltype(df[SingleColumnIndex] )
- df[SingleRowIndex, MultiColumnIndex] -> SubDataFrame
- df[SingleRowIndex, BooleanColumnIndex] -> SubDataFrame
- df[MultiRowIndex, SingleColumnIndex] -> SubVector | SubDataVector | SubPooledDataVector
- df[MultiRowIndex, MultiColumnIndex] -> SubDataFrame
- df[MultiRowIndex, BooleanColumnIndex] -> SubDataFrame
- df[BooleanRowIndex, SingleColumnIndex] -> SubVector | SubDataVector | SubPooledDataVector
- df[BooleanRowIndex, MultiColumnIndex] -> SubDataFrame
- df[BooleanRowIndex, BooleanColumnIndex] -> SubDataFrame
# I/O

It should always be possible to read and write ADF's using appropriate data structures, including CSV files, Vega-style JSON, etc.
# Basic Operations on ADF's
- Conversion to Matrix and DataMatrix
- Column-wise function application
- Row-wise function application
- Formulas as a DSL for converting DataFrames to matrices for statistical analysis.
# Advanced Operations on ADF's

Every ADF should support
- Split-apply-combine operations
- Stack/restack - cast/melt operations

**Comment by quinnj** [comment]
I don't think there's anything actionable here anymore.
