### ISSUE TITLE
Proposed interface changes / stop exposing internals

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#517]
We're exporting a lot more functions than I'd like to be when we announce our official interface.

Here's some proposed changes:

**Class 1: Internals we don't need to export**
- AbstractIndex
- Index
- interaction_design_matrix
- PooledDataVecs
- SimpleIndex
- StackedVector
- RepeatedVector
- EachRepeatedVector
- RComplex
- RInteger
- RLogical
- RNumeric
- RList
- RString
- RSymbol
- class
- inherits

**Class 2: Names that are or could be deprecated**
- array
- cbind
- matrix
- merge
- rbind
- subset
- vector
- ncol
- nrow
- vecbind

**Class 3: Names that could be removed entirely**
- clean_colnames!
- dict
- letters
- LETTERS
- range
- reldiff
- rep
- table
- cut
- DataStream
- findat
- nafilter
- naFilter
- nas
- order
- paste
- percent_change

**Class 4: Things that could be renamed**
- pool (Renaming can wait till we create proper factor type)
- pool! (Renaming can wait till we create proper factor type)
- drop_duplicates! (unique!)
- duplicated (nonunique)
- gl (A more explicit name would help)
- load_df (Kill underscores)
- model_response (Is this in StatsBase?)
- xtab (Rename)
- xtabs (Rename)
- stack_df (Kill underscores)
- read_rda, (Kill underscores)
- melt_df (Kill underscores)
- pivot_table (Kill underscores)

**Comment by ararslan** [comment]
Looks like the vast majority of this has been done. Perhaps it should be converted to a checklist so we can track progress on the rest.

**Comment by quinnj** [comment]
I think the backport of DataTables has mostly addressed this; we can open other issues for specific things to stop exporting.

**Comment by nalimilan** [comment]
Wow, it's so nice to see how many functions we've removed since then. I think we still need to do something about `stack_df` and `melt_df`.
