### ISSUE TITLE
Don't access fields of composite types directly

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataFrames.jl#518]
As Toivo argued recently, we shouldn't encourage users to access the fields of composite types directly. In particular, we shouldn't tell people to work with `df.columns` directly.

Instead, this should be part of the effective metadata for a DataFrame:

* `columns(df)`
* `names(df)`
* `types(df)`
* `isnullable(df)`

In particular, this is going to be important if we start allowing users to access columns as `df.colName` since one could have a column called `columns` and we can't let ambiguity slip into our interface.

**Comment by garborg** [comment]
Implemented in #729.
