### ISSUE TITLE
CSV performance

### ISSUE THREAD

**Issue by filmackay** [JuliaStats/DataFrames.jl#530]
Following up from a (incorrect) issue on IJulia, what are the main constraints on performance - starting with `readtable`?

How much is going to be tuning DataFrames, and how much requires improvements in optimization smarts in julia in general?

Coming from Pandas I'm finding the performance is an order higher than what I'm used to - I need to find a solution to this :)

**Comment by quinnj** [comment]
CSV.jl and TextParse.jl are both very fast csv parsing packages. `readtable` has been deprecated. Feel free to open issues at those packages for specific performance issues.
