### ISSUE TITLE
readtable option to parsing only a subset of columns

### ISSUE THREAD

**Issue by diegozea** [JuliaStats/DataFrames.jl#568]
I have a huge table on csv. I want to read it into a Julia's DataFrame. I'm want only 5 of the 85 columns... Being able to select the columns before the parsing will be a huge win on time and space ;)

**Comment by quinnj** [comment]
`readtable` is now deprecated; this is actually a bit of a tricky problem to get right and keep good performance. I've mocked up some design around how to do this and opened https://github.com/JuliaData/DataStreams.jl/issues/40 to track progress for any DataStreams Source implementation to support this generically (including CSV.jl).
