### ISSUE TITLE
PooledDataVecs should have a user-specifiable type parameter allowing 1, 2, 4, or 8-byte levels

### ISSUE THREAD

**Issue by doobwa** [JuliaStats/DataFrames.jl#58]
The motivation: in some instances PooledDataVecs might have many levels (i.e. .more than 65000).  The plan is to automatically convert the refs to Uint32 if we are about to overflow.   One option is to make PooledDataVec a parametric type depending both on the type in the vector but also on the type of the reference, e.g. PooledDataVec{U, T}.

See #55 for a discussion.

**Comment by garborg** [comment]
Closing here. At least partially resolved upstream.
