### ISSUE TITLE
Feature request: Allow  eltypes=[..., Symbol, ...] in readtable

### ISSUE THREAD

**Issue by mkriele** [JuliaStats/DataFrames.jl#584]
Since data frame columns are now indexed with symbols, there is a use case for columns with symbols in order to reference columns of other tables.  (An example would be acolumn vectors with survival probabilities which are stored in another table).  It is possible to store symbols in a data frame. However, using `readtable`  in conjunction with the option `eltypes=[]`  for reading a table with a column containing symbols fails:

```
ERROR: Invalid eltype 'Symbol' encountered.
Valid eltypes: UTF8String, Bool, Float64 or Int64
```

As a work around one could follow  `df=readtable("file.txt")`  with something like 

```
 df[ :surv_col] = [symbol(df[ i, :surv_col]) for i=1:nrow(df)]
```

But it would be nicer to treat `Symbol` just like `UTF8String`, `Bool`, `Float64`,  `Int64`.

**Comment by quinnj** [comment]
`readtable` is deprecated in favor of CSV.jl and should support this.
