### ISSUE TITLE
optionally make AbstractDataVec be like an R factor

### ISSUE THREAD

**Issue by HarlanH** [JuliaStats/DataFrames.jl#6]
There should be a way to enforce a fixed set of pool items in a DV, and to optionally flag the ordering as important. It may also be useful to have meta-data for constrast construction -- or maybe this isn't the appropriate place for it (cf. R).

**Comment by quinnj** [comment]
@nalimilan, is this covered by your work in CategoricalArrays.jl now?

**Comment by nalimilan** [comment]
Yes, it's so old that I'm not even sure what this issue was about.
