### ISSUE TITLE
Add spline modeling

### ISSUE THREAD

**Issue by ianfiske** [JuliaStats/DataFrames.jl#60]
In R, you can add spline bases to the design matrix for a linear model with `y ~ x1 + bs(x2)` to model the variable `x2` as a cubic spline with B-spline basis functions.  I'd like to implement something similar in JuliaData, but I am still trying to figure you where to start.  It looks like we would need 

`function bs(x::DataVec,...)`

but I'm not sure which type it should return... a DataFrame or matrix?

Does this seem like the right approach in general?  I will probably just port the code from the splines library in R over to Julia.

**Comment by quinnj** [comment]
@ararslan, @nalimilan, @kleinschmidt, do we have this functionality in any other repos? DataFrames probably wouldn't be a great home for this at htis point.

**Comment by ararslan** [comment]
There's [SmoothingSplines](https://github.com/nignatiadis/SmoothingSplines.jl), and [Interpolations](https://github.com/JuliaMath/Interpolations.jl) has B-splines. Not sure what's around beyond that, but I agree it shouldn't live in DataFrames. If we need our own implementation it should live in StatsModels.

**Comment by kleinschmidt** [comment]
Or add some glue code.  The design of kleinschmidt/StreamModels.jl is meant to allow for packages to add their own glue code without modifying the base implementation.
