### ISSUE TITLE
readtable escaping options

### ISSUE THREAD

**Issue by garborg** [JuliaStats/DataFrames.jl#672]
I think it's time to expose quote-escaping options to the user (whether the encoding used `""` or `\"` to embed quotes in a quoted string).

Right now it does a pretty good job of handling either encoding, but it can mangle strings slightly (e.g. `"1\\4\6"` => `"1\4\6"`), and valid csvs fail (e.g. `"trailing backslash\"` under quote-escaping or no escaping).

I'm not sure about the API. A couple options:
1) `escapechar`/`quote_escaping` = `:hybrid`, `:backslash`, `:quote`, `:none`, current default `:hybrid`
2) `backslash_escaped` = true, `quote_escaped` = `true`

`1` is more explicit about the default being a generally harmless convenience, `2` fits better with current options, type-wise.

Also, there is be some ambiguity (keyword-wise) with the existing `allowescapes` option for c-style escapes.

Ideas?

**Comment by johnmyleswhite** [comment]
Do we believe there are a lot of hybrid files in the wild? I think we wound up with hybrid because people were annoyed with having to pick an escaping rule explicitly.

**Comment by garborg** [comment]
I don't think there are -- as opposed to the current situation, I'd certainly prefer picking a default and making sure we're helpful with the error message.

**Comment by johnmyleswhite** [comment]
Agreed.

**Comment by quinnj** [comment]
CSV.jl handles setting the `escapechar` and `quotechar` options when reading csv files.
