### ISSUE TITLE
readtable complains about empty file

### ISSUE THREAD

**Issue by LeoK987** [JuliaStats/DataFrames.jl#678]
file test.csv just has header but no content.  readtable output the following errors.  It should better return a df with 0 rows.

julia> df = readtable("test.csv")
ERROR: ArgumentError("Columns and column index must be the same length")
 in DataFrame at /home/xxxx/.julia/DataFrames/src/dataframe/dataframe.jl:34
 in DataFrame at /home/xxxx/.julia/DataFrames/src/dataframe/dataframe.jl:85
 in builddf at /home/xxxx/.julia/DataFrames/src/dataframe/io.jl:627
 in readtable! at /home/xxxx/.julia/DataFrames/src/dataframe/io.jl:746
 in readtable at /home/xxxx/.julia/DataFrames/src/dataframe/io.jl:823
 in readtable at /home/xxxx/.julia/DataFrames/src/dataframe/io.jl:890

**Comment by julian-gehring** [comment]
Let me second @LeoK987's idea for reading in a table with only a header as an empty DataFrame. The current code seems unintuitive in a few cases:

1. A file with only one header column:
```julia
i = IOBuffer("a")
readtable(i, header = true)
```
returns a DataFrame with a variable 'a' of type 'Int64' and 'NA' as an observation.
2. A file with multiple header columns, no other content
```julia
i = IOBuffer("a,b")
readtable(i, header = true)
````
throws an ArgumentError. 
3. Specifying the variable types explicitly
```julia
i = IOBuffer("a,b")
readtable(i, header = true, eltypes = [UTF8String, UTF8String])
```
fails with the same error message.

I understand that there is no way to determine the data type if there is no data. On the other hand, a table structure without data seems perfectly valid, and something that you will often encounter with an automated data import/export. If the types for columns without data would default to 'UTF8String', this should cause little friction.

**Comment by garborg** [comment]
`readtable` clearly needs some work, I'd support a PR making case 1. an error, keeping case 2. an error,  and for case 3., returning a 0-row `DataFrame` with column eltypes matching the user-supplied `eltypes`.

**Comment by ssagaert** [comment]
I just ran into this error with variant number 3 (explicit eltypes) also. I definitely would want to have an emtpy dataframe created also (since an empty input file with just a header is a valid case for my application).

**Comment by samoconnor** [comment]
I just ran into this too.

A `.csv` file with no rows should produce a DataFrame with no rows!

If the column types should be whatever the default would be if the type inference code failed to figure out the type for some other reason. AbstractString?

**Comment by samoconnor** [comment]
My workaround using [Retry.jl](https://github.com/samoconnor/Retry.jl) :

```julia
    @protected try
        foo = readtable("foo_scores.csv")
    catch e
        @ignore if e.msg == "Columns and column index must be the same length"
            foo = DataFrame(Day = Int[], Seconds = Int[], Foo = Int[])
        end
    end
```

_Note that `@protected try` makes this safe in that any exception that does not match the `@ignore if` condition is re-thrown automatically._

**Comment by gustafsson** [comment]
@samoconnor see #891, the unit tests already contain a .csv with a header but no rows. How is your file different?

**Comment by samoconnor** [comment]
```bash
$ julia --version
julia version 0.4.2

$ echo "A,B,C" > test.csv

$ julia -e '@show Pkg.installed("DataFrames") ; using DataFrames ; @show readtable("test.csv")'
Pkg.installed("DataFrames") = v"0.6.10"
ERROR: ArgumentError: Columns and column index must be the same length
 in call at /Users/sam/.julia/v0.4/DataFrames/src/dataframe/dataframe.jl:95
 in builddf at /Users/sam/.julia/v0.4/DataFrames/src/dataframe/io.jl:651
 in readtable! at /Users/sam/.julia/v0.4/DataFrames/src/dataframe/io.jl:783
 in readtable at /Users/sam/.julia/v0.4/DataFrames/src/dataframe/io.jl:847
 in readtable at /Users/sam/.julia/v0.4/DataFrames/src/dataframe/io.jl:893
 in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib

$ echo "1,2,3" >> test.csv

$ julia -e 'using DataFrames ; @show readtable("test.csv")'
readtable("test.csv") = 1x3 DataFrames.DataFrame
| Row | A | B | C |
|-----|---|---|---|
| 1   | 1 | 2 | 3 |
```

**Comment by gustafsson** [comment]
This seems to be fixed in master by now.

```
$ julia -v
julia version 0.4.6

$ echo "A,B,C" > test.csv

$ julia -e '@show Pkg.installed("DataFrames") ; using DataFrames ; @show readtable("test.csv")'
Pkg.installed("DataFrames") = v"0.8.3"
readtable("test.csv") = 0×3 DataFrames.DataFrame

$ echo "1,2,3" >> test.csv

$ julia -e 'using DataFrames ; @show readtable("test.csv")'
readtable("test.csv") = 1×3 DataFrames.DataFrame
│ Row │ A │ B │ C │
├─────┼───┼───┼───┤
│ 1   │ 1 │ 2 │ 3 │
```

**Comment by quinnj** [comment]
CSV.jl handles csv files w/ header, but no rows.
