### ISSUE TITLE
do you want users contribute documentation for spinx/readthedocs?

### ISSUE THREAD

**Issue by floswald** [JuliaStats/DataFrames.jl#680]
hey,
i've seen you setup a sphinx folder to work with readthedocs, with some stuff in it. did you decide on readthedocs/sphinx in the end? if so, great. would you encourage users to write documentation into that folder? some guidelines maybe? 

cheers

**Comment by garborg** [comment]
Closed as answered (and as there are other call-for-doc issues open).
