### ISSUE TITLE
ERROR: readstream not defined

### ISSUE THREAD

**Issue by lojic** [JuliaStats/DataFrames.jl#686]
I'm attempting to process a CSV file in a streaming manner as described here:

http://juliastats.github.io/DataFrames.jl/datastreams.html

Here's the output:

--- snip ---
julia> using DataFrames

julia> ds = readstream("foo.csv")
ERROR: readstream not defined
--- snip ---

I'm running Mac OSX 10.9.4 and Julia 0.3.0

**Comment by garborg** [comment]
Closing (not in the docs any longer).
