### ISSUE TITLE
datasets in the svmlight / libsvm format

### ISSUE THREAD

**Issue by arshak** [JuliaStats/DataFrames.jl#694]
Would it make sense to support the libsvm / svmlight file importing into DataFrames?  Pandas supports sparse dataframes:

http://pandas.pydata.org/pandas-docs/stable/sparse.html

**Comment by achen12** [comment]
QQ, is this a function in the current DataFrame?  Or it hasn't been implemented yet?

**Comment by achen12** [comment]
Seems like we have a loader and dumper written? https://github.com/mblondel/svmlight-loader

**Comment by ararslan** [comment]
It would make more sense to me for that to be a separate package which has DataFrames as a dependency. This may also be relevant for you: https://github.com/simonster/LIBSVM.jl.

**Comment by achen12** [comment]
Understood.  I wrote a quick line for my own use to dump data into libsvm format.  I will check out libsvm.jl as well.  Thanks!
