### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ccsv** [JuliaStats/DataFrames.jl#701]
I want to suggest to update the documentation with some of the following topics

* creating pivot tables
* groupby functions
* I/O hdf5 or SQL files, 
* I/O for excel files (xls and xlsx) files, JSON, and html files
* graphing data
* chunking data
* deleting/appending dataframe or columns
* drop blanks (NAs)

even the `describe()` function does not show up.

**Comment by cgoldammer** [comment]
@johnmyleswhite I'd be excited to take this on. If you're interested, I'd probably start by opening a new issue that lists features that need documenting (the list above is partially outdated).

**Comment by johnmyleswhite** [comment]
@cgoldammer: Please do.

**Comment by garborg** [comment]
Discussion moved to #775.
