### ISSUE TITLE
Selection of rows whose elements take on certain values

### ISSUE THREAD

**Issue by joshjob42** [JuliaStats/DataFrames.jl#721]
I often want to restrict my large dataset to some smaller subset, where that set is determined by a particular list of values. The only way to do so that I could see is with some horrible chain of things like

``` julia
goodrows = df[:key1].==val1 || df[:key1].==val2...
goodrows = goodrows && (df[:key2].==val1 || df[:key2].==val2)...
littledf = df[goodrows,:]
```

etc.

This was unbearable, so I wrote this little function:

``` julia
function restrict(df, dict)
    keylist=[x for x in keys(dict)]
    goodidx=ones(Bool,size(df,1))
    for key in keylist
        if (typeof(dict[key])=="ASCIIString") || (typeof(dict[key])=="UTF8String")
            vals = [dict[key]]
        else
            vals=dict[key]
        end
        littlegoodidx=zeros(Bool,size(df,1))
        for val in vals
            littlegoodidx |= (df[key].==val)
        end
        goodidx &= littlegoodidx
    end
    return df[goodidx,:]
end
```

This lets you index on keys, so the above would be

``` julia
littledf = restrict(df,[:key1=>[val1,val2...],:key2=>[val1,val2...]])
```

Since I use this function a bajillion times a day, I thought I might ask if a) this function should be included in the DataFrames package and b) if I'm just stupid and something like this already exists and simply isn't well documented.

**Comment by quinnj** [comment]
I think this is probably a unique enough case to not warrant something in this package itself. Your `restrict` function seems fine for a limited case, or @tshort's solution using `findin` is about as concise.
