### ISSUE TITLE
return Bool and PooledDataVec to read_table

### ISSUE THREAD

**Issue by HarlanH** [JuliaStats/DataFrames.jl#75]
I'd suggest using a Dict to store unique items for each column during the first pass. If the number of unique items in a column exceeds 2^8, stop storing for that column. If the column ends up having a string type and not too many items, use the Dict to seed a PDV for the second pass. If the column ends up being either integral with only 0/1/(NA), or string with only T/F/(NA) or TRUE/FALSE(NA) or similar, make the column a Bool.

**Comment by garborg** [comment]
Superseded by other IO issues.
