### ISSUE TITLE
vcat fails when trying to append non NA values to a NA column

### ISSUE THREAD

**Issue by romainFr** [JuliaStats/DataFrames.jl#758]
Not sure if it's the expected behavior (this used to work with rbind), but here is how it looks in a minimal example :  

```julia
df = DataFrame(A = NA, B = 2)
df2 = DataFrame(A = 4, B = 3)
vcat(df,df2)

`convert` has no method matching convert(::Type{Int64}, ::NAtype)
while loading In[49], in expression starting on line 3

 in copy! at /home/juser/.julia/v0.3/DataArrays/src/dataarray.jl:187
 in copy! at /home/juser/.julia/v0.3/DataArrays/src/dataarray.jl:156
 in vcat at /home/juser/.julia/v0.3/DataFrames/src/abstractdataframe/abstractdataframe.jl:333
 in vcat at /home/juser/.julia/v0.3/DataFrames/src/abstractdataframe/abstractdataframe.jl:319
```

In julia 3.4, with DataFrames 0.6.0 (same thing with the checkout version).

(And sorry if it's a duplicate, but I couldn't find anything related to it).

**Comment by garborg** [comment]
Related to JuliaStats/DataArrays.jl#134.

Also related to the ongoing discussion about whether DataFrame assignment should be broadcasting scalars at all (the inconsistency required to work around this would another argument against broadcasting, except that `NA`s and `DataArray`s are going to be replaced by `NullableArray`s soon).

See my post on [this julia-users thread](https://groups.google.com/forum/#!topic/julia-users/piCb9m7lUmE) for explanation and workarounds. As noted in the links, this may not get a ton of attention ATM as most interested developers are figuring out `NullableArray`s.

**Comment by gustafsson** [comment]
I don't think missing values (NA or nullable) values should affect the type of a column. I created a PR with my suggested solution: https://github.com/JuliaStats/DataFrames.jl/pull/889
