### ISSUE TITLE
sort! error on latest dataframe 0.6.1 update.  ERROR: defalg not defined

### ISSUE THREAD

**Issue by disleyland** [JuliaStats/DataFrames.jl#768]
the latest dataframe update 0.6.1 is throwing up an error on some sort! commands.
location: .julia/v0.3/DataFrames/src/dataframe/sort.jl:8

**Comment by axsk** [comment]
+1
LoadError: UndefVarError: defalg not defined in sort! at C:\cygwin64\home\Alex\.julia\v0.4\DataFrames\src\dataframe\sort.jl:8

**Comment by garborg** [comment]
Thanks for the report, you two!

**Comment by disleyland** [comment]
no problem.  is there a temporary manual fix or a new release put out soon?

**Comment by garborg** [comment]
Since the fix is committed here, if you run `Pkg.checkout("DataFrames")`, you'll have a version that includes the fix. There should be a new release soon, but likely after resolving a couple other issues.

**Comment by disleyland** [comment]
thanks.

**Comment by disleyland** [comment]
btw, is this error part of the other issues to be resolved.  seems its another sort! issue:

ERROR: `isless` has no method matching isless(::Symbol, ::UTF8String)

 in sort! at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib (repeats 9 times)
 in sort at sort.jl:342
 in PooledDataVecs at /Users/me/.julia/v0.3/DataArrays/src/pooleddataarray.jl:686
 in join at /Users/me/.julia/v0.3/DataFrames/src/abstractdataframe/join.jl:141
