### ISSUE TITLE
read_rda throws TypeError in GZip module

### ISSUE THREAD

**Issue by axsk** [JuliaStats/DataFrames.jl#770]
``` julia
using DataFrames
read_rda("some.rda")
```

throws 
`LoadError: TypeError: readnchars: in typeassert, expected ASCIIString, got UTF8String
 in gzopen at C:\cygwin64\home\Alex\.julia\v0.4\GZip\src\GZip.jl:253`

on current Julia 0.4.0-dev and Windows 8.
I am not sure whether this is a GZip or DataFrames issue, as I didn't get any further backtrace then the given :(

**Comment by kmsquire** [comment]
This does look to be an issue in DataFrames.  Do you have a test file that you could provide?

It looks like the error is here: https://github.com/JuliaStats/DataFrames.jl/blob/50a87c89e2ee56ee7de7193c1f2680f68680a876/src/RDA.jl#L166

I think the easiest fix would be to replace most uses of `ASCIIString` with `UTF8String` in types and with `String` in function call signatures in this file.  [These lines](https://github.com/JuliaStats/DataFrames.jl/blob/50a87c89e2ee56ee7de7193c1f2680f68680a876/src/RDA.jl#L192-L197) will also have to be modified to either use `sizeof` or look at the length of the underlying array, as `length` on `UTF8Strings` counts characters, not bytes.


Cc: @garborg @alyst

**Comment by alyst** [comment]
Yes, it would be nice to have the test RDA file.

Besides potential performance/memory implications, substituting most of ASCII with UTF8 would be a way to go. However, some of the strings in RDA format are ASCII-only, so ASCII-reading methods should stay.

**Comment by johnmyleswhite** [comment]
What does ASCII-only mean? ASCII is a strict subset of UTF-8. Do you mean Latin-1?

**Comment by alyst** [comment]
I have meant that according to R sources, CHARSXP R objects could be in "native", "bytes", "latin1" and "utf8" encoding, as specified by its flags. Currently reading the encoding flag is not supported by `RDA.jl`.
Potentially, strings could also be the names of Namespace and Packages and Builtin objects, but that strings have no encoding attribute, so they should be "latin1" then.
Should "latin1" strings optimally be stored in ASCIIString or it doesn't matter?

**Comment by johnmyleswhite** [comment]
@garborg should have the final decision, but that suggests to me that we should re-encode everything to UTF-8 or throw an error for unsupported encodings.

Personally, I think it's important we never return an `ASCIIString` vector. That breaks human-level type inference.

**Comment by garborg** [comment]
Unless a new child of `DirectIndexString` is implemented (outside of `DataFrames`) with methods that work all the places the `ASCIIString` methods assume bytes are below `0x80`, we should follow one of the two paths John suggested.

**Comment by joermungandr** [comment]
Is it planned to fix this issue? :-)

**Comment by alyst** [comment]
@joermungandr If you can provide any RData file that triggers this exception, it would be nice.

**Comment by quinnj** [comment]
`read_rda` has been deprecated.
