### ISSUE TITLE
readtable separator parameter only accepts single quotes

### ISSUE THREAD

**Issue by Mokubyow** [JuliaStats/DataFrames.jl#777]
Is there a reason the separator parameter only accepts single quotes and not double quotes? 

This doesn't work:
readtable("~/file", separator = "\t")

This work:
readtable("~/file", separator = '\t')

**Comment by johnmyleswhite** [comment]
Because single quotes and double quotes aren't ever exchangeable in Julia since they produce different types.

There's an existing issue that contains the arguments for allowing strings as arguments.

**Comment by nalimilan** [comment]
Yes, this is https://github.com/JuliaStats/DataFrames.jl/pull/774.

**Comment by Mokubyow** [comment]
Interesting thanks for the response
