### ISSUE TITLE
Docile error prevents loading of DataFrames

### ISSUE THREAD

**Issue by ViralBShah** [JuliaStats/DataFrames.jl#783]
ERROR: LoadError: ArgumentError: Docile not found in path
 in require at ./loading.jl:49
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /Users/viral/.julia/v0.4/DataFrames/src/DataFrames.jl, in expression starting on line 16

**Comment by garborg** [comment]
Looks like `Docile` is in the `REQUIRE`.  I just pulled down DataFrames master and `using DataFrames` works for me on 0.4, but maybe because I already had Docile -- would `Pkg.resolve()` help?

**Comment by ViralBShah** [comment]
`Pkg.resolve()` updated Docile and fixed it. 

Thanks. Cc: @aviks

**Comment by garborg** [comment]
Great!
