### ISSUE TITLE
save 

### ISSUE THREAD

**Issue by prezaei85** [JuliaStats/DataFrames.jl#790]
function save has a conflict with the same function in the package HDF5. As that package is basically the one to save things, should the save function here be reconsidered?
```
julia> using DataFrames

julia> methods(save)
# 1 method for generic function "save":
save(filename::String,df::DataFrame) at /Users/prezaei/.julia/v0.3/DataFrames/src/dataframe/io.jl:989

julia> using HDF5, JLD
Warning: imported binding for DL_LOAD_PATH overwritten in module BinDeps
Warning: using JLD.save in module Main conflicts with an existing identifier.
```

**Comment by simonster** [comment]
We should probably get rid of `save` in this package. `serialize` was never intended as a file format; the format changes between Julia releases; and `deserialize` may fail when types change.

**Comment by johnmyleswhite** [comment]
+1 to removing save

**Comment by garborg** [comment]
Agreed.
