### ISSUE TITLE
Feature request: Options to turn NAs into blanks when exporting

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/DataFrames.jl#792]
Right now when exporting a DataFrame with writetable any missing values show up in a csv as 

>...1,2,NA,4,...

it would be very nice to be able to specify that any NAs should be left blank so that the output looks like

>...1,2,,4,...

In particular this would help people who want to open up the output in a program like LibreOffice Calc or Excel.  This is somewhat non-trivial because writetable currently relies on printtable however, and I'm not sure what the best way to implement this without making a copy of the datatable at some point.

**Comment by nalimilan** [comment]
You could add a `nastring` argument to `printtable`, and check for `NA`s in the loop to change the representation. Then `writetable` would accept `nastring` and pass it over to `printtable`.

**Comment by amellnik** [comment]
Seems fairly straightforward, I'll see if I can figure out how to pull the code and make my first big-kid commit in the next few days.

**Comment by garborg** [comment]
Closed by #794.
