### ISSUE TITLE
NA undefined when converting an array to DataFrame

### ISSUE THREAD

**Issue by prezaei85** [JuliaStats/DataFrames.jl#796]
Is there a workaround for this problem? 
```
julia> x = rand(2,2)
2x2 Array{Float64,2}:
 0.514146  0.325186
 0.87831   0.38223 

julia> using DataFrames

julia> y = convert(DataFrame, x)
2x2 DataFrame
| Row | x1       | x2       |
|-----|----------|----------|
| 1   | 0.514146 | 0.325186 |
| 2   | 0.87831  | 0.38223  |

julia> y[2,2] = NA
ERROR: `convert` has no method matching convert(::Type{Float64}, ::NAtype)
 in setindex! at array.jl:307
 in insert_single_entry! at /Users/prezaei/.julia/v0.3/DataFrames/src/dataframe/dataframe.jl:313
 in setindex! at /Users/prezaei/.julia/v0.3/DataFrames/src/dataframe/dataframe.jl:411
```

**Comment by garborg** [comment]
The original matrix is not a `DataMatrix` (doesn't allow NAs), so the converted columns are not `DataVector`s. If you want to change a column container type post-construction,`nullable!` works:

```julia
nullable!(y, 2)
2x2 DataFrames.DataFrame
| Row | x1       | x2       |
|-----|----------|----------|
| 1   | 0.537453 | 0.363671 |
| 2   | 0.922684 | 0.778638 |

julia> y[2,2] = NA
NA

julia> nullable!(y, :x1)
2x2 DataFrames.DataFrame
| Row | x1       | x2       |
|-----|----------|----------|
| 1   | 0.537453 | 0.363671 |
| 2   | 0.922684 | NA       |

julia> y[1,1] = NA
```

Related: some DataFrames functions are hardcoded with the assumption that columns are `AbstractDataArrays`, but that will be fixed soon.

**Comment by prezaei85** [comment]
Thanks for your clarification. Do you know if there is any efficiency gain/loss in using a `DataMatrix` instead of a `Matrix` when using a large `DataFrame`? For example in the above case but assuming that this is a much larger dataset?

**Comment by nalimilan** [comment]
@prezaei85 Using a `DataMatrix` instead of a plain `Matrix` can incur all sorts of costs due to 1) storing 1 bit more for each entry to keep track of whether it's `NA` or not, and 2) handling potential `NA` values in the various algorithms.
