### ISSUE TITLE
any one else seeing the Sort function overloading latest julia? 

### ISSUE THREAD

**Issue by disleyland** [JuliaStats/DataFrames.jl#798]
i'm getting a problem with the humble sort function in the latest update.  sort(dataframe, cols=:symbol) is sending julia into a 100% CPU state which it never seems to get out of.  stripped down a big dataframe to 600k rows and 2 columns to see if this might be the problem, same thing.  takes ages doing something, and i have to manually kill the julia process.  

I'm on OS X Julia 0.3.8

**Comment by nalimilan** [comment]
Would you be able to provide a self-reproducible example, either with toy data or by posting real data somewhere?

**Comment by disleyland** [comment]
here's an illustrative example.

using DataFrames
df = DataFrame()
df[:ID] = [string("ID",rand(1000:9999)) for a in 1:700000]
df[:YEAR] = [rand(1980:2015) for a in 1:700000]
@time sort(df,cols=:ID)
elapsed time: 203.022825049 seconds (85088716616 bytes allocated, 98.76% gc time) !!

if you sort by the Int64 column, its faster, but really these times and the bytes load seem crazy to what it used to be.
elapsed time: 127.706580658 seconds (85135077384 bytes allocated, 97.34% gc time)

on dataframe with real data, time is measured in hours :(

**Comment by disleyland** [comment]
same test on second computer that hasn't been updated for a little while (e.g., Julia 0.3.7, DataFrames 0.6.2), 
@time sort(df,cols=:ID)
elapsed time: 3.960193315 seconds (114918976 bytes allocated, 8.95% gc time).  where is all this memory allocation coming from in recent update?

**Comment by garborg** [comment]
@disleyland Traced to JuliaLang/SortingAlgorithms.jl#11, but I don't have time to dig -- please follow along or jump in there.

**Comment by nalimilan** [comment]
Performance is good again on Julia 0.5 with latest master.
