### ISSUE TITLE
dropUnusedLevels! throws ErrorException("type cannot be constructed") because of Uint8 conversion in julia 0.3.8 

### ISSUE THREAD

**Issue by adamlabadorf** [JuliaStats/DataFrames.jl#808]
Hi,

I encountered an error in statsmodels/formulas.jl:dropUnusedLevels! when using pooled data arrays in julia 0.3.8 (output from IJulia here):

type cannot be constructed
while loading In[45], in expression starting on line 4

 in map at abstractarray.jl:1328
 in dropUnusedLevels! at /usr3/graduate/labadorf/.julia/v0.3/DataFrames/src/statsmodels/formula.jl:230
 in ModelFrame at /usr3/graduate/labadorf/.julia/v0.3/DataFrames/src/statsmodels/formula.jl:240
 in fit at /usr3/graduate/labadorf/.julia/v0.3/DataFrames/src/statsmodels/statsmodel.jl:52
 in glm at /usr3/graduate/labadorf/.julia/v0.3/GLM/src/glmfit.jl:228
 in anonymous at no file:9

This issue is caused by the line 230:

dict = Dict(su, map(T, 1:length(uu)))

where T::Uint8 and Uint8(x::Int64) is not supported. If I change this line to

dict = Dict(su, map(x -> convert(T,x), 1:length(uu)))

the issue seems to be resolved. In julia 0.4.0 this error does not occur, as Uint8(x::Int64) is now supported. My proposed fix using convert works on both 0.3.8 and 0.4.0. I haven't forked the repo to test this or generate a pull request, if you agree this fixes the issue should I do that?

Thanks.

**Comment by dmbates** [comment]
Sounds good to me.  I too had encountered the problem but hadn't yet taken the time to investigate.  Thanks for looking into this.

**Comment by ararslan** [comment]
The Julia 0.3 release series is no longer supported by DataFrames. As you said, this works as expected in Julia 0.4, which is currently the minimum required version for the package, which mean this issue no longer applies.
