### ISSUE TITLE
Question: How to omit quotemark for writetable?

### ISSUE THREAD

**Issue by abieler** [JuliaStats/DataFrames.jl#811]
I tried Char[] as with readtable but get an error and '' (two single quotes) is invalid in julia.

**Comment by johnmyleswhite** [comment]
Are you sure this is a thing you want to do? We don't support writing files without quotemarks because some DataFrames would generate corrupt data as a result.

**Comment by abieler** [comment]
Me personally I really would like this, but I can understand your argument.
Not a big deal if it is not there. Just wanted to check if I am missing it.

**Comment by johnmyleswhite** [comment]
At first I was thinking to implement it, but it would make things too brittle in my mind. You can only do this safely if you promise that your data never contains the end-of-column delimiter or the end-of-row delimiter. A single string containing a `\n` kills your parser's ability to read back the file you just wrote out.

Obviously a judgment call, but I think a defensible way in the interest of safety.

**Comment by abieler** [comment]
I have to say this is coming back as an "issue" in my daily life over and over again. Especially when providing csv files to people with limited computer skills. They complain a lot about quotemarks as apparently a lot of software packages cannot handle this properly..
Any chance omitting quotes can be an option still? :) --> under the disclaimer that if people wanna do this it is on their own to make sure it is save to use..

**Comment by nalimilan** [comment]
Have a look at the CSV.jl package. It looks like the CSV support will use that at some point, instead of the current implementation. Better file an issue there.

**Comment by cossio** [comment]
I support this idea. I also need to get rid of quotemarks.

**Comment by davidanthoff** [comment]
Another option is to use the [FileIO.jl](https://github.com/JuliaIO/FileIO.jl) integration provided by [CSVFiles.jl](https://github.com/davidanthoff/CSVFiles.jl):
````julia
using DataFrames, FileIO

df = ... # Get your DataFrame

save("data.csv", df, quotechar=nothing)

# Or you can use the pipe syntax
df |> save("data.csv", quotechar=nothing)
````

This will work with the more than a dozen table types that [IterableTables.jl](https://github.com/davidanthoff/IterableTables.jl) integrates, not just ``DataFrame``s.
