### ISSUE TITLE
`by` has no method matching by(::DataFrame, ::Symbol, ::Function)

### ISSUE THREAD

**Issue by bramsdenteuling** [JuliaStats/DataFrames.jl#812]
I get this error when I follow the instructions of by. 

```
using RDatasets, DataFrames
iris = dataset("datasets", "iris")
by(iris, :Species, size)
```

**Comment by tshort** [comment]
That works for me in Julia 0.3.9 and DataFrames 0.6.6. What's your version of Julia and DataFrames? Are your packages updated?

**Comment by bramsdenteuling** [comment]
I use DataFrames 0.6.6 and Julia 0.3.7.
After restarting it started working.
