### ISSUE TITLE
Error while reading csv

### ISSUE THREAD

**Issue by ararog** [JuliaStats/DataFrames.jl#814]
I'm trying to read the csv contained in the following zip archive:

https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip

But I'm always getting the following error:

ERROR: LoadError: TypeError: readtable: in typeassert, expected Char, got ASCIIString
 in anonymous at no file:48
 in include at ./boot.jl:253
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:312
 in _start at ./client.jl:412

**Comment by johnmyleswhite** [comment]
Sounds like you've written something like `"\n"` where you needed to write something like `'\n'`. Can you post the exact code you're running? We probably don't actually need to see the data you're using.

**Comment by ararog** [comment]
Don't worry john, you got the point, i made this change and everything worked as expected.

**Comment by johnmyleswhite** [comment]
Glad to have helped.
