### ISSUE TITLE
ModelFrame and SubDataFrame

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/DataFrames.jl#818]
It seems like regressors are duplicated twice before fitting a linear model - once to return a `ModelFrame`, once to return a `ModelMatrix`.

Could [ModelFrame](https://github.com/JuliaStats/DataFrames.jl/blob/master/src/statsmodels/formula.jl#L237) return a `SubDataFrame` rather than a deep copy of the original `DataFrame`? 
One way to do that would be to replace `df[complete_cases(df)]` by `sub(df, complete_cases(df))` and move the `dropUnusedLevel` to `ModelMatrix`?

**Comment by kleinschmidt** [comment]
I noticed the same thing, and I don't see any reason why not.  Probably want to restrict to the columns that are actually required to generate the `ModelMatrix` (the `etrms` field of the `Terms`).

**Comment by kleinschmidt** [comment]
(and evaluate `complete_cases` with respect to only those columns, too)

**Comment by nalimilan** [comment]
+1

**Comment by johnmyleswhite** [comment]
I'm also in favor of this.

Any chance some of you will be at JuliaCon? I'd love to just sit down with all of the stakeholders and decide on the definitive semantics for transforming DataFrames into matrices.

**Comment by nalimilan** [comment]
Sorry, I won't be there (but I haven't really thought about this issue so I'm not sure I would have been very helpful anyway...).

**Comment by kleinschmidt** [comment]
I won't either, unfortunately.  I'd love to skype into a meeting if you end up getting a quorum though.

**Comment by johnmyleswhite** [comment]
Maybe we should set up a Skype meeting post JuliaCon instead?

**Comment by kleinschmidt** [comment]
Sure! Let me know when would work, my schedule is pretty open in the summer.

**Comment by johnmyleswhite** [comment]
How about tentatively setting a meeting for sometime on July 15th? That gives us plenty of room to organize.

**Comment by kleinschmidt** [comment]
👍

**Comment by matthieugomez** [comment]
So for now, ModelMatrix(ModelFrame()) does 3+ copies of the data:
- once in ModelFrame via `na_omit`
- twice in ModelMatrix:  1 in `cols` (to convert to `Vector{Float64}`), once in `hcat` (to create the matrix).
In case of interactions, even more copies are created (in `expandcols`).

It would be great to do only one copy. It's probably best to wait Julia 0.5 to tackle this. Not an emergency — the `ModelMatrix(ModelFrame())` call is already much faster than R (no idea why R is so slow for such an important function).

**Comment by quinnj** [comment]
Feel free to re-open at https://github.com/JuliaStats/StatsModels.jl is this is still an issue.

**Comment by nalimilan** [comment]
@kleinschmidt has experimented a non-copying approach in https://github.com/kleinschmidt/StreamModels.jl too.
