### ISSUE TITLE
Missing operators for PooledDataArray?

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/DataFrames.jl#820]
Both & and | work for DataArrays but not for PooledDataArrays.  Is this intentional or were they just left out somewhere?

    using DataFrames
    df = DataFrame(A=[1,1,1,1,0,1], B=["a","a","a","b","c","c"])
    df2 = df[(df[:B].=="a")|(df[:B].=="c"),:] #Works

    df[:B] = pool(df[:B])
    df2 = df[(df[:B].=="a")|(df[:B].=="c"),:] #Dies

    `|` has no method matching |(::PooledDataArray{Bool,Uint8,1}, ::PooledDataArray{Bool,Uint8,1})
while loading In[6], in expression starting on line 2

**Comment by johnmyleswhite** [comment]
This was probably just left out after we removed most of the other operators for PDA's.

I would be open to fixing this, but NullableArrays are being actively worked on now, so I have no intention to support DataArrays for more than a few more weeks. Once NullableArrays lands, we'll be completely removing the idea of PDA's and replacing them with NullableArrays with scalar categorical entries.

**Comment by nalimilan** [comment]
Closing now that we no longer use DataArrays.
