### ISSUE TITLE
Intermittent crashes when working with large DataFrames

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/DataFrames.jl#822]
I've posted this here as a start, although I'm not convinced that it has anything in particular to do with DataFrames (it's just the only way I observe it).  

I'm having intermittent crashes when performing various operations on large dataframes.  When this happens, if I restart the kernel and run the same code again, it works.  The error message that is printed to the kernel is not very illuminating; a typical one is below.  (The first line repeats a very large number of times, not shown here)

...
jl_profile_is_running at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjuli
a.dll (unknown line)
jl_gc_collect at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll (u
nknown line)
allocobj at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll (unknow
n line)
apply_scale_typed! at C:\Users\amellnik\.julia\v0.3\Gadfly\src\scale.jl:297
jlcall_apply_scale_typed!_4271 at  (unknown line)
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
apply_scale at C:\Users\amellnik\.julia\v0.3\Gadfly\src\scale.jl:256
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
jl_f_apply at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll (unkn
own line)
apply_scales at C:\Users\amellnik\.julia\v0.3\Gadfly\src\scale.jl:39
apply_scales at C:\Users\amellnik\.julia\v0.3\Gadfly\src\scale.jl:59
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
jl_f_apply at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll (unkn
own line)
render at C:\Users\amellnik\.julia\v0.3\Gadfly\src\Gadfly.jl:692
writemime at C:\Users\amellnik\.julia\v0.3\Gadfly\src\Gadfly.jl:884
jlcall_writemime_4080 at  (unknown line)
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
jl_f_apply at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll (unkn
own line)
sprint at iostream.jl:229
display_dict at C:\Users\amellnik\.julia\v0.3\IJulia\src\execute_request.jl:28
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
execute_request_0x535c5df2 at C:\Users\amellnik\.julia\v0.3\IJulia\src\execute_r
equest.jl:196
jlcall_execute_request_0x535c5df2_1611 at  (unknown line)
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
eventloop at C:\Users\amellnik\.julia\v0.3\IJulia\src\IJulia.jl:123
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
anonymous at task.jl:340
jl_handle_stack_switch at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjul
ia.dll (unknown line)
julia_trampoline at C:\Users\amellnik\AppData\Local\Julia-0.3.9\bin\libjulia.dll
 (unknown line)
unknown function (ip: 4202784)
unknown function (ip: 4199370)
unknown function (ip: 4199672)
BaseThreadInitThunk at C:\windows\system32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\windows\SYSTEM32\ntdll.dll (unknown line)
RtlUserThreadStart at C:\windows\SYSTEM32\ntdll.dll (unknown line)
[I 15:02:40.927 NotebookApp] KernelRestarter: restarting kernel (1/5)

Because this is intermittent, I can't figure out any way to reproduce it reliably.  As a very rough indicator of frequency I've seen it about ten times in the last two days of working reasonably consistently.  It might be windows specific.  Does anyone have any idea what this might be related to, or anything I should check to help debug it?

**Comment by johnmyleswhite** [comment]
If you can shrink this to a test case, we might be able to help. As is, it's going to be really to debug something that's failing within Julia's C functions.

**Comment by amellnik** [comment]
Unfortunately I can't share the data set / code I'm working on, but I'll see if I can reproduce it using large random data frames or similar, and will report here if I can manage it.

**Comment by johnmyleswhite** [comment]
That would be great.

**Comment by amellnik** [comment]
Unable to reproduce, closing.
