### ISSUE TITLE
concat DataFrameRow's to DataFrame

### ISSUE THREAD

**Issue by emilbayes** [JuliaStats/DataFrames.jl#846]
I have a dataset of names for the last 116 years, that I've ranked for each year in a `PriorityQueue{DataFrameRow,Float64}`. I'd like to export each `PriorityQueue` as a `DataFrame` but can't seem to find much information or code about `DataFrameRow`s. Is it possible to `vcat` `DataFrameRow`s or similar to construct a `DataFrame` that I can write to disk using `writetable`?

I've included my code for reference:

```julia
using DataFrames
using Base.Collections

names = readtable("all_names_normed.csv", makefactors = true)

# Create indexes for years 1900..2015, in descending order (reverse)
ranks = Dict{Int, PriorityQueue}([year => PriorityQueue{DataFrameRow,Float64}(Base.Order.Reverse) for year=1900:2015])

# Put each data row in the appropriate year rank, if it had any occurrences that year
for row in eachrow(names)
  if(row[:count] > 0)
    enqueue!(ranks[row[:year]], row, row[:count])
  end
end

for (year, rank) in ranks
  # rank.xs is the PriorityQueue type's internal array of all entries sorted by priority
  rank.xs
  # ?
end
```

**Comment by alyst** [comment]
At the moment ```DataFrameRow``` is essentially a reference to a ```DataFrame``` and a row index, it doesn't store any data by itself. So in your case it would be even more efficient to store just the row indices instead of ```DataFrameRow``` objects. You can compose a new data frame with the proper ordering by ```names[ordered_row_indices,:]```.
Alternatively you may use ```by(df, :year) do subdf ... end``` to group the data by year and then reorder each subframe by name rank. It should save you a few lines.

**Comment by alyst** [comment]
I don't think there are plans to use ```DataFrameRow``` in the way you propose, so I'll close the issue.

**Comment by johnmyleswhite** [comment]
I think it would be reasonable to allow calling `append!` with a `DataFrameRow` as an argument.

**Comment by alyst** [comment]
I had seen people waiting hours for the data frame construction in R: they were adding row by row in a loop. Of course, in Julia even that code pattern would be much more efficient, but there are already much better ways to do the same thing.
