### ISSUE TITLE
julia-dev broke function documentation

### ISSUE THREAD

**Issue by vchuravy** [JuliaStats/DataFrames.jl#852]
Current master seems to have broken the way DataFrames annotates its functions

Versioninfo:
````
julia> versioninfo()
Julia Version 0.4.0-dev+6693
Commit c61cd8b (2015-08-13 00:28 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.6.2
````

Error message:
````
ERROR: LoadError: LoadError: Invalid doc expression [:rename!,:rename]
while loading /home/wallnuss/.julia/v0.4/DataFrames/src/abstractdataframe/abstractdataframe.jl, in expression starting on line 167
while loading /home/wallnuss/.julia/v0.4/DataFrames/src/DataFrames.jl, in expression starting on line 79
````

**Comment by vchuravy** [comment]
Seems to be JuliaLang/julia@61f85adb3177791a78f00d2cfd07fbdbf9d85923

**Comment by alyst** [comment]
Thanks for reporting!
It's not obvious for me what is the proper way to document multiple functions at once.
Could you please also report the issue upstream, so that the devs are aware that this change is breaking packages?

**Comment by vchuravy** [comment]
It might be easier to just ping @one-more-minute

**Comment by one-more-minute** [comment]
It's actually a good thing this came up, since before you were just documenting the array `[:rename!,:rename]` in 0.4 (I think that syntax is supported by Docile, which is probably why you were using it).

Feel free to open an issue about this and we can discuss syntax for documenting multiple things at once.

**Comment by MichaelHatherly** [comment]
Until a decision is made in https://github.com/JuliaLang/julia/issues/12615 you can disable the docstring in 0.4 by appending a ``;`` to the end of it, ie.

```jl
"...";
[a, b]
```

It'll still work fine in 0.3 with Docile.

**Comment by vchuravy** [comment]
julia-dev now provides syntax for documenting multiple function definitions [1]. Altough I don't know whether that is backwards compatible to 0.3 

https://github.com/JuliaLang/julia/commit/a7cd5904118a14bc2840d79a1ad2bbbdb5f82e4c

**Comment by MichaelHatherly** [comment]
The syntax is also supported in Docile as of ``0.5.16``, tagged yesterday.

Quoted symbols such as ``[:rename!, :rename]`` will need to be changed to ``[rename!, rename]`` and moved to after their definitions. Otherwise the following kind of thing happens:

```
julia> "..."
       :foo, :bar
  ...

julia> Main.__META__
ObjectIdDict with 3 entries:
  :foo                     => Base.Markdown.MD(Any[Base.Markdown.Paragra…
  :bar                     => Base.Markdown.MD(Any[Base.Markdown.Paragra…
  #= circular reference =# => Base.Markdown.MD(Any[Base.Markdown.Paragra…
```

The quoted form can only be supported in Docile because it looks for docstrings after the module has be loaded rather than during macro expansion like ``@doc`` does.

**Comment by protogeezer** [comment]
I cloned the package from github hoping to get around this to allow me to continue testing/working with 0.4-dev - but I'm still seeing the problem..

et-imac-retina:julia sjbespa$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6787 (2015-08-17 18:41 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 72431c5 (0 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using DataFrames
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/Docile.ji for module Docile.
ERROR: LoadError: LoadError: Invalid doc expression [:rename!,:rename]
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in anonymous at no file:110
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in require at ./loading.jl:205
while loading /Users/sjbespa/.julia/v0.4/DataFrames/src/abstractdataframe/abstractdataframe.jl, in expression starting on line 167
while loading /Users/sjbespa/.julia/v0.4/DataFrames/src/DataFrames.jl, in expression starting on line 79

Can I do anything to either properly download the latest DataFrames.jl or help you figure out what's up?

Stephen

**Comment by alyst** [comment]
@protogeezer The head of the master branch has a fix for a few days already. `Pkg.checkout("DataFrames")` would switch your copy to that revision.
Actually, the new version of the package should be tagged very soon, so you don't need to bother with the "master" at all, just make sure you have the recent build of julia 0.4dev.

**Comment by protogeezer** [comment]
Thanks! I totally missed the difference between clone and checkout...
