### ISSUE TITLE
unstack example in doc not working

### ISSUE THREAD

**Issue by anriseth** [JuliaStats/DataFrames.jl#854]
I'm struggling with unstack on Julia 0.3.12-pre+3, DataFrames 0.6.8.

I get the error
``` julia
ERROR: `convert` has no method matching convert(::Type{Float64}, ::ASCIIString)
 in setindex! at /home/asbjorn/.julia/v0.3/DataArrays/src/indexing.jl:261
 in unstack at /home/asbjorn/.julia/v0.3/DataFrames/src/abstractdataframe/reshape.jl:187
 in unstack at /home/asbjorn/.julia/v0.3/DataFrames/src/abstractdataframe/reshape.jl:192
```
when running the following code from the documentation:
``` julia
using DataFrames, RDatasets
iris = dataset("datasets", "iris")
iris[:id] = 1:size(iris, 1) 
longdf = melt(iris, :id)
widedf = unstack(longdf, :id, :variable, :value)
```

**Comment by amellnik** [comment]
I had a hard time following that example, and would suggest something a bit easier to follow like

    df = DataFrame(
    Fish = ["Bob", "Bob", "Batman", "Batman", "Suzy"], 
    Key = ["Mass", "Color", "Mass", "Color", "Color"], 
    Value = ["12 g", "Red", "18 g", "Grey", "Silver"])

<table class="data-frame"><tr><th></th><th>Fish</th><th>Key</th><th>Value</th></tr><tr><th>1</th><td>Bob</td><td>Mass</td><td>12 g</td></tr><tr><th>2</th><td>Bob</td><td>Color</td><td>Red</td></tr><tr><th>3</th><td>Batman</td><td>Mass</td><td>18 g</td></tr><tr><th>4</th><td>Batman</td><td>Color</td><td>Grey</td></tr><tr><th>5</th><td>Suzy</td><td>Color</td><td>Silver</td></tr></table>

    unstack(df, :Key, :Value)

<table class="data-frame"><tr><th></th><th>Fish</th><th>Color</th><th>Mass</th></tr><tr><th>1</th><td>Bob</td><td>Grey</td><td>18 g</td></tr><tr><th>2</th><td>Batman</td><td>Red</td><td>12 g</td></tr><tr><th>3</th><td>Suzy</td><td>Silver</td><td>NA</td></tr></table>

**Comment by tshort** [comment]
In @amellnik's example above, "Bob" and "Batman" should be reversed. See my comment in #859. 

In @anriseth's example with mixed types in a column, I don't think `unstack` was expected to handle that case. Maybe your `melt` line wasn't what you wanted. This works:

```julia
longdf = melt(iris, [:Species,:id])
widedf = unstack(longdf, :id, :variable, :value)
```

**Comment by amellnik** [comment]
Wow, good catch.

**Comment by anriseth** [comment]
I see @tshort. This was an example from the docs, and I thought it worked in previous versions. Anyway if that's not expected behaviour, pull-request #860 fixes the issue.
