### ISSUE TITLE
Dataframe subsetting

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/DataFrames.jl#857]
Currently `df[v]`  always subsets a dataframe by columns

Would not it better to subset by row when `v` is a vector of boolean or integer, while keeping column subsetting when `v` is a vector of symbols?

I don't like the current behavior for two reasons. It is generally considered bad behavior to rely on the ordering of columns in a dataset. Moreover, subsetting a dataframe by rows is a very common operation.

**Comment by johnmyleswhite** [comment]
I think we should not flip the semantics based on the type of `v`. Single index == column subset is a simple rule that doesn't need to be altered.

**Comment by nalimilan** [comment]
Agreed, better keep the semantics simple. Anyway indexing rows to subset is no longer the recommended approach, better use query macros.
