### ISSUE TITLE
unexpected unstack() behavior

### ISSUE THREAD

**Issue by tcovert** [JuliaStats/DataFrames.jl#859]
I'm getting different results between unstack(df, :key, :value) and unstack(df, :id, :key, :value) on a DataFrame with exactly those three columns.  The output of unstack(df, :id, :key, :value) is closer to what I expected to see than the output of unstack(df, :key, :value), but I don't think either is exactly right.  My read of the documentation is that these two statements should generate the same output.

In particular, the DataFrame produced by unstack(df, :key, :value) has fewer unique values of ":id" than the DataFrame produced by unstack(df, :id, :key, :value), which I believe does have the right set of unique values.  

However, the DataFrame produced by unstack(df, :id, :key, :value) has columns ":key" and all of the unique values of :key in the original DataFrame.  In this case, the contents of :key are indeed the (correct) unique values of :id in the original DataFrame.

Here is a gist demonstrating this phenomenon: https://gist.github.com/tcovert/7310d9ad79c1b46d0fe0

I suppose I can always use unstack(df, :id, :key, :value) and rename the first column, but I figured I should find out if I'm doing something else wrong.

**Comment by tshort** [comment]
It looks like the `unstack(df, :key, :value)` version is broken. The "payload" looks right, but the key column is wrong. That column needs to be sorted. If you sort that, it might fix the problem. You could add a line to sort it just after this line:

https://github.com/JuliaStats/DataFrames.jl/blob/master/src/abstractdataframe/reshape.jl#L224

**Comment by tcovert** [comment]
Cool, so should I try to fix it on my machine and submit a pull request?  I did that once before but might need a refresher on how it works.  Do you know of a reference?

**Comment by tshort** [comment]
That'd be great, @tcovert! Here is a general guide to github pull requests:

https://help.github.com/articles/using-pull-requests/

I still sometimes refer to the following notes for git advice:

https://gist.github.com/dmbates/2712118#file_julia_git_pull_request.md

It's also helpful to include a test that captures the bug.

**Comment by amellnik** [comment]
@tshort -- This has been open for a while, were you about to figure out what's going on?  I've poked through it a bit but I'm having a hard time following the code and have stuck with the unstack(df, :id, :key, :value) version as a result.

**Comment by tshort** [comment]
@amellnik, try changing the line linked above to the following:

```julia
    df1 = df[g.idx[g.starts], g.cols]
```

If that works, then someone needs to make the change, write a test case, and submit a pull request.

**Comment by tshort** [comment]
Fixed by #883.

**Comment by GordStephen** [comment]
A disclaimer in the docs warning that the last tagged release (6 Oct 2015) has known bugs might be helpful - I'm on 0.6.10 (not master)  and just spent a few hours thinking I was going crazy because of this issue!

**Comment by tshort** [comment]
Hopefully, we'll get a new version tagged soon.
