### ISSUE TITLE
DataFrames and ArrayViews

### ISSUE THREAD

**Issue by bramtayl** [JuliaStats/DataFrames.jl#863]
It seems like DataFrames is pretty smart about not duplicating data when it doesn't need to when doing column operations. However, it doesn't seem like the same is true for row operations. Integrating DataFrames and ArrayViews (or another similar package) might be useful in this regard. This would enable something like this. I think.

```{julia}
function slice{T <: Integer}(df::DataFrames, indices::Vector{T})
  df2 = copy(df)
  for i in 1:( size(df)[2] )
    df2.columns[i] = ArrayViews.view(df.columns[i], indices)
  end
  df2
end
```

**Comment by bramtayl** [comment]
Actually, an array view for each individual column seems wasteful because the sub-setting information would be the same for each. An array view of the entire dataframe seems better.

**Comment by johnmyleswhite** [comment]
This issue should be blocked on the views-by-default changes that are planned for the Arraymageddon release of 0.5. Until then, I think we shouldn't invest any eng effort on an ArrayViews-based solution.

**Comment by tshort** [comment]
Also, DataFrames already has something like your `slice` above with `sub` and the `SubDataFrame`. The SubDataFrame stores a view into another AbstractDataFrame. It doesn't use ArrayViews; it stores the row indexes separately. 

https://github.com/JuliaStats/DataFrames.jl/blob/master/src/subdataframe/subdataframe.jl#L14
