### ISSUE TITLE
using DataFrames results in LoadError in fresh Julia install on Fedora 21

### ISSUE THREAD

**Issue by allswellthatsmaxwell** [JuliaStats/DataFrames.jl#866]
Below I have pasted the successful package addition & building of DataFrames, followed by the failed loading of the package. I have tried uninstalling and reinstalling Julia through yum, and also manually removed my local package repository on reinstall. The problem persists. I have tried the same as root and get the same error.

I get the same error with DataArrays, but am able to successfully add, build, and "using" the packages ArgParse, Curl, and DoubleDouble.

uname -a on my system gives "Linux localhost.localdomain 4.1.5-100.fc21.x86_64 #1 SMP Tue Aug 11 00:24:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux".
julia --version gives "julia version 0.4.0-dev".

julia> Pkg.add("DataFrames")
INFO: Initializing package repository /home/mson/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of DataArrays from git://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of DataFrames from git://github.com/JuliaStats/DataFrames.jl.git
INFO: Cloning cache of Docile from git://github.com/MichaelHatherly/Docile.jl.git
INFO: Cloning cache of GZip from git://github.com/JuliaLang/GZip.jl.git
INFO: Cloning cache of Reexport from git://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SortingAlgorithms from git://github.com/JuliaLang/SortingAlgorithms.jl.git
INFO: Cloning cache of StatsBase from git://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of StatsFuns from git://github.com/JuliaStats/StatsFuns.jl.git
INFO: Installing ArrayViews v0.6.3
INFO: Installing Compat v0.6.0
INFO: Installing DataArrays v0.2.18
INFO: Installing DataFrames v0.6.9
INFO: Installing Docile v0.5.16
INFO: Installing GZip v0.2.17
INFO: Installing Reexport v0.0.2
INFO: Installing SortingAlgorithms v0.0.5
INFO: Installing StatsBase v0.7.1
INFO: Installing StatsFuns v0.1.3
INFO: Package database updated

julia> Pkg.build("DataFrames"))

julia> using DataFrames
Warning: Method definition call(Type{IPv4},AbstractString) in module Base at socket.jl:33 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:49.
Warning: Method definition call(Type{IPv6},AbstractString) in module Base at socket.jl:76 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:50.
Warning: Method definition isless(T<:IPAddr,T<:IPAddr) in module Base at socket.jl:5 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:55.
Warning: Method definition call(Type{Dict{K,V}},Any) in module Base at dict.jl:375 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:67.
Warning: Method definition round(Type{T<:Integer},Integer) in module Base at int.jl:255 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:83.
Warning: New definition 
    round(Type{T<:Integer},Real) at /home/mson/.julia/v0.4/Compat/src/Compat.jl:84
is ambiguous with: 
    round(Type{T},Rational{T<:Integer}) at rational.jl:282.
To fix, define 
    round(Type{_<:Integer},Rational{T<:Integer})
before the new definition.
Warning: Method definition ceil(Type{T<:Integer},Integer) in module Base at int.jl:258 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:83.
Warning: New definition 
    ceil(Type{T<:Integer},Real) at /home/mson/.julia/v0.4/Compat/src/Compat.jl:84
is ambiguous with: 
    ceil(Type{T},Rational{T<:Integer}) at rational.jl:275.
To fix, define 
    ceil(Type{_<:Integer},Rational{T<:Integer})
before the new definition.
Warning: Method definition floor(Type{T<:Integer},Integer) in module Base at int.jl:257 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:83.
Warning: New definition 
    floor(Type{T<:Integer},Real) at /home/mson/.julia/v0.4/Compat/src/Compat.jl:84
is ambiguous with: 
    floor(Type{T},Rational{T<:Integer}) at rational.jl:274.
To fix, define 
    floor(Type{_<:Integer},Rational{T<:Integer})
before the new definition.
Warning: Method definition trunc(Type{T<:Integer},Integer) in module Base at int.jl:256 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:83.
Warning: New definition 
    trunc(Type{T<:Integer},Real) at /home/mson/.julia/v0.4/Compat/src/Compat.jl:84
is ambiguous with: 
    trunc(Type{T},Rational{T<:Integer}) at rational.jl:273.
To fix, define 
    trunc(Type{_<:Integer},Rational{T<:Integer})
before the new definition.
Warning: Method definition srand(Base.Random.MersenneTwister,Array{UInt32,1}) in module Random at random.jl:104 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:133.
Warning: Method definition srand(Base.Random.MersenneTwister,) in module Random at random.jl:155 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:149.
Warning: Method definition rand(Base.Random.MersenneTwister,Type{UInt64}) in module Random at random.jl:232 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:154.
Warning: Method definition rand(Base.Random.MersenneTwister,Type{UInt128}) in module Random at random.jl:237 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:155.
Warning: Method definition rand(Base.Random.MersenneTwister,Type{Int64}) in module Random at random.jl:243 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:158.
Warning: Method definition rand(Base.Random.MersenneTwister,Type{Int128}) in module Random at random.jl:244 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:158.
Warning: New definition 
    rand(Base.Random.MersenneTwister,Type{T<:Union(Float16,Float32)}) at /home/mson/.julia/v0.4/Compat/src/Compat.jl:162
is ambiguous with: 
    rand(Union(Base.Random.MersenneTwister,Base.Random.RandomDevice),Type{Float16}) at random.jl:216.
To fix, define 
    rand(Base.Random.MersenneTwister,Type{Float16})
before the new definition.
Warning: New definition 
    rand(Base.Random.MersenneTwister,Type{T<:Union(Float16,Float32)}) at /home/mson/.julia/v0.4/Compat/src/Compat.jl:162
is ambiguous with: 
    rand(Union(Base.Random.MersenneTwister,Base.Random.RandomDevice),Type{Float32}) at random.jl:219.
To fix, define 
    rand(Base.Random.MersenneTwister,Type{Float32})
before the new definition.
Warning: Method definition rand(Base.Random.AbstractRNG,Type{Complex{T<:Real}}) in module Random at random.jl:248 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:163.
Warning: Method definition rand(Base.Random.AbstractRNG,Type{T<:Top},(Int64...,)) in module Random at random.jl:255 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:172.
Warning: Method definition srand() in module Random at random.jl:167 overwritten in module Compat at /home/mson/.julia/v0.4/Compat/src/Compat.jl:178.
Warning: could not import Base.evaluate into StatsBase
ERROR: LoadError: LoadError: LoadError: UndefVarError: @_div64 not defined
 in eval at ./no file
while loading /home/mson/.julia/v0.4/DataArrays/src/indexing.jl, in expression starting on line 23
while loading /home/mson/.julia/v0.4/DataArrays/src/DataArrays.jl, in expression starting on line 63
while loading /home/mson/.julia/v0.4/DataFrames/src/DataFrames.jl, in expression starting on line 14

**Comment by simonster** [comment]
Based on the huge number of warnings, I'm guessing your copy of Julia doesn't have the build number in `VERSION`, perhaps due to JuliaLang/julia#10851. This will basically break everything. But to confirm, can you post the output of `versioninfo()`?

**Comment by allswellthatsmaxwell** [comment]
Sure:

julia> versioninfo()
Julia Version 0.4.0-dev
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.5.0
