### ISSUE TITLE
@document not defined

### ISSUE THREAD

**Issue by merl-dev** [JuliaStats/DataFrames.jl#869]
Just updated packages, using DataFrames 0.6.9 and julia 0.3.11 getting the following when I 
run 
julia> using DataFrames

ERROR: @document not defined
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/ubuntu/.julia/v0.3/DataFrames/src/DataFrames.jl, in expressi                                              on starting on line 20

Thanks for any help

My version info
julia> versioninfo()
Julia Version 0.3.11
Commit 483dbf5 (2015-07-27 06:18 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by AggeKA** [comment]
I am getting same error after a Pkg.update

Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3



Pkg.status()
3 required packages:
 - DataFrames                    0.6.8
 - Gadfly                        0.3.13
 - Jewel                         1.0.5
38 additional packages:
 - ArrayViews                    0.6.2
 - Calculus                      0.1.8
 - Codecs                        0.1.4
 - Color                         0.4.6
 - Compat                        0.4.9
 - Compose                       0.3.13
 - Contour                       0.0.7
 - DataArrays                    0.2.16
 - DataStructures                0.3.11
 - Dates                         0.3.2
 - Distances                     0.2.0
 - Distributions                 0.7.6
 - Docile                        0.5.12
 - DualNumbers                   0.1.3
 - FactCheck                     0.2.8
 - FixedPointNumbers             0.0.8
 - GZip                          0.2.17
 - Graphics                      0.1.0
 - Grid                          0.3.10
 - Hexagons                      0.0.3
 - ImmutableArrays               0.0.8
 - Iterators                     0.1.8
 - JSON                          0.4.4
 - JuliaParser                   0.6.2
 - KernelDensity                 0.1.1
 - LNR                           0.0.1
 - Lazy                          0.9.1
 - Loess                         0.0.3
 - MacroTools                    0.1.0
 - NaNMath                       0.0.2
 - Optim                         0.4.2
 - PDMats                        0.3.3
 - Reexport                      0.0.2
 - Requires                      0.1.3
 - Showoff                       0.0.4
 - SortingAlgorithms             0.0.5
 - StatsBase                     0.6.15
 - WoodburyMatrices              0.1.0

**Comment by merl-dev** [comment]
so the solution is just to load "using Docile" before DataFrames, all runs smoothly once again

**Comment by AggeKA** [comment]
Fixed it for me too.  Thanks!

**Comment by nalimilan** [comment]
The fact that a workaround exists doesn't mean that the bug shouldn't be fixed. `using DataFrames` should work without calling anything else.

**Comment by merl-dev** [comment]
@nalimilan: I agree

**Comment by simonster** [comment]
Maybe fixed by https://github.com/JuliaLang/Compat.jl/pull/144?
