### ISSUE TITLE
Conflicts with Images

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/DataFrames.jl#877]
With 0.4.0 and the DataFrames master, I'm seeing tons of conflicts in the namespace

    using DataFrames
    import Images.imread

results in this wall of warnings (using Images does the same):

    WARNING: both StatsBase and Base export "histrange"; uses of it in module DataArrays must be qualified
    WARNING: both StatsBase and Base export "midpoints"; uses of it in module DataArrays must be qualified
    WARNING: both DataArrays and StatsBase export "autocor"; uses of it in module DataFrames must be qualified
    WARNING: both DataArrays and StatsBase export "histrange"; uses of it in module DataFrames must be qualified
    WARNING: both DataArrays and StatsBase export "inverse_rle"; uses of it in module DataFrames must be qualified
    WARNING: both DataArrays and StatsBase export "midpoints"; uses of it in module DataFrames must be qualified
    WARNING: both DataArrays and StatsBase export "rle"; uses of it in module DataFrames must be qualified
    WARNING: New definition 
        +(AbstractArray, Images.AbstractImageDirect) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:20
    is ambiguous with: 
        +(DataArrays.DataArray, AbstractArray) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\operators.jl:326.
    To fix, define 
        +(DataArrays.DataArray, Images.AbstractImageDirect)
    before the new definition.
    WARNING: New definition 
        +(AbstractArray, Images.AbstractImageDirect) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:20
    is ambiguous with: 
        +(DataArrays.AbstractDataArray, AbstractArray) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\operators.jl:349.
    To fix, define 
        +(DataArrays.AbstractDataArray, Images.AbstractImageDirect)
    before the new definition.
    WARNING: New definition 
        .+(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:22
    is ambiguous with: 
        .+(AbstractArray, Union{DataArrays.PooledDataArray, DataArrays.DataArray}, AbstractArray...) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:284.
    To fix, define 
        .+(Images.AbstractImageDirect, Union{DataArrays.PooledDataArray, DataArrays.DataArray})
    before the new definition.
    WARNING: New definition 
        -(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:35
    is ambiguous with: 
        -(AbstractArray, DataArrays.DataArray) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\operators.jl:326.
    To fix, define 
        -(Images.AbstractImageDirect, DataArrays.DataArray)
    before the new definition.
    WARNING: New definition 
        -(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:35
    is ambiguous with: 
        -(AbstractArray, DataArrays.AbstractDataArray) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\operators.jl:349.
    To fix, define 
        -(Images.AbstractImageDirect, DataArrays.AbstractDataArray)
    before the new definition.
    WARNING: New definition 
        -(AbstractArray, Images.AbstractImageDirect) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:37
    is ambiguous with: 
        -(DataArrays.DataArray, AbstractArray) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\operators.jl:326.
    To fix, define 
        -(DataArrays.DataArray, Images.AbstractImageDirect)
    before the new definition.
    WARNING: New definition 
        -(AbstractArray, Images.AbstractImageDirect) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:37
    is ambiguous with: 
        -(DataArrays.AbstractDataArray, AbstractArray) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\operators.jl:349.
    To fix, define 
        -(DataArrays.AbstractDataArray, Images.AbstractImageDirect)
    before the new definition.
    WARNING: New definition 
        .-(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:40
    is ambiguous with: 
        .-(AbstractArray, Union{DataArrays.PooledDataArray, DataArrays.DataArray}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:272.
    To fix, define 
        .-(Images.AbstractImageDirect, Union{DataArrays.PooledDataArray, DataArrays.DataArray})
    before the new definition.
    WARNING: New definition 
        .*(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:51
    is ambiguous with: 
        .*(AbstractArray, Union{DataArrays.PooledDataArray, DataArrays.DataArray}, AbstractArray...) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:282.
    To fix, define 
        .*(Images.AbstractImageDirect, Union{DataArrays.PooledDataArray, DataArrays.DataArray})
    before the new definition.
    WARNING: New definition 
        .*(AbstractArray, Images.AbstractImageDirect) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:52
    is ambiguous with: 
        .*(Union{DataArrays.PooledDataArray, DataArrays.DataArray}, AbstractArray...) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:282.
    To fix, define 
        .*(Union{DataArrays.PooledDataArray, DataArrays.DataArray}, Images.AbstractImageDirect)
    before the new definition.
    WARNING: New definition 
        ./(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:55
    is ambiguous with: 
        ./(AbstractArray, Union{DataArrays.PooledDataArray, DataArrays.DataArray}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:272.
    To fix, define 
        ./(Images.AbstractImageDirect, Union{DataArrays.PooledDataArray, DataArrays.DataArray})
    before the new definition.
    WARNING: New definition 
        .<(Images.AbstractImageDirect{Bool, N<:Any}, AbstractArray{Bool, N<:Any}) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:129
    is ambiguous with: 
        .<(AbstractArray{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:317.
    To fix, define 
        .<(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}})
    before the new definition.
    WARNING: New definition 
        .<(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:130
    is ambiguous with: 
        .<(AbstractArray{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:317.
    To fix, define 
        .<(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}})
    before the new definition.
    WARNING: New definition 
        .<(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:130
    is ambiguous with: 
        .<(AbstractArray, Union{DataArrays.PooledDataArray, DataArrays.DataArray}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:272.
    To fix, define 
        .<(Images.AbstractImageDirect, Union{DataArrays.PooledDataArray, DataArrays.DataArray})
    before the new definition.
    WARNING: New definition 
        .>(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:131
    is ambiguous with: 
        .>(AbstractArray{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:317.
    To fix, define 
        .>(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}})
    before the new definition.
    WARNING: New definition 
        .>(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:131
    is ambiguous with: 
        .>(AbstractArray, Union{DataArrays.PooledDataArray, DataArrays.DataArray}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:272.
    To fix, define 
        .>(Images.AbstractImageDirect, Union{DataArrays.PooledDataArray, DataArrays.DataArray})
    before the new definition.
    WARNING: New definition 
        .==(Images.AbstractImageDirect{Bool, N<:Any}, AbstractArray{Bool, N<:Any}) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:133
    is ambiguous with: 
        .==(AbstractArray{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:317.
    To fix, define 
        .==(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}})
    before the new definition.
    WARNING: New definition 
        .==(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:134
    is ambiguous with: 
        .==(AbstractArray{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:317.
    To fix, define 
        .==(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.DataArray{Bool, N<:Any}, DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}})
    before the new definition.
    WARNING: New definition 
        .==(Images.AbstractImageDirect, AbstractArray) at C:\Users\amellnik\.julia\v0.4\Images\src\algorithms.jl:134
    is ambiguous with: 
        .==(AbstractArray, Union{DataArrays.PooledDataArray, DataArrays.DataArray}) at C:\Users\amellnik\.julia\v0.4\DataArrays\src\broadcast.jl:272.
    To fix, define 
        .==(Images.AbstractImageDirect, Union{DataArrays.PooledDataArray, DataArrays.DataArray})
    before the new definition.

I understand that there's some situations why we would expect conflicts between different modules, but the fact that we're defining ```+(DataArrays.DataArray, Images.AbstractImageDirect)``` somehow makes me think it's a bug.  If this looks like it's due to something with Images let me know and I'll migrate the issue there.

**Comment by vchuravy** [comment]
See JuliaStats/DataArrays.jl#168 for a bit more context.

**Comment by amellnik** [comment]
Whoops, I now realize I even saw that go by. I'll follow up there.
