### ISSUE TITLE
Problem of the embedded double-quote characters

### ISSUE THREAD

**Issue by jskDr** [JuliaStats/DataFrames.jl#878]
Referring to wikipedia (https://en.wikipedia.org/wiki/Comma-separated_values)
although it is defined that each of the embedded double-quote characters must be represented by a pair of double-quote characters, writetable() in DataFraes uses a pair of \" instead of a pair of double-quote characters(""). Because of it, I can not read csv files in libreoffice and pandas/python. How can I solve this problem? I could not find a solution although I try to change parameters in writetable.

**Comment by johnmyleswhite** [comment]
The way to fix this is to edit the code in this file https://github.com/JuliaStats/DataFrames.jl/blob/0beba61c1e59bc32a799d111f160ee0c56bddda9/src/abstractdataframe/io.jl to handle other escaping rules.

**Comment by jskDr** [comment]
@johnmyleswhite I will try to update for mine and I suggest to add one parameter in writetable() to handle it. 

In addition, writeable() adds quote characters for all strings regardless of its need. In general, the csv file does not mark quote characters for string unless it is necessary. If a string includes a separate character such as comma, it is necessary to use the quote characters. By avoiding to use in unnecessary cases, the manipulation of a csv file in a text editor is easy in addition to saving some storage espeically for short text cases. Although I try to find to turn off this default behaviour of writetable() I couldn't find it. Even if this issues is not urgent than the issue above, I elaborated for the discussion in the community.

**Comment by quinnj** [comment]
`readtable` is deprecated and CSV.jl can handle custom setting of `escapechar` and `quotechar` characters when parsing.
