### ISSUE TITLE
prettier show function

### ISSUE THREAD

**Issue by gdkrmr** [JuliaStats/DataFrames.jl#881]
the ```show``` function for ```DataFrame``` could be nicer, here is a proposal:

![dataframe_show_function](https://cloud.githubusercontent.com/assets/12512930/10921029/93994fec-8273-11e5-9c4a-0faf585cde62.png)

**Comment by johnmyleswhite** [comment]
Please write a pull request and we'll review it. It's unlikely we'll change this functionality, though.

**Comment by StefanKarpinski** [comment]
+1 – I like that display much better.

**Comment by gdkrmr** [comment]
there are also different styles, any suggestions? https://en.wikipedia.org/wiki/Box-drawing_character

**Comment by nalimilan** [comment]
Good idea, but why not drop the vertical lines entirely? In many scientific publications, tables are drawn without them, and the result is quite good. The alignment of contents is enough for the eye to identify the columns.

If people still prefer the version with lines, I'd vote for the less heavy character available, e.g. `│` (U+2502). It would also help if the REPL stopped using bold by default (https://github.com/JuliaLang/julia/pull/11250).

**Comment by gdkrmr** [comment]
Light vertical lines, bold horizontal lines:
![dataframe_show_function_verical_light](https://cloud.githubusercontent.com/assets/12512930/11020904/dfd63d88-862f-11e5-9f4d-eacd112de0a3.png)

**Comment by nalimilan** [comment]
Do you have any idea about how to make the vertical lines  join?

**Comment by gdkrmr** [comment]
The problem is the space between lines in the terminal which cannot be 
changed in most terminal emulators, I think it is possible in iterm.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaStats/DataFrames.jl/pull/888.

**Comment by clayms** [comment]
converting output of Jupyter notebook with DataFrames output to a pdf with nbconvert causes the following error.

```
[! Package ucs Error: Unknown Unicode character 9474 = U+2502,
(ucs)                possibly declared in uni-37.def.
(ucs)                Type H to see if it is available with options.

See the ucs package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.410 │ Row │ A │ B       │ C    │

? 
! Emergency stop.
 ...                                              

l.410 │ Row │ A │ B       │ C    │

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.](url)  
```

U+2502: BOX DRAWINGS LIGHT VERTICAL

Any suggestions?

I also posted question on [StackExchange](http://stackoverflow.com/questions/37312663/julia-dataframe-output-in-jupyter-error-in-nbconvert).
