### ISSUE TITLE
Select number of rows to be displayed in a DataFrame

### ISSUE THREAD

**Issue by rsmith31415** [JuliaStats/DataFrames.jl#886]
I asked about this on julia-users but I haven't received a response.

To put it simply, is there an equivalent to `pandas.set_option('display.max_rows', 500)` in order to control the number of displayed rows in a DataFrame? Currently, we have a summary that shows the first and last rows and that's okay, but sometimes you want to see more rows, particularly when the DataFrame is not very large.

I tried to use `showall` but this doesn't provide a good control on the number of rows to be displayed and also uses the text/plain representation instead of the more user-friendly HTML representation.

**Comment by simonster** [comment]
`head`/`tail`?

**Comment by rsmith31415** [comment]
Unfortunately, head and tail still provide a summary:

```
julia> x = DataFrame(x=1:500, y=1:500);
julia> head(x, 50)
50x2 DataFrames.DataFrame
| Row | x  | y  |
|-----|----|----|
| 1   | 1  | 1  |
| 2   | 2  | 2  |
| 3   | 3  | 3  |
| 4   | 4  | 4  |
| 5   | 5  | 5  |
| 6   | 6  | 6  |
| 7   | 7  | 7  |
| 8   | 8  | 8  |
⋮
| 42  | 42 | 42 |
| 43  | 43 | 43 |
| 44  | 44 | 44 |
| 45  | 45 | 45 |
| 46  | 46 | 46 |
| 47  | 47 | 47 |
| 48  | 48 | 48 |
| 49  | 49 | 49 |
| 50  | 50 | 50 |
```

**Comment by rsmith31415** [comment]
@simonster Is there some update with respect to this issue / feature request ?

**Comment by tshort** [comment]
You can do `showall(head(x, 150))`. 

I'm closing this. If you have a more specific feature request, please reopen or start a new issue.

You could also write an enhancement and submit a PR. I'm not sure a global setting is the way to go, though.

**Comment by rsmith31415** [comment]
@tshort Thank you for your response. As I said, `showall` removes the nice HTML representation. If you don't favor a global setting, maybe an additional option in `showall` to let the user keep the HTML representation? Looking at large DataFrames without HTML is fairly painful.

**Comment by tshort** [comment]
Changing HTML display requires a change to [writemime](https://github.com/JuliaStats/DataFrames.jl/blob/master/src/abstractdataframe/io.jl#L132). 

According to #30, you can already affect the lines of HTML output with `ENV["LINES"]`. I haven't tried it.

**Comment by rsmith31415** [comment]
Actually, ENV["LINES"] is actually useful. It does work in a jupyter notebook due to [IJulia](https://github.com/JuliaLang/IJulia.jl#default-display-size), though:

>When Julia displays a large data structure such as a matrix, by default it truncates the display to a given number of lines and columns. In IJulia, this truncation is to 30 lines and 80 columns by default. You can change this default by the LINES and COLUMNS environment variables, respectively, which can also be changed within IJulia via ENV (e.g. ENV["LINES"] = 60). (Like in the REPL, you can also display non-truncated data structures via print(x).)

I'm not sure if that works in the REPL. At least, I haven't been able to make it work there.

**Comment by tshort** [comment]
HTML display and REPL display are handled differently.
