### ISSUE TITLE
melt with non-julia identifier column names

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/DataFrames.jl#899]
I have a csv file that roughly looks like this:
````
Year,Name of country 1, Name of country 2
1950, 5., 6.
1951, 6., 8.
````
The real file has more columns and rows.

I want to bring this into tidy format, so that I have a DataFrame that looks like this:
````
Year, Region, Value
1950, Name of country 1, 5.
1950, Name of country 2, 6.
1951, Name of country 1, 6.
1951, Name of country 2, 8.
````
Right now I read the file with readtable into a DataFrame and then use
````julia
melt(df, :Year)
````
This gives me the right structure, but now all the country names are messed up, e.g. they look like “Name_of_country_1” instead of “Name of country 1”.

I understand why that is the case, i.e. readtable converts strings into symbols and has to insert these underscores. One can hack around it, but I’m wondering whether might be some way to make this (to me at least very common) operation easier.

Maybe safe the original column header name as a string in addition to the symbol version, and use the original in the melt operation? Not sure I like that idea myself, but maybe someone else has a better idea.

**Comment by johnmyleswhite** [comment]
The tradeoff here is that the importer makes sure that you can always assume that column names are valid identifiers. I'm honestly not sure what assumption is best.

**Comment by tshort** [comment]
There's a new option to leave names as is when reading csv files. You'll need the devel version. See https://github.com/JuliaStats/DataFrames.jl/pull/896.

**Comment by davidanthoff** [comment]
@tshort: Ha, perfect! I love it when someone has committed a fix for an issue 7 days before I thought of the problem in the first place ;)
