### ISSUE TITLE
can't use array(df) to convert DataFrame to arrays in Julia

### ISSUE THREAD

**Issue by b2bblackuser** [JuliaStats/DataFrames.jl#900]
I used to have a previous version of DataFrames and used array(df) to convert DataFrames to normal Julia arrays: 
e.g., init_obs = array(iData[1,1])'
where iData is a dataframe.

I cannot get the same thing working using DataFrame v0.6.10. Does anyone know how to solve the problem?

**Comment by HouwndDawg** [comment]
I'm not entirely sure what your goal is, but as for the example you give, the shortest solution would be to just drop the entire array(). That is,
```
init_obs = iData[1,1] 
```
will give you init_obs as the first cell of your dataframe, taking on the type of the data in that cell. 
```
all_obs = Array(iData[m:M, n:N])
```
will give you a regular matrix of your data. Note the capital on Array().

**Comment by quinnj** [comment]
I don't think there's anything actionable here; feel free to re-open if there's still an issue.
