### ISSUE TITLE
writetable from dataframe

### ISSUE THREAD

**Issue by tahenti** [JuliaStats/DataFrames.jl#902]
i am wishing to write a table of dataframe on a csv file. but the command write the final dataframe df calculated by my code. a would like to ask is there is  command to append into the file. so i will retrieve all my df generated by the code and not only the final. ( i would like to write over the same file)

**Comment by nalimilan** [comment]
Please use the julia-stats mailing list for help requests, and keep GitHub for bug reports. (FWIW, I also think you should improve your description as I don't really understand what you want to do.)
