### ISSUE TITLE
OutOfMemoryError() with cross join

### ISSUE THREAD

**Issue by anshuljoshi** [JuliaStats/DataFrames.jl#904]
```
ERROR: OutOfMemoryError()
 in rep at /home/anshul/.julia/v0.4/DataArrays/src/extras.jl:83
 in crossjoin at /home/anshul/.julia/v0.4/DataFrames/src/abstractdataframe/join.jl:254
 in join at /home/anshul/.julia/v0.4/DataFrames/src/abstractdataframe/join.jl:200
```
I am getting this error working with a ~20MB dataset. All other joins are working fine. Would appreciate any help regarding this.

**Comment by alyst** [comment]
How many rows do you have? If it's something >10^5, the observed behaviour is not surprising.

**Comment by anshuljoshi** [comment]
16GB RAM. Rows are around ~10^5. If it is an observed behavior, then is there any solution to this?

**Comment by alyst** [comment]
Then cross join would give you ~10^10 rows. It's quite a lot, at least for in-memory desktop application. I suppose the solution depends on what you want to do. If you plan to filter the result of cross join, maybe  you can do some prefiltering by using the other types of join.

**Comment by anshuljoshi** [comment]
Okay, thanks for the help
