### ISSUE TITLE
Warning: New definition of write()

### ISSUE THREAD

**Issue by colbec** [JuliaStats/DataFrames.jl#906]
Using julia on openSUSE Leap 42.1 full patched:

Version 0.5.0-dev+2500 (2016-02-04 08:22 UTC)
Commit c200b4c* (0 days old master)
x86_64-suse-linux

julia> using DataFrames
WARNING: New definition 
    write(GZip.GZipStream, Array{#T<:Any, N<:Any}) at /home/colin/.julia/v0.5/GZip/src/GZip.jl:456
is ambiguous with: 
    write(Base.IO, Array{UInt8, N<:Any}) at io.jl:154.
To fix, define 
    write(GZip.GZipStream, Array{UInt8, N<:Any})
before the new definition.

--------------------
julia> Pkg.checkout("DataFrames")
INFO: Checking out DataFrames master...
INFO: Pulling DataFrames latest master...
INFO: No packages to install, update or remove

julia> versioninfo()
Julia Version 0.5.0-dev+2500
Commit c200b4c* (2016-02-04 08:22 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1

**Comment by kmsquire** [comment]
Looks like this is actually a problem with GZip.jl--can you reopen this issue [there](https://github.com/JuliaLang/GZip.jl/issues)?

Note that if you're trying to use Julia for actual work, it would be best to stick with v0.4.3 for now.  But if you're willing to live on the bleeding edge... :-)

**Comment by kmsquire** [comment]
See https://github.com/JuliaLang/julia/issues/14935.
