### ISSUE TITLE
Warning tty_size() deprecated in 0.5.0

### ISSUE THREAD

**Issue by colbec** [JuliaStats/DataFrames.jl#907]
In:
julia> dfz = readtable("test.csv")
WARNING: tty_size is deprecated. use `displaysize(io)` as a replacement
 in depwarn(::ASCIIString, ::Symbol) at ./deprecated.jl:64
 in tty_size() at ./deprecated.jl:920
 in show(::IOContext{Base.Terminals.TTYTerminal}, ::DataFrames.DataFrame, ::Bool, ::Symbol, ::Bool) at /home/colin/.julia/v0.5/DataFrames/src/abstractdataframe/show.jl:440

I tried inserting blindly the displaysize() suggestion but this made matters worse since it did not know `io`.

------
julia> versioninfo()
Julia Version 0.5.0-dev+2500
Commit c200b4c* (2016-02-04 08:22 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1

**Comment by nalimilan** [comment]
`io` is probably the first argument to `show` (i.e. the `::IOContext` one). Does it work if you use it?

**Comment by colbec** [comment]
An example of the use of `tty_size()` here is in the function `getchunkbounds` on line 199. This function takes arguments `maxwidths` and `splitchunks` only. Other functions in the same show.jl file have `io` as a specific argument where necessary. I'm afraid I am not following your suggestion regarding `::IOContext` - this string does not appear in the file at all.

**Comment by nalimilan** [comment]
I was referring to the stack trace. Anyway, I think you'll have to make `getchunkbounds` take an `availablewidth` argument, and use it to pass the result of `displaysize(io)[2]` from `showrows()`. That should work fine.
