### ISSUE TITLE
Warnings in Base.getindex(r::DataFrameRow, idx::AbstractArray)

### ISSUE THREAD

**Issue by LouisMagarshack** [JuliaStats/DataFrames.jl#913]
Hi all,

I am using Julia 0.4.3 on Ubuntu, and I get a deprecation warning from the following bit of code:

```julia
using DataFrames
df = DataFrame(a = collect(1:10), b = collect(1:10), c = collect(1:10))
for row in eachrow(df)
  println(row[2:end])
end
```

The warning is the following:

> WARNING: [a] concatenation is deprecated; use collect(a) instead
>  in depwarn at deprecated.jl:73
>  in oldstyle_vcat_warning at ./abstractarray.jl:29
>  [inlined code] from In[3]:4
>  in anonymous at no file:0
>  in include_string at loading.jl:266
>  in execute_request_0x535c5df2 at /home/ubuntu/.julia/v0.4/IJulia/src/execute_request.jl:177
>  in eventloop at /home/ubuntu/.julia/v0.4/IJulia/src/IJulia.jl:141
>  in anonymous at task.jl:447
> while loading In[3], in expression starting on line 3

I think this can be fixed by implementing Base.getindex(r::DataFrameRow, idx::AbstractArray) as follows:

```julia
Base.getindex(r::DataFrameRow, idx::AbstractArray)
  return DataFrameRow(r.df[collect(idx)], r.row)
end
```

Cheers,
Louis

**Comment by nalimilan** [comment]
Thanks. But I wonder why the current code is written as `r.df[[idx]]`, while it looks like `r.df[idx]` would be enough. Tests still pass if I make this change.

This line comes from commit e47accba by @kmsquire.

**Comment by alyst** [comment]
`[]` would be required if `idx` is "scalar", but in this case it's declared as a vector, so should be fine without them.

**Comment by LouisMagarshack** [comment]
I opened https://github.com/JuliaStats/DataFrames.jl/pull/928 but I'm not sure how to add a test for that. I'm also not sure if there are implications I'm missing here.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaStats/DataFrames.jl/pull/928.
