### ISSUE TITLE
constructor should allow vector of vectors even if the outer type is not `Any`

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/DataFrames.jl#915]
Currently

``` julia
DataFrame(Any[[1:10], [21:30]], [:A, :B])
```

works, but it fails when the first argument has a more specific element type, eg `Array{Array{Int64,1},1}`. Removing `Any` from

``` julia
function DataFrame(columns::Vector{Any},
                   cnames::Vector{Symbol} = gennames(length(columns)))
    return DataFrame(columns, Index(cnames))
end
```

would fix this, but before submitting a PR I wanted to ask if this has other implications, or if there is a reason for the restriction.

**Comment by alyst** [comment]
I think it's a good idea to fix this ctor. Potentially, there might be clashes with the other DataFrame ctors, in particular the one that expects the vector of Associatives. PR would be the best way to check for that for each Julia version.
And we definitely need to add a test for `columns::Vector{T}`, `T != Any`, another good reason for a PR.

**Comment by quinnj** [comment]
This works on current master
```julia
julia> DataFrame([collect(1:10), collect(21:30)], [:A, :B])
10×2 DataFrames.DataFrame
│ Row │ A  │ B  │
├─────┼────┼────┤
│ 1   │ 1  │ 21 │
│ 2   │ 2  │ 22 │
│ 3   │ 3  │ 23 │
│ 4   │ 4  │ 24 │
│ 5   │ 5  │ 25 │
│ 6   │ 6  │ 26 │
│ 7   │ 7  │ 27 │
│ 8   │ 8  │ 28 │
│ 9   │ 9  │ 29 │
│ 10  │ 10 │ 30 │
```
