### ISSUE TITLE
accessing describe()

### ISSUE THREAD

**Issue by kleinash** [JuliaStats/DataFrames.jl#926]
Hi,

Is there a way to access the info coming out of the describe()? Something like:
info = describe(df)
len = info.Length
t = info.Type
x = info.Unique
etc..

Thx

**Comment by nalimilan** [comment]
Please use the mailing list for questions and keep GitHub for issues.

`describe` prints directly to the REPL, so you can't access the values. But you can easily compute them manually using the relevant functions.
