### ISSUE TITLE
Date types and durations

### ISSUE THREAD

**Issue by tcovert** [JuliaStats/DataFrames.jl#937]
right now, code like this doesn't work:
`df = DataFrame(d1 = [Date(2016,3,31), Date(2015,3,31)], d2 = [Date(2016,3,30), Date(2015,3,30)])
df[:delta] = df[:d1] - df[:d2]`

Here is the error I get from the second line of this expression:

> ERROR: MethodError: `convert` has no method matching convert(::Type{Date}, ::Base.Dates.Day)
> This may have arisen from a call to the constructor Date(...),
> since type constructors fall back to convert methods.
> Closest candidates are:
>   Date(::Base.Dates.Period...)
>   Date(::Any)
>   Date(::Any, ::Any)
>   ...

My hunch is that its not working because DataFrames expects that the output of the differencing operator should have the same type as one (or both) of the inputs to the differencing operator.  With a Date, this isn't true, as the difference is a "Day" as opposed to a "Date"

My current workaround to this is to convert each DataArray to an array, do the math on the two arrays, and then assign that to a new column in df:
`df[:delta] = convert(Array, df[:d1]) - convert(Array, df[:d2])`

Is there a more natural way to do this?

**Comment by nalimilan** [comment]
The problem is actually in DataArrays, you don't need a data frame to reproduce it:
```julia
da = DataArray([Date(2016,3,31), Date(2015,3,31)])
da - da
```

The definition for arithmetic operations uses `promote_type(eltype(a), eltype(b))` as the element type of the result. Looks like it should use `Base.promote_op(Base.SubFun(), eltype(a), eltype(b))`.

Note that NullableArrays.jl uses `promote_op`, and still suffers from the same bug, so there might be something else to do.

**Comment by quinnj** [comment]
This now works because DataFrames doesn't require DataArrays as underlying storage
```julia
julia> df = DataFrame(d1 = [Date(2016,3,31), Date(2015,3,31)], d2 = [Date(2016,3,30), Date(2015,3,30)])
2×2 DataFrames.DataFrame
│ Row │ d1         │ d2         │
├─────┼────────────┼────────────┤
│ 1   │ 2016-03-31 │ 2016-03-30 │
│ 2   │ 2015-03-31 │ 2015-03-30 │

julia> df[:delta] = df[:d1] - df[:d2]
2-element Array{Base.Dates.Day,1}:
 1 day
 1 day
```
