### ISSUE TITLE
DataFrames and DistributedArrays

### ISSUE THREAD

**Issue by fabgrei** [JuliaStats/DataFrames.jl#938]
Hi, I came across the following problem, the last line runs forever:

```
using DistributedArrays
using DataFrames
x = ones(3, 3)
DataFrame(x)
```

leave out the first line, and everything is fine.

julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
...

**Comment by quinnj** [comment]
No longer happens on master
