### ISSUE TITLE
Simplifying syntax for by()

### ISSUE THREAD

**Issue by fisherc2** [JuliaStats/DataFrames.jl#940]
The syntax for the by() function is a little verbose. I was wondering if there might be a way to simplify it. 

For example, the current syntax is

by(df,[:condition1;condition2],DataFrame(mean = mean(df[:RT]), sd =std(df[:RT])))

It would be nice to have a simpler syntax such as

by(df,[:condition1;condition2],[mean = mean(RT) sd = std(RT)])

**Comment by tshort** [comment]
You can't simplify this without macros. `by` uses anonymous functions, so your current syntax should be (untested):

```julia
by(df, [:condition1, :condition2], df -> DataFrame(mean = mean(df[:RT]), sd =std(df[:RT])))
```

For a more concise syntax, see [DataFramesMeta](https://github.com/JuliaStats/DataFramesMeta.jl/) (again, untested):

```julia
@by(df, [:condition1, :condition2], mean = mean(:RT), sd =std(:RT)))
```

**Comment by fisherc2** [comment]
I was not aware of the DataFramesMeta package. It seems to work. Thanks and sorry for the noise!
