### ISSUE TITLE
Panel support / N-D labeled arrays

### ISSUE THREAD

**Issue by femtotrader** [JuliaStats/DataFrames.jl#941]
Hello,

Python Pandas provides a nice data structure called Panel for 3 dimensional data.
http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel

xarray (previously known as xray) http://xarray.pydata.org/ provides N-D labeled arrays.

This kind of data structure are very convenient.

See for example this example in Python (using Pandas DataReader http://pandas-datareader.readthedocs.org/en/latest/ )

``` python
from pandas_datareader import data as web
data = web.DataReader("GOOG", "IBM", "2015-04-01", "2015-04-10")

In [7]: web.DataReader("IBM", "google", "2015-04-01", "2015-04-10")
Out[7]:
              Open    High     Low   Close   Volume
Date
2015-04-01  160.23  160.62  158.39  159.18  3700791
2015-04-02  159.52  162.54  158.89  160.45  4671578
2015-04-06  159.69  162.80  158.70  162.04  3465682
2015-04-07  161.67  163.84  161.62  162.07  3147975
2015-04-08  161.72  163.55  161.01  161.85  2524323
2015-04-09  161.70  162.47  160.72  162.34  2263490
2015-04-10  162.34  163.33  161.25  162.86  2515703

In [8]: web.DataReader("MSFT", "google", "2015-04-01", "2015-04-10")
Out[8]:
             Open   High    Low  Close    Volume
Date
2015-04-01  40.60  40.76  40.31  40.72  36865322
2015-04-02  40.66  40.74  40.12  40.29  37487476
2015-04-06  40.34  41.78  40.18  41.54  39223692
2015-04-07  41.61  41.91  41.31  41.53  28809375
2015-04-08  41.46  41.69  41.04  41.42  24753438
2015-04-09  41.25  41.62  41.25  41.48  25723861
2015-04-10  41.63  41.95  41.41  41.72  28022002

In [9]: panel = web.DataReader(["IBM", "MSFT"], "google", "2015-04-01", "2015-04-10")
In [10]: panel
<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 7 (major_axis) x 2 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2015-04-01 00:00:00 to 2015-04-10 00:00:00
Minor_axis axis: IBM to MSFT

In [13]: panel["Open"]  # or panel.loc['Open',:,:]
Out[13]:
               IBM   MSFT
Date
2015-04-01  160.23  40.60
2015-04-02  159.52  40.66
2015-04-06  159.69  40.34
2015-04-07  161.67  41.61
2015-04-08  161.72  41.46
2015-04-09  161.70  41.25
2015-04-10  162.34  41.63
```

I wonder if such data structure exists in Julia.

It will be very convenient for my project [DataReader.jl](https://github.com/femtotrader/DataReader.jl).

Kind regards

**Comment by nalimilan** [comment]
Am I right that this is basically a list of `DataFrames` with some convenience functions? If so, that could easily be experimented in a separate package. DataFrames.jl already contains `GroupedDataFrame` for split-apply-combine operations, which might give some inspiration.

I also wonder whether this isn't closer to [TimeSeries](https://github.com/JuliaStats/TimeSeries.jl/) and [AxisArrays](https://github.com/mbauman/AxisArrays.jl) than to DataFrames.

**Comment by femtotrader** [comment]
I don't find in DataFrame.jl the concept of index... this is something very important when creating a Panel from dict of DataFrame as it should automatically add NaN for missing values when some index doesn't exist in one of the DataFrame.
Thanks for pointing to TimeSeries and AxisArrays. I will have a look

**Comment by ViralBShah** [comment]
[NDSparseData.jl](https://github.com/JuliaComputing/NDSparseData.jl) does have the concept of indexes, and is in very early stages, but is something I think we will pursue. Would be great if you could tell us what operations on indexed data you would like to do.

**Comment by nalimilan** [comment]
Wouldn't you simply specify the name of the column to use as an index when converting a `DataFrame` to a panel object? Why does this information need to be stored in the data frame?

**Comment by femtotrader** [comment]
@ViralBShah  Some features

Support for both integer indexing and label indexing.
Slicing
Rename dimension
Rename columns
Groupby operation
Datetime indexing
Resampling
Easy serialization

**Comment by johnmyleswhite** [comment]
The separation of indices and columns is one of the strangest things about Pandas. Wes can give lots of good arguments for why you might want to do it, and Hadley will remind you that real databases don't do any of these tricks. It may be useful for financial applications in the same way that big data stacks distinguish partitions and columns because they're not capable of generating indices for tables but need efficient filtering.

**Comment by femtotrader** [comment]
Hierarchical indexing is also a great feature (MultiIndex) !

**Comment by quinnj** [comment]
I think this would be best pursued as an independent package.
