### ISSUE TITLE
Type of existing column set to Any on replacement instead of more specific type

### ISSUE THREAD

**Issue by neilpanchal** [JuliaStats/DataFrames.jl#947]
I have an XML parser that builds a dataframe. All columns are type "Any". All elements are AbstractStrings. How best to convert the columns to appropriate types?

I have tried the following approach:

Using the map function
First, let's confirm the element type.

```
>> typeof(df[:A][1])
SubString{ASCIIString}
```

Now map and convert the entire column to Int64.

`df[:A] = map(parse, df[:A]);
`

Check the element type:

```
>> typeof(df[:A][1]) 
Int64
```

Check the column eltype

```
>> eltype(df[:A])
Any
```

There appears to be no easy way to change the eltype of a column?

**Comment by nalimilan** [comment]
This works:
```julia
df[:A] = convert(DataArray{Int}, df[:A])
```

Looks like something is missing here. Since `map(parse, df[:A])` is a `Vector{Int}`, the type of the column should be updated accordingly.

**Comment by nalimilan** [comment]
The problem is actually in DataArrays.jl:
```julia
julia> A=DataArray(["1","2"]);

julia> typeof(map(parse, A))
DataArrays.DataArray{Any,1}
```

**Comment by quinnj** [comment]
DataFrames no longer relies on DataArrays by default; feel free to re-open an issue at the DataArrays.jl package.
