### ISSUE TITLE
readtable with string as data / StringIO

### ISSUE THREAD

**Issue by femtotrader** [JuliaStats/DataFrames.jl#948]
Hello,

I would like to use readtable http://dataframesjl.readthedocs.io/en/latest/io.html with string as data

I'm looking for a similar Julia function than Python StringIO https://docs.python.org/2/library/stringio.html

Does something similar exists ?

so instead of doing

```julia
using DataFrames
using Requests

# Iris data set
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# with error checking
r = Requests.get_streaming(url; timeout = 30.0)
if r.response.status / 100 != 2
    error("Error downloading data")
end
df = readtable(r)
```

I'd like to be able to do

```julia
using DataFrames
using Requests

# Iris data set
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# with error checking
r = Requests.get(url; timeout = 30.0)
if r.status / 100 != 2
    error("Error downloading data")
end
io = StringIO(r)  # doesn't exist
df = readtable(io)
```

Any idea ?

Kind regards

**Comment by nalimilan** [comment]
I don't really get the reason why you'd prefer the second solution over the first one, but isn't `IOBuffer` what you're looking for?

**Comment by femtotrader** [comment]
`IOBuffer` is exactly what I was looking for. Thanks.
