### ISSUE TITLE
Broadcast is ambiguous

### ISSUE THREAD

**Issue by ignaciomartin** [JuliaStats/DataFrames.jl#949]
DataFrames v"0.7.0" leads to warnings about an ambiguity in broadcast:

![image](https://cloud.githubusercontent.com/assets/19220563/15088484/f17e3164-13f4-11e6-9fa0-7c3e2af4b1d6.png)

**Comment by ararslan** [comment]
There have been several releases since 0.7.0; I think this has been fixed. At least I haven't been seeing it anywhere. I'll close this for now but let me know if you run into the problem again.
