### ISSUE TITLE
Showing DataFrame generates characters that cannot be displayed in console on windows

### ISSUE THREAD

**Issue by mmagnuski** [JuliaStats/DataFrames.jl#953]
An example below:
![df display issue in windows console](https://cloud.githubusercontent.com/assets/8452354/15179514/8aab448c-177c-11e6-84b7-bcec8a804005.PNG)

My `versioninfo()`:
```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1226 v3 @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by nalimilan** [comment]
Ah, that's annoying. It's unfortunate that we cannot use these Unicode characters without breaking display in the Windows console. Which Windows version is that?

I guess we have no choice but reverting this until we ship Julia with a better console.

Cc: @gdkrmr

**Comment by nalimilan** [comment]
Good news, Wikipedia made me realize the thin lines were supported, only the thick ones are a problem for Windows. Sounds reasonable to use thin lines for now.

**Comment by mmagnuski** [comment]
Just btw - these characters generally seem to be wider and therefore the dataframe display is a bit weird (the row separating column names and values is too long). Does it display nicely on non-windows computers or is that intentional?

**Comment by femtotrader** [comment]
Here is how a DataFrame appears under OS X (10.10.5)

![capture d ecran 2016-05-13 a 11 25 49](https://cloud.githubusercontent.com/assets/5049737/15243715/9e07cf28-18fd-11e6-800f-3872b7502c16.png)

That's not perfectly aligned

**Comment by KristofferC** [comment]
Looks like a constant offset though.

**Comment by mmagnuski** [comment]
On Windows it's much worse. I'm on my phone, but once I get to the computer I will post a screenshot.

**Comment by mmagnuski** [comment]
But see examples [here](https://github.com/JuliaStats/DataFrames.jl/issues/952).

**Comment by nalimilan** [comment]
Sorry, but we can't do anything about it, that's most likely a console issue. Is the new (thin) character better?

**Comment by mmagnuski** [comment]
The thin character works great, thanks! :smile: 
BTW, you can notice in the GitHub diff (on Chrome/Windows), that the character width seems to be different:
![df_char_len_01](https://cloud.githubusercontent.com/assets/8452354/15276585/8bdcedf6-1aec-11e6-8ddf-3c8f4e8344d7.PNG)

**Comment by nalimilan** [comment]
Good to know! You can't really trust what is shown on GitHub since it will depend on the exact font used. It's surprising that the widths differ, since AFAICT this is supposed to be a fixed-width font...

**Comment by mmagnuski** [comment]
Oh yes, the point was just to show that at least in some fixed-width fonts this character has different width. Looks like a bug in `Fonts.jl` :wink:
