### ISSUE TITLE
NaNs instead of NAs in data frames

### ISSUE THREAD

**Issue by laborhm** [JuliaStats/DataFrames.jl#958]
using RDatasets, DataFrames
df = dataset("mlmRev","Gcsemv");

Produces:
│ 1 │ "20920" │ "16" │ "M" │ 23.0 │ NaN │
│ 2 │ "20920" │ "25" │ "F" │ NaN │ 71.2 │
│ 3 │ "20920" │ "27" │ "F" │ 39.0 │ 76.8 │
│ 4 │ "20920" │ "31" │ "F" │ 36.0 │ 87.9 │
│ 5 │ "20920" │ "42" │ "M" │ 16.0 │ 44.4 │
│ 6 │ "20920" │ "62" │ "F" │ 36.0 │ NaN │
│ 7 │ "20920" │ "101" │ "F" │ 49.0 │ 89.8 │
│ 8 │ "20920" │ "113" │ "M" │ 25.0 │ 17.5 │
│ 9 │ "20920" │ "146" │ "M" │ NaN │ 32.4 │
│ 10 │ "22520" │ "1" │ "F" │ 48.0 │ 84.2 │

RDatasets in Win10 produce NaN-values for unvailable values (NAs) as compared to Unices.
So the funcs dropna() and complete_cases() 'do not work' as needed, no filtering done.

**Comment by amellnik** [comment]
I think this is an issue with RDatasets rather than with DataFrames.

**Comment by nalimilan** [comment]
This was a bug in DataFrames's support for R data files, which is being moved to a separate package, RData.jl. I've filed an issue there instead: https://github.com/JuliaStats/RData.jl/issues/10
