### ISSUE TITLE
No matching HTML_Escape error

### ISSUE THREAD

**Issue by awang94** [JuliaStats/DataFrames.jl#963]
I'm getting an error on the following code segment `DataFrame(ODBC.query(dsn, "select Sex from persons WHERE persons.PersonId = 2"))` and other similar queries where the result contains a string. The error message is:
MethodError: `html_escape` has no method matching html_escape(::UTF16String)

 in writemime at C:\Users\Adam\.julia\v0.4\DataFrames\src\abstractdataframe\io.jl:184
 in sprint at iostream.jl:206
 in display_dict at C:\Users\Adam\.julia\v0.4\IJulia\src\execute_request.jl:39

When I remove the DataFrame conversion or if the result is of a different data type, I don't have any issues. Oddly enough, this was working perfectly fine just an hour ago. I wasn't having any trouble with strings. I spent some time trying to install node-julia, and then came back to this, where I encountered this error for the first time. Has anyone seen this before? Thanks!

**Comment by nalimilan** [comment]
@andreasnoack Looks like you introduced this bug by replacing `html_escape(cell::AbstractString)` with `html_escape(cell::String)`. I don't think this is needed since that function merely calls `replace` on the string. You seem to have done that in a lot of places, not sure why.

**Comment by andreasnoack** [comment]
That was not intentional.

**Comment by andreasnoack** [comment]
Fixed by #964
