### ISSUE TITLE
No constant in ModelMatrix

### ISSUE THREAD

**Issue by lbittarello** [JuliaStats/DataFrames.jl#965]
The function ModelMatrix adds a column of ones to the covariate set, which is useful for regression models. But it is unnecessary at times. For example, you wouldn't want a constant if you're estimating a conditional density function. Could we make it optional?

**Comment by kleinschmidt** [comment]
You can omit the intercept (constant) term by putting a `0` or `-1` in the formula: `ModelMatrix(ModelFrame(y ~ 0 + x, df))`

**Comment by lbittarello** [comment]
Great! Thanks! I couldn't find anything about it in the documentation.

**Comment by nalimilan** [comment]
The docs are a bit sparse currently. FWIW, there have been discussions on the julia-stats mailing list about stopping this behavior, and instead requiring the user to write `1 + ` explicitly.
