### ISSUE TITLE
DataFrames output in Jupyter notebook - nbconvert to pdf error

### ISSUE THREAD

**Issue by clayms** [JuliaStats/DataFrames.jl#967]
converting output of Jupyter notebook with DataFrames output to a pdf with nbconvert causes the following error.

```
[! Package ucs Error: Unknown Unicode character 9474 = U+2502,
(ucs)                possibly declared in uni-37.def.
(ucs)                Type H to see if it is available with options.

See the ucs package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.410 │ Row │ A │ B       │ C    │

? 
! Emergency stop.
 ...                                              

l.410 │ Row │ A │ B       │ C    │

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.](url)  
```  
  \

U+2502: BOX DRAWINGS LIGHT VERTICAL

Any suggestions?

I also posted question on [StackExchange](http://stackoverflow.com/questions/37312663/julia-dataframe-output-in-jupyter-error-in-nbconvert).

**Comment by nalimilan** [comment]
I don't think that's an issue in DataFrames, though that's certainly annoying for its users. The error clearly appears in Jupyter, and that Unicode character is valid. I suggest you report the issue to them.

It would be interesting to try putting that character in a string and see whether it triggers the same bug.

**Comment by clayms** [comment]
@nalimilan  sounds good, migrated to [nbconvert](https://github.com/jupyter/nbconvert/issues/314).
