### ISSUE TITLE
Remove Docile from REQUIRE?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataFrames.jl#971]
In v0.5- the Docile package produces many warnings.  I think it can be removed from `REQUIRE` because we require `julia 0.4` and `Docile` is only necessary for version 3 and earlier.  This would also apply to other packages owned by JuliaStats

I can make these changes but I wanted to check first that this change would not be a problem.

**Comment by tshort** [comment]
Should be fine...

**Comment by ararslan** [comment]
Done in https://github.com/JuliaStats/DataFrames.jl/commit/a5579ec202fb41713c604bf747bd56a56c596ed1.
