### ISSUE TITLE
Index corruption by names!

### ISSUE THREAD

**Issue by bkamins** [JuliaStats/DataFrames.jl#972]
The following code

```
ds = DataFrame(eye(3))
names!(ds, fill(:a, 3))
```

correctly throws an error that `ds` has been corrupted by duplicate column names.
However, in interactive use it is a problem as afterwards `ds` is corrupted and is effectively unusable (eg. running `names!` again to fix the problem fails).

A simple fix (added in `names!` function after checking if `length(nms)==length(x.names)`) would make `nms` unique before performing the update. The solution proposed below is triggered only in interactive mode in order not to slow down `names!` in batch mode.

```
    if isinteractive()
        oldlen = length(nms)
        nms = make_unique(nms)
        if length(nms) != oldlen
            throw(ArgumentError("Duplicate symbols in nms."))
        end
    end
```

I do not know if the change is allowed by design assumptions of DataFrames as it makes behavior of `names!` differ depending on `isinteractive()`, so I post it as an issue (alternatively deduplication of `nms` could be performed always to keep the behavior consistent).

**Comment by nalimilan** [comment]
I agree this behavior isn't great. I would always check for duplicates, even when not in interactive mode. A PR would be appreciated.

Though I don't really understand your code: `make_unique` returns a vector of the same length as the input, so it doesn't allow detecting duplicates. AFAICT you should use `unique` instead. Also, it would be great to print the offending symbols in the error message to help the user.

**Comment by bkamins** [comment]
You are right. I incorrectly used `make_unique` (I looked it up from definition of constructor of `Index`). However, actually after thinking about it such approach would be consistent with behavior of 'Index` by generating new names for duplicate entries. The code could be more terse then:

```
function names!(x::Index, nms::Vector{Symbol})
    if length(nms) != length(x)
        throw(ArgumentError("Length of nms doesn't match length of x."))
    end
    newindex = Index(nms)
    x.names = newindex.names
    x.lookup = newindex.lookup
    return x
end
```
If this is an acceptable solution I could make a PR.

**Comment by nalimilan** [comment]
I think I would prefer failing by default when duplicate names are passed, possibly with a keyword argument to automatically add number suffixes. It's always better to make sure the user is aware of the duplication, which may reflect a bug. I guess this change could be made directly inside the `Index` constructor.
