### ISSUE TITLE
Unexpected handling of NA in DataFrame creation

### ISSUE THREAD

**Issue by bkamins** [JuliaStats/DataFrames.jl#974]
The following code produces unexpected results:

```
x = Any[1, NA, 2]
y = DataFrame(x = x)
z = DataArray(x)
```
Now `y[:x]` and `z` are of `DataArray` type and both report that they do not contain any `NA`s (their `na` field is set to a vector of `false`). This causes `complete_cases(y)` and `isna(z)` report unexpected results.

I would expect that if `NA`s injected into `Vector{Any}` then gets detected by the constructors of `DataFrame` and `DataArray`. I report it here (not in `DataArrays` package) because `upgrade_vector` in `dataframe.jl` explicitly sets `na` field to a vector of `false`.

**Comment by nalimilan** [comment]
I guess we could try to fix this (and a PR would be welcome), but I'm personally more interested in porting DataFrames to `Nullable`. I'll publish code soon to move toward that goal.

**Comment by bkamins** [comment]
Another example of the same nature (but this time it is quite probable to occur in practice):

```
x = DataFrame(a=1:5, b=NA)
```
and `x[:b]` is corrupted.

The solution fixing could be placed in the inner constructor of `DataArray` by adding `isna(d)` check:

```
type DataArray{T, N} <: AbstractDataArray{T, N}
    data::Array{T, N}
    na::BitArray{N}

    # Ensure data values and missingness metadata match
    function DataArray(d::Array{T, N}, m::BitArray{N})
        if size(d) != size(m)
            msg = "Data and missingness arrays must be the same size"
            throw(ArgumentError(msg))
        end
        # additionally check if d does not contain NA entries
        new(d, isna(d) | m)
    end
end
```

This should fix all possible problems. Is such solution acceptable?

**Comment by nalimilan** [comment]
Sounds indeed correct to me. Feel free to make a PR against DataArrays.jl.
