### ISSUE TITLE
eltype(df[:col]) now returns multiple types: DataType and/or Union

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/DataFrames.jl#976]
b009716f0450b2ef4d18eaf15b3b85c5b27573c3 introduces a quirk which broke DataFrame to DataTable conversion in the DataStreams package (https://github.com/JuliaDB/DataStreams.jl/issues/8).  This might be an entirely reasonable change, but I wanted to bring it up here in case it was an unintended change.  

On master, if I make a simple DataFrame the column types are as one might expect:

```julia
using DataFrames
df = DataFrame(A = collect(1:3), B=["A", "B", "sdfsdf"])
DataType[eltype(df[c]) for c in names(df)]
```

```
2-element Array{DataType,1}:
 Int64      
 ASCIIString
```

However, if I write this DataFrame to a file and read it back in:

```julia
writetable("temp.csv", df)
df2 = readtable("temp.csv")
DataType[eltype(df2[c]) for c in names(df)]
```

```
LoadError: MethodError: `convert` has no method matching convert(::Type{DataType}, ::Type{ByteString})
This may have arisen from a call to the constructor DataType(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, !Matched::T)
while loading In[7], in expression starting on line 3

 in setindex! at array.jl:313
 in anonymous at no file
```

This is because the `eltype` of `df2[:B]` is `Union` rather than `DataType`:

```julia
eltype(df2[:B])
```

```
Union{ASCIIString,UTF8String}
```

```julia
typeof(eltype(df2[:B]))
```

```
Union
```

(Note that every element of the column is still an ASCIIString.)  Prior to b009716f0450b2ef4d18eaf15b3b85c5b27573c3 `df2` would have the same eltypes as `df`.  

Should this be occurring?  If so, is there a suggested method of dealing with columns with Union types?

**Comment by nalimilan** [comment]
Yeah, that's unfortunate. I think https://github.com/JuliaStats/DataFrames.jl/pull/970 should fix it.

**Comment by nalimilan** [comment]
I just merged it. Could you try the latest development version with `Pkg.checkout("DataFrames")` and confirm that it's fixed? Then you'll be able to use `Pkg.free("DataFrames")` to go back to the latest stable release.

**Comment by amellnik** [comment]
All my systems work after that merge -- I'll pin to this and keep an eye on it.  Thanks!
