### ISSUE TITLE
string issue with readtable(...,nastrings=["blubb"])

### ISSUE THREAD

**Issue by krauti** [JuliaStats/DataFrames.jl#978]
Hi all,
I encountered a Problem with readtable(). I supply the argument `nastrings=["","NA","NaN"]` and I get the error posted below.
I guess this is fixed in #970, since it is closely related to #969, this is just to make sure it is taken into account...

```
MethodError: `convert` has no method matching convert(::Type{DataFrames.ParseOptions{S<:Union{ASCIIString,UTF8String}}}, ::Bool, ::Char, ::Array{Char,1}, ::Char, ::Array{ASCIIString,1}, ::Array{ByteString,1}, ::Array{ByteString,1}, ::Bool, ::Array{Symbol,1}, ::Array{DataType,1}, ::Bool, ::Char, ::Bool, ::Int64, ::Array{Int64,1}, ::Bool, ::Symbol, ::Bool, ::Bool)
This may have arisen from a call to the constructor DataFrames.ParseOptions{S<:Union{ASCIIString,UTF8String}}(...), since type constructors fall back to convert methods.
Closest candidates are:
  DataFrames.ParseOptions{S<:Union{ASCIIString,UTF8String}}(::Bool, ::Char, ::Array{Char,1}, ::Char, ::Array{S<:Union{ASCIIString,UTF8String},1}, !Matched::Array{S<:Union{ASCIIString,UTF8String},1}, !Matched::Array{S<:Union{ASCIIString,UTF8String},1}, ::Bool, ::Array{Symbol,1}, ::Array{T,1}, ::Bool, ::Char, ::Bool, ::Int64, ::AbstractArray{Int64,1}, ::Bool, ::Symbol, ::Bool, ::Bool)
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, !Matched::T)
 in readtable at ~/.julia/v0.4/DataFrames/src/dataframe/io.jl:857
```

PS: first time getting involved with developers... :)

**Comment by nalimilan** [comment]
Thanks for the report. I just merged https://github.com/JuliaStats/DataFrames.jl/pull/970. Could you try the latest development version with `Pkg.checkout("DataFrames")` and confirm that it's fixed? Then you'll be able to use `Pkg.free("DataFrames")` to go back to the latest stable release.

**Comment by krauti** [comment]
Thanks for the fast reply.
I did `Pkg.checkout("DataFrames"); using DataFrames`, and then re-run my script. Still, it hangs at `readtable()` with the following error:
```
MethodError: `convert` has no method matching convert(::Type{DataFrames.ParseOptions{S<:Union{ASCIIString,UTF8String}}}, ::Bool, ::Char, ::Array{Char,1}, ::Char, ::Array{ASCIIString,1}, ::Array{ByteString,1}, ::Array{ByteString,1}, ::Bool, ::Array{Symbol,1}, ::Array{DataType,1}, ::Bool, ::Char, ::Bool, ::Int64, ::Array{Int64,1}, ::Bool, ::Symbol, ::Bool, ::Bool)
This may have arisen from a call to the constructor DataFrames.ParseOptions{S<:Union{ASCIIString,UTF8String}}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  DataFrames.ParseOptions{S<:Union{ASCIIString,UTF8String}}(::Bool, ::Char, ::Array{Char,1}, ::Char, ::Array{S<:Union{ASCIIString,UTF8String},1}, !Matched::Array{S<:Union{ASCIIString,UTF8String},1}, !Matched::Array{S<:Union{ASCIIString,UTF8String},1}, ::Bool, ::Array{Symbol,1}, ::Array{T,1}, ::Bool, ::Char, ::Bool, ::Int64, ::AbstractArray{Int64,1}, ::Bool, ::Symbol, ::Bool, ::Bool)
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, !Matched::T)
 in readtable at ~/.julia/v0.4/DataFrames/src/dataframe/io.jl:851
```
I re-checked the Data-Frame status and found (as expected):
` - DataFrames                    0.7.2+             master`

**Comment by nalimilan** [comment]
OK, so it was indeed a good idea to check. Could you try after `Pkg.checkout("DataFrames", "nl/string")`? I have another series of fixes there.

**Comment by krauti** [comment]
sure, but the command fails (both if I execute it in `/home/user/` and `/home/user/.julia/v4.0/`. Anything that I need to do before?

**Comment by nalimilan** [comment]
What's the error?

**Comment by krauti** [comment]
failed process: Process(`git --work-tree=/home/user/.julia/v0.4/DataFrames --git-dir=/home/user/.julia/v0.4/DataFrames/.git checkout -q -B nl/string -t origin/nl/string`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in run at process.jl:531
 in anonymous at pkg/entry.jl:192
 in transact at pkg/git.jl:97
 in _checkout at pkg/entry.jl:190
 in checkout at pkg/entry.jl:205
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in include_string at ~/.julia/v0.4/CodeTools/src/eval.jl:28
 in include_string at ~/.julia/v0.4/CodeTools/src/eval.jl:32
 [inlined code] from ~/.julia/v0.4/Atom/src/eval.jl:39
 in anonymous at ~/.julia/v0.4/Atom/src/eval.jl:62
 in withpath at ~/.julia/v0.4/Requires/src/require.jl:37
 in withpath at ~/.julia/v0.4/Atom/src/eval.jl:53
 [inlined code] from ~/.julia/v0.4/Atom/src/eval.jl:61
 in anonymous at task.jl:58

**Comment by nalimilan** [comment]
Hmm, weird. Could you start Julia from `~/.julia/DataFrames` and then run `; git checkout nl/string`? You may need to run `; git fetch` first.

**Comment by krauti** [comment]
check. the error is resolved and from a first glance the data looks nice.
If further issues persist, I will come back here.

**Comment by krauti** [comment]
Thank you !!!

**Comment by nalimilan** [comment]
Thanks for checking!

**Comment by diegozea** [comment]
I had the same problem, `Pkg.checkout("DataFrames", "nl/string")` solved it for me ;)
