### ISSUE TITLE
readtable is 200x slower in master than 0.4, with huge memory allocation

### ISSUE THREAD

**Issue by sfchen** [JuliaStats/DataFrames.jl#983]
0.4
```julia
julia> @time readtable("a.csv")
  1.051377 seconds (5.51 M allocations: 241.775 MB, 40.19% gc time)
```

master
```julia
julia> @time readtable("a.csv")
286.593244 seconds (63.08 M allocations: 9.352 GB, 1.06% gc time)
```

See the attached a.csv

[a.csv.zip](https://github.com/JuliaStats/DataFrames.jl/files/292666/a.csv.zip)

**Comment by nalimilan** [comment]
This is simply due to deprecation warnings slowing down the code a lot. https://github.com/JuliaStats/DataFrames.jl/pull/984 fixes it.
