### ISSUE TITLE
silent error in writetable

### ISSUE THREAD

**Issue by diegozea** [JuliaStats/DataFrames.jl#986]
I was working with a `DataFrame` with more than 30_200_000 lines. I used `writetable` to save it. After that, I try to read it in a new Julia session and I get the next error with `readtable`:

```
ERROR: Saw 9005258 rows, 14 columns and 135078867 fields
* Line 1 has 17 columns

in error at ./error.jl:21
in findcorruption at /home/elin/.julia/v0.4/DataFrames/src/dataframe/io.jl:725
in readtable! at /home/elin/.julia/v0.4/DataFrames/src/dataframe/io.jl:796
in readtable at /home/elin/.julia/v0.4/DataFrames/src/dataframe/io.jl:859
in readtable at /home/elin/.julia/v0.4/DataFrames/src/dataframe/io.jl:953
```

The file was unfinished... Is there a `close`/`flush` missing in `writetable`?

Best,

**Comment by nalimilan** [comment]
Do you get the same error with a subset of the data?

**Comment by diegozea** [comment]
I'm sorry. I don't have it anymore...

**Comment by nalimilan** [comment]
Would be good to find a way to reproduce this with dummy data set

**Comment by quinnj** [comment]
`readtable` and `writetable` are now deprecated in favor of the CSV.jl and TextParse.jl packages.
