### ISSUE TITLE
__precompile__(true) but require failed to create a precompiled cache file 

### ISSUE THREAD

**Issue by Ward9250** [JuliaStats/DataFrames.jl#988]
Hi, I'm getting this error when I do `using DataFrames` from the Juli console in Atom Editor. Oddly, in the terminal, it works fine. It's something to do with precompiling Compat: 
```
WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.
WARNING: deserialization checks failed while attempting to load cache from /Users/bward/.julia/lib/v0.4/Docile.ji
INFO: Precompiling module Docile...
``` 

I'm not entirely sure if this is a DataFrames issue, a JunoLab issue or a bit of both.

Best,
Ben.

**Comment by nalimilan** [comment]
Looks like this is related to Docile or Compat. Please file issues there or ask for help on the mailing list.
