### ISSUE TITLE
bug in assigning values to dataframe subset?

### ISSUE THREAD

**Issue by floswald** [JuliaStats/DataFrames.jl#999]
hey,
i'm seeing this and wonder if I'm making a mistake or it's a bug. if mistake, how could i initiate multiple new columns, and then change only one of them as a subset?

```julia
julia> d = DataFrame(a=1:5,b=rand(5))
5×2 DataFrames.DataFrame
│ Row │ a │ b        │
├─────┼───┼──────────┤
│ 1   │ 1 │ 0.351535 │
│ 2   │ 2 │ 0.937234 │
│ 3   │ 3 │ 0.538115 │
│ 4   │ 4 │ 0.457804 │
│ 5   │ 5 │ 0.403712 │

julia> d[[:n1,:n2]] = 0.0
0.0

julia> d
5×4 DataFrames.DataFrame
│ Row │ a │ b        │ n1  │ n2  │
├─────┼───┼──────────┼─────┼─────┤
│ 1   │ 1 │ 0.351535 │ 0.0 │ 0.0 │
│ 2   │ 2 │ 0.937234 │ 0.0 │ 0.0 │
│ 3   │ 3 │ 0.538115 │ 0.0 │ 0.0 │
│ 4   │ 4 │ 0.457804 │ 0.0 │ 0.0 │
│ 5   │ 5 │ 0.403712 │ 0.0 │ 0.0 │

julia> d[d[:a].>3,:n1] = rand()
0.9127590254021951

julia> d
5×4 DataFrames.DataFrame
│ Row │ a │ b        │ n1       │ n2       │
├─────┼───┼──────────┼──────────┼──────────┤
│ 1   │ 1 │ 0.351535 │ 0.0      │ 0.0      │
│ 2   │ 2 │ 0.937234 │ 0.0      │ 0.0      │
│ 3   │ 3 │ 0.538115 │ 0.0      │ 0.0      │
│ 4   │ 4 │ 0.457804 │ 0.912759 │ 0.912759 │
│ 5   │ 5 │ 0.403712 │ 0.912759 │ 0.912759 │
```

**Comment by floswald** [comment]
In other words: whats the right way to create several new columns initiated at the same numeric value, without creating a reference of both columns to that numerical value as an object (changes to which would affect all new columns, as in the example above).

**Comment by nalimilan** [comment]
Sounds like a bug to me: there's little use in having two identical columns. Indeed a vector is created from the scalar (here, `0.0`), and its assigned to each new column without copying. To see the code, use `@less d[[:n1,:n2]] = 0.0`.

Would you make a PR to fix that? I think that code should just call `copy` on the vector. A small complication is that you need to insert the first column without a copy, and then insert remaining columns (if any) after calling `copy` (to avoid making an additional unused copy).

**Comment by johnmyleswhite** [comment]
I would say this is a bug we should fix.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaStats/DataFrames.jl/pull/1057.
